[build]
  command = "react-scripts build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "20"
  REACT_APP_API_URL = "https://genesisideas.school"

[[redirects]]
  from = "/api/*"
  to = "http://api.genesisideas.school/api/:splat"
  status = 200
  force = true
