import React from 'react';
import { PathwayPage } from './PathwayComponents';

const COLOR = '#C84B0A';

const META = {
  color: COLOR,
  title: 'Business & Marketing',
  subtitle: 'Build brands. Lead teams. Launch ideas.',
  emoji: '📊',
  courseEmoji: '📊',
  heroDescription: 'A 4-year pathway for students headed toward business, marketing, management, or entrepreneurship. You will learn how markets work, how consumers make decisions, how to build a brand, and how to lead teams — finishing with a real capstone brand launch project.',
  targets: ['Business Administration / Management', 'Marketing & Advertising', 'Entrepreneurship & Startups', 'International Business', 'Public Relations & Communications', 'Supply Chain & Operations'],
  collegeNote: 'Business schools at NYU Stern, UMich Ross, USC Marshall, and similar programs want to see evidence of business thinking — not just grades. This pathway gives you a structured four-year story: from business fundamentals through a senior brand launch project, with economics and statistics to show quantitative rigor.',
  stats: [{ label: 'AP Courses', value: 1 }],
};

const SCHEDULE = [
  { grade: 9, term: 'Fall', courses: [
    { name: 'English I',                  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra I',                  type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology',                    type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World History',              type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Physical Education',         type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Introduction to Business',   type: 'pathway',   credits: 0.5, courseId: 'biz-intro' },
  ]},
  { grade: 9, term: 'Spring', courses: [
    { name: 'English I — Writing',        type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Geometry',                   type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Environmental Science',      type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Geography',                  type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Health & Wellness',          type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Marketing Principles',       type: 'pathway',   credits: 0.5, courseId: 'biz-marketing' },
  ]},
  { grade: 10, term: 'Fall', courses: [
    { name: 'English II',                 type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra II',                 type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Chemistry',                  type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'U.S. History',              type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Digital Marketing & Social Media', type: 'pathway', credits: 0.5, courseId: 'biz-digital' },
    { name: 'Public Speaking',            type: 'supporting', credits: 0.5, dept: 'Communication' },
  ]},
  { grade: 10, term: 'Spring', courses: [
    { name: 'English II — Literature',    type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Pre-Calculus',              type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics Fundamentals',      type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World Politics',            type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Entrepreneurship',          type: 'pathway',   credits: 0.5, courseId: 'biz-entrepreneur' },
  ]},
  { grade: 11, term: 'Fall', courses: [
    { name: 'English III',               type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Statistics',                type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology — Advanced',        type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'AP Macroeconomics',         type: 'pathway',   credits: 1.0, courseId: 'biz-apmacro' },
  ]},
  { grade: 11, term: 'Spring', courses: [
    { name: 'English III — Literature',  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Trigonometry',              type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics — Mechanics',       type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Consumer Behavior',         type: 'pathway',   credits: 0.5, courseId: 'biz-consumer' },
    { name: 'Introduction to Accounting', type: 'supporting', credits: 0.5, dept: 'Business', note: 'Recommended' },
  ]},
  { grade: 12, term: 'Fall', courses: [
    { name: 'English IV — Writing & Communication', type: 'core', credits: 1.0, dept: 'English Language Arts' },
    { name: 'Calculus',                  type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Business Strategy',         type: 'pathway',   credits: 1.0, courseId: 'biz-strategy' },
    { name: 'AP Statistics',             type: 'supporting', credits: 1.0, dept: 'Mathematics', note: 'Strongly recommended for business analytics' },
  ]},
  { grade: 12, term: 'Spring', courses: [
    { name: 'English IV — Advanced Composition', type: 'core', credits: 1.0, dept: 'English Language Arts' },
    { name: 'Marketing Capstone: Brand Launch', type: 'pathway', credits: 1.0, courseId: 'biz-capstone' },
  ]},
];

const COURSES = [
  {
    id: 'biz-intro',
    name: 'Introduction to Business',
    grade: 9, term: 'Fall', credits: 0.5,
    description: 'A broad introduction to how businesses work — from the corner store to Apple. Explore the four functions of business (production, marketing, finance, management), understand how companies are structured and owned, and discover which area of business excites you most.',
    syllabus: {
      objectives: [
        'Identify the four primary functions of business and explain each',
        'Compare different forms of business ownership (sole proprietorship, partnership, corporation)',
        'Explain how supply and demand affect business decisions',
        'Analyze a real company\'s business model using a simple framework',
        'Identify an opportunity in your community and propose a basic solution',
      ],
      units: [
        { week: '1–2',   topic: 'What is Business?',         desc: 'Why businesses exist, what problems they solve, types of industries.' },
        { week: '3–4',   topic: 'Business Ownership',        desc: 'Sole proprietorships, partnerships, LLCs, corporations — pros, cons, liability.' },
        { week: '5–6',   topic: 'The Business Functions',    desc: 'Operations, marketing, finance, human resources — how they work together.' },
        { week: '7–8',   topic: 'Supply, Demand & Markets',  desc: 'How prices are determined, what shifts supply and demand, elasticity basics.' },
        { week: '9–10',  topic: 'Business Models',           desc: 'Revenue streams, cost structures — analyze Spotify, Nike, McDonald\'s.' },
        { week: '11–12', topic: 'Ethics & Social Responsibility', desc: 'CSR, stakeholder vs. shareholder theory, case studies of ethical failures.' },
        { week: '13',    topic: 'Global Business',           desc: 'Import/export, comparative advantage, multinational companies.' },
        { week: '14–16', topic: 'Business Idea Project',     desc: 'Identify a problem, propose a business solution, present a basic business concept.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=eDMEHMphTps', title: 'Intro to Business — Crash Course Business', channel: 'Crash Course', note: 'Watch the full Crash Course Business playlist — covers all topics in this course.' },
      { url: 'https://www.khanacademy.org/economics-finance-domain/microeconomics', title: 'Microeconomics — Supply & Demand', channel: 'Khan Academy', note: 'Use for the supply and demand unit (Weeks 7–8).' },
      { url: 'https://www.youtube.com/watch?v=lqSXY3PN_Xg', title: 'Business Models Explained', channel: 'The Business of Business', note: 'How to analyze what makes different companies\' business models work.' },
      { url: 'https://www.youtube.com/watch?v=XKQg6E0_jGQ', title: 'Corporate Social Responsibility', channel: 'ACCIS', note: 'Good overview of CSR and ethics in business for Week 11–12.' },
    ],
    quiz: [
      { q: 'Which business ownership structure provides the MOST personal liability protection?', opts: ['Sole Proprietorship', 'General Partnership', 'Corporation', 'Freelancer'], ans: 2, exp: 'A corporation is a separate legal entity — owners (shareholders) are generally not personally liable for the company\'s debts. Sole proprietors and general partners have unlimited personal liability.' },
      { q: 'When supply of a product decreases while demand stays the same, what typically happens to price?', opts: ['Price falls', 'Price rises', 'Price stays the same', 'Price becomes zero'], ans: 1, exp: 'Less supply with the same demand means more competition among buyers — prices rise. This is fundamental supply and demand economics.' },
      { q: 'Which of the four business functions is responsible for creating awareness and driving sales?', opts: ['Operations', 'Finance', 'Human Resources', 'Marketing'], ans: 3, exp: 'Marketing creates awareness, builds brand, and drives customers to buy. The other functions keep the business running but don\'t directly generate demand.' },
      { q: 'What is a "stakeholder" in a business context?', opts: ['Only the company\'s shareholders', 'Anyone who owns company stock', 'Any person or group affected by the business, including employees, customers, and community', 'A government regulator'], ans: 2, exp: 'Stakeholders include anyone affected by the company — employees, customers, suppliers, the community, and shareholders. This is broader than just shareholders (who own stock).' },
    ],
  },
  {
    id: 'biz-marketing',
    name: 'Marketing Principles',
    grade: 9, term: 'Spring', credits: 0.5,
    description: 'Why do you choose one brand over another? Marketing is the science and art of answering that question — and then using those answers to influence behavior. Learn the 4 Ps, understand target markets, and build your first complete marketing campaign.',
    syllabus: {
      objectives: [
        'Define and apply the 4 Ps of marketing (Product, Price, Place, Promotion)',
        'Identify and describe a target market using demographic and psychographic variables',
        'Distinguish between primary and secondary market research methods',
        'Analyze a brand\'s marketing strategy and identify its positioning',
        'Create a complete marketing campaign for a product or service',
      ],
      units: [
        { week: '1–2',   topic: 'What is Marketing?',         desc: 'Marketing vs. advertising, the role of marketing in business, brief history.' },
        { week: '3–4',   topic: 'The 4 Ps of Marketing',      desc: 'Product, Price, Place, Promotion — with examples from Apple, Nike, McDonald\'s.' },
        { week: '5–6',   topic: 'Target Markets & Segmentation', desc: 'Demographics, psychographics, geographic, behavioral segmentation.' },
        { week: '7–8',   topic: 'Market Research',            desc: 'Surveys, interviews, focus groups, secondary research, how to analyze data.' },
        { week: '9–10',  topic: 'Branding',                   desc: 'Brand identity, brand equity, positioning, competitive differentiation.' },
        { week: '11–12', topic: 'Promotion Mix',              desc: 'Advertising, PR, personal selling, sales promotion, direct marketing.' },
        { week: '13',    topic: 'Pricing Strategies',         desc: 'Cost-plus, competitive, value-based, penetration, skimming pricing.' },
        { week: '14–16', topic: 'Marketing Campaign Project', desc: 'Design a full campaign for a product: target market, positioning, 4 Ps, creative execution.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=wWIPqeZF00s', title: 'Marketing in Real Life — Crash Course Business', channel: 'Crash Course', note: 'Watch episodes 1–6 of Crash Course Business: Soft Skills for the marketing fundamentals.' },
      { url: 'https://www.youtube.com/watch?v=VsRJiAv9Kq8', title: 'Marketing Mix — 4 Ps Explained', channel: 'Marketing Business Network', note: 'Clear explanation of Product, Price, Place, Promotion with examples.' },
      { url: 'https://www.youtube.com/watch?v=3bBOl4-sqGw', title: 'Market Segmentation and Targeting', channel: 'Philip Kotler insights', note: 'Covers how companies identify and reach their target customers.' },
      { url: 'https://www.youtube.com/watch?v=PqKNyXkQpnk', title: 'How Apple Builds its Brand', channel: 'Marques Brownlee / MKBHD', note: 'Real-world case study of brand strategy and positioning — use for Week 9–10.' },
    ],
    quiz: [
      { q: 'Which of the 4 Ps refers to where and how a product is made available to consumers?', opts: ['Product', 'Price', 'Place', 'Promotion'], ans: 2, exp: 'Place (also called Distribution) includes all activities that make a product available to target customers — retail stores, e-commerce, wholesalers, direct sales.' },
      { q: 'A company segments its market by age, gender, and income. Which type of segmentation is this?', opts: ['Psychographic', 'Geographic', 'Behavioral', 'Demographic'], ans: 3, exp: 'Demographic segmentation divides the market by measurable population characteristics — age, gender, income, education level, family size.' },
      { q: 'What does "brand equity" mean?', opts: ['The total value of a company\'s assets', 'The additional value a brand name adds to a product above its functional value', 'The cost of registering a trademark', 'The amount spent on advertising'], ans: 1, exp: 'Brand equity is the premium customers are willing to pay because of the brand name. Nike shoes cost more than generic shoes partly because of brand equity.' },
      { q: 'A company launches a new product at a very low price to gain market share quickly, planning to raise the price later. This is called:', opts: ['Skimming pricing', 'Competitive pricing', 'Penetration pricing', 'Value-based pricing'], ans: 2, exp: 'Penetration pricing sets a low initial price to attract customers and build market share quickly. Companies then raise prices once the customer base is established.' },
    ],
  },
  {
    id: 'biz-digital',
    name: 'Digital Marketing & Social Media',
    grade: 10, term: 'Fall', credits: 0.5,
    description: 'Marketing has moved online. This course covers SEO, social media strategy, email marketing, paid advertising, content creation, and analytics. You will run a real social media campaign and analyze its performance using actual data.',
    syllabus: {
      objectives: [
        'Explain how search engines rank content and apply basic SEO principles',
        'Design and execute a social media content strategy for a brand',
        'Read and interpret marketing analytics dashboards (reach, engagement, CTR)',
        'Create a content calendar and write platform-appropriate copy',
        'Run and evaluate a small paid advertising campaign',
      ],
      units: [
        { week: '1–2',   topic: 'The Digital Landscape',     desc: 'How the internet changed marketing. Organic vs. paid. The customer journey online.' },
        { week: '3–4',   topic: 'SEO & Content Marketing',   desc: 'Keywords, on-page SEO, backlinks, content strategy, blogging.' },
        { week: '5–6',   topic: 'Social Media Strategy',     desc: 'Platform differences (Instagram vs. TikTok vs. LinkedIn), algorithms, best posting times.' },
        { week: '7–8',   topic: 'Content Creation',          desc: 'Writing for digital, video basics, graphic design tools (Canva), brand voice.' },
        { week: '9–10',  topic: 'Email Marketing',           desc: 'List building, segmentation, open rates, copywriting, A/B testing.' },
        { week: '11–12', topic: 'Paid Advertising',          desc: 'Google Ads vs. Meta Ads, CPC, CPM, targeting, budget allocation.' },
        { week: '13',    topic: 'Analytics & Measurement',   desc: 'Google Analytics basics, KPIs, attribution, reading reports.' },
        { week: '14–16', topic: 'Digital Campaign Project',  desc: 'Plan, run, and report on a real social media campaign for a school organization or mock brand.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=DvwS7cV9GmQ', title: 'Digital Marketing Full Course', channel: 'Simplilearn', note: '6-hour complete digital marketing course — use as the main reference for this course.' },
      { url: 'https://www.youtube.com/watch?v=T79Sv1Mwnas', title: 'SEO for Beginners — Complete Guide', channel: 'Ahrefs', note: 'The best beginner SEO explanation from one of the top SEO tools companies.' },
      { url: 'https://www.youtube.com/watch?v=HXiW-uWMIaQ', title: 'Social Media Marketing Strategy 2024', channel: 'Hootsuite', note: 'Up-to-date platform-by-platform breakdown of social media strategy.' },
      { url: 'https://www.youtube.com/watch?v=qZB3VCdJpY4', title: 'Google Analytics 4 Tutorial for Beginners', channel: 'Analytics Mania', note: 'Learn how to read real marketing data using Google\'s free analytics tool.' },
    ],
    quiz: [
      { q: 'What does SEO stand for?', opts: ['Social Engagement Optimization', 'Search Engine Optimization', 'Site Engagement Output', 'Standard Email Operations'], ans: 1, exp: 'SEO (Search Engine Optimization) is the practice of improving a website so it ranks higher in search engine results — driving more organic (free) traffic.' },
      { q: 'In paid advertising, what does "CTR" mean?', opts: ['Cost to Run', 'Click-Through Rate — the percentage of people who clicked your ad after seeing it', 'Customer Target Reach', 'Content Traffic Rate'], ans: 1, exp: 'Click-Through Rate = (Clicks / Impressions) × 100%. A CTR of 2% means 2 out of every 100 people who saw the ad clicked it. It measures ad effectiveness.' },
      { q: 'Which social media platform is MOST appropriate for B2B (business-to-business) marketing?', opts: ['TikTok', 'Snapchat', 'LinkedIn', 'Pinterest'], ans: 2, exp: 'LinkedIn is the professional network where business decision-makers spend time. It\'s the primary platform for B2B marketing, recruiting, and professional content.' },
      { q: 'What is A/B testing in email marketing?', opts: ['Testing if an email works on Android and iOS', 'Sending two versions of an email to different groups to see which performs better', 'Testing email deliverability', 'Checking if links work before sending'], ans: 1, exp: 'A/B testing sends version A to one group and version B to another, then measures which performs better (higher open rate, click rate). This is how marketers optimize their campaigns with data.' },
    ],
  },
  {
    id: 'biz-entrepreneur',
    name: 'Entrepreneurship',
    grade: 10, term: 'Spring', credits: 0.5,
    description: 'Turn an idea into a real business plan. This course covers opportunity recognition, customer discovery, product development, financial modeling, and pitching to investors. You will run customer interviews and present a full business plan at the end of the course.',
    syllabus: {
      objectives: [
        'Identify and evaluate entrepreneurial opportunities using design thinking',
        'Conduct customer discovery interviews and synthesize insights',
        'Build a business model canvas for a new venture',
        'Create a basic financial model (revenue, costs, break-even)',
        'Deliver a compelling 5-minute investor pitch',
      ],
      units: [
        { week: '1–2',   topic: 'Entrepreneurial Mindset',    desc: 'What makes entrepreneurs different. Failure as learning. Growth mindset.' },
        { week: '3–4',   topic: 'Opportunity Recognition',    desc: 'Finding problems worth solving. Trends, pain points, underserved markets.' },
        { week: '5–6',   topic: 'Customer Discovery',         desc: 'How to run customer interviews, the Jobs-to-Be-Done framework, validating assumptions.' },
        { week: '7–8',   topic: 'Business Model Canvas',      desc: 'Value proposition, customer segments, channels, revenue streams, cost structure.' },
        { week: '9–10',  topic: 'Product Development',        desc: 'MVP, prototyping, iterating based on feedback, product-market fit.' },
        { week: '11–12', topic: 'Financial Fundamentals',     desc: 'Revenue models, cost types, break-even analysis, basic cash flow.' },
        { week: '13',    topic: 'Funding & Growth',           desc: 'Bootstrapping, friends & family, angel investors, venture capital — what they want.' },
        { week: '14–16', topic: 'Business Plan & Pitch',      desc: 'Finalize business plan. Pitch to a panel of judges. Q&A on your model.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=IP0cUBWTgpY', title: 'How to Build a Startup — Steve Blank', channel: 'Udacity / Steve Blank', note: 'The foundational entrepreneurship course by the creator of the Customer Development methodology.' },
      { url: 'https://www.youtube.com/watch?v=QoAOzMTLP5s', title: 'Business Model Canvas Explained', channel: 'Alexander Osterwalder', note: 'The creator of the BMC explains how to use it — watch in Weeks 7–8.' },
      { url: 'https://www.youtube.com/watch?v=9uOETcuFjbE', title: 'How to Run Customer Interviews', channel: 'Y Combinator', note: 'Y Combinator advice on how to talk to customers — essential for Week 5–6.' },
      { url: 'https://www.youtube.com/watch?v=5B8KEn5TLfU', title: 'How to Pitch to Investors', channel: 'Y Combinator', note: 'Learn what investors look for and how to structure a compelling pitch.' },
    ],
    quiz: [
      { q: 'What is a "Business Model Canvas"?', opts: ['A financial spreadsheet', 'A one-page visual framework that describes how a business creates, delivers, and captures value', 'A type of market research survey', 'A legal business formation document'], ans: 1, exp: 'The Business Model Canvas (by Osterwalder) is a visual template on one page that maps all nine building blocks of a business: customers, value proposition, channels, revenue, costs, etc.' },
      { q: 'What is the purpose of customer discovery interviews?', opts: ['To sell your product to potential customers', 'To validate or invalidate your assumptions about the problem and customer before building anything', 'To gather testimonials for marketing', 'To determine the price of your product'], ans: 1, exp: 'Customer discovery interviews test your hypotheses. You\'re NOT selling — you\'re listening to understand if the problem you\'re solving is real and painful enough for people to pay for a solution.' },
      { q: 'What is "product-market fit"?', opts: ['When your product is perfectly priced', 'When a product satisfies a strong market demand — customers love it and it sells itself', 'When you have enough inventory to meet demand', 'When your product beats all competitors'], ans: 1, exp: 'Product-market fit means your product truly solves a real problem for a defined market. Signs: strong word-of-mouth, high retention, customers are disappointed if the product disappears.' },
      { q: 'Break-even analysis tells you:', opts: ['How much profit you will make', 'The point at which total revenue equals total costs — neither profit nor loss', 'How long until you get funding', 'The maximum price you can charge'], ans: 1, exp: 'Break-even is when Revenue = Total Costs. Above this point, you\'re profitable. Below it, you\'re losing money. It helps you understand minimum sales needed to survive.' },
    ],
  },
  {
    id: 'biz-apmacro',
    name: 'AP Macroeconomics',
    grade: 11, term: 'Fall', credits: 1.0,
    description: 'College-level economics focused on the big picture — how national and global economies function. GDP, unemployment, inflation, fiscal policy, monetary policy, and international trade. This course prepares you for the AP exam and gives you the economic literacy needed for any business career.',
    syllabus: {
      objectives: [
        'Explain what GDP measures and its limitations as an economic indicator',
        'Analyze the causes and effects of inflation and unemployment',
        'Describe how the Federal Reserve uses monetary policy to stabilize the economy',
        'Explain fiscal policy tools and their effects on aggregate demand',
        'Analyze international trade, exchange rates, and the balance of payments',
      ],
      units: [
        { week: '1–3',   topic: 'Basic Economic Concepts',   desc: 'Scarcity, opportunity cost, PPC, economic systems, circular flow model.' },
        { week: '4–5',   topic: 'Measuring the Economy',     desc: 'GDP, GDP per capita, real vs. nominal, CPI, unemployment rate calculation.' },
        { week: '6–7',   topic: 'National Income & Price Determination', desc: 'Aggregate demand, aggregate supply, equilibrium, demand shocks.' },
        { week: '8–9',   topic: 'Financial Sector',          desc: 'Money supply, banking, money multiplier, Federal Reserve, FOMC.' },
        { week: '10–11', topic: 'Monetary Policy',           desc: 'Interest rates, quantitative easing, inflation targeting, the Taylor Rule.' },
        { week: '12–13', topic: 'Fiscal Policy',             desc: 'Government spending, taxes, multiplier effect, crowding out, national debt.' },
        { week: '14',    topic: 'International Trade',       desc: 'Comparative advantage, trade policies, exchange rates, balance of payments.' },
        { week: '15–16', topic: 'AP Exam Prep',              desc: 'Free-response practice, multiple-choice review, graph interpretation skills.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=6_mfAOSaFEo', title: 'AP Macroeconomics — Full Course Review', channel: 'Heimler\'s History', note: 'The most popular AP Macro review channel — watch all episodes in order.' },
      { url: 'https://www.khanacademy.org/economics-finance-domain/ap-macroeconomics', title: 'AP Macroeconomics', channel: 'Khan Academy', note: 'Complete AP Macro curriculum with practice exercises — work through every unit.' },
      { url: 'https://www.youtube.com/watch?v=d8uTB5XorBw', title: 'Economics — Crash Course', channel: 'Crash Course', note: 'Watch episodes 20–35 for macroeconomics topics. Clear, entertaining explanations.' },
      { url: 'https://apclassroom.collegeboard.org/', title: 'AP Classroom — Official AP Macro Resources', channel: 'College Board', note: 'Official FRQs and progress checks. Use throughout the year for exam prep.' },
    ],
    quiz: [
      { q: 'What does GDP measure?', opts: ['A country\'s trade surplus', 'The total market value of all final goods and services produced within a country in a given year', 'The total wealth of all citizens', 'Government tax revenue'], ans: 1, exp: 'GDP (Gross Domestic Product) is the monetary value of all final goods and services produced within a country\'s borders in a year. It is the primary measure of economic output.' },
      { q: 'If the Federal Reserve raises interest rates, what is the MOST likely effect on inflation?', opts: ['Inflation increases', 'Inflation decreases', 'Inflation is unaffected', 'Inflation becomes negative'], ans: 1, exp: 'Higher interest rates make borrowing more expensive, reducing spending and investment. Lower demand puts downward pressure on prices, decreasing inflation. This is contractionary monetary policy.' },
      { q: 'Which of the following is an example of expansionary fiscal policy?', opts: ['Raising income taxes', 'Reducing government spending on infrastructure', 'Cutting taxes and increasing government spending', 'Raising the federal funds rate'], ans: 2, exp: 'Expansionary fiscal policy stimulates the economy by increasing aggregate demand. Cutting taxes puts more money in consumers\' hands; increasing spending directly adds to AD. Note: raising the federal funds rate is monetary policy, not fiscal policy.' },
      { q: 'What happens to a country\'s currency when its interest rates rise relative to other countries?', opts: ['The currency depreciates', 'The currency appreciates', 'The currency stays unchanged', 'The currency is devalued'], ans: 1, exp: 'Higher interest rates attract foreign capital (investors want higher returns). Higher demand for the currency increases its value — appreciation. This is a key international finance concept.' },
    ],
  },
  {
    id: 'biz-consumer',
    name: 'Consumer Behavior & Market Research',
    grade: 11, term: 'Spring', credits: 0.5,
    description: 'Why do people buy what they buy? This course dives into the psychology of consumer decision-making — perception, motivation, attitudes, social influence — and teaches you to use research methods to generate actionable insights for marketing strategy.',
    syllabus: {
      objectives: [
        'Explain the stages of the consumer decision-making process',
        'Describe how psychological and social factors influence buying decisions',
        'Design and conduct a market research study using primary methods',
        'Analyze and present data from consumer surveys',
        'Write a research-backed marketing recommendation report',
      ],
      units: [
        { week: '1–2',   topic: 'Consumer Decision Process', desc: 'Problem recognition, information search, evaluation, purchase, post-purchase behavior.' },
        { week: '3–4',   topic: 'Psychological Influences',  desc: 'Motivation, perception, learning, memory, attitudes — how the mind drives buying.' },
        { week: '5–6',   topic: 'Social & Cultural Influences', desc: 'Family, reference groups, culture, social class, opinion leaders.' },
        { week: '7–8',   topic: 'Research Design',           desc: 'Research questions, hypotheses, qualitative vs. quantitative methods, sampling.' },
        { week: '9–10',  topic: 'Data Collection',           desc: 'Survey design, interview techniques, focus groups, observational research.' },
        { week: '11–12', topic: 'Data Analysis',             desc: 'Tabulating results, finding patterns, charts and graphs, key insights.' },
        { week: '13',    topic: 'Behavioral Economics',      desc: 'Anchoring, loss aversion, nudges, default effects — how irrationality affects buying.' },
        { week: '14–16', topic: 'Research Report',           desc: 'Conduct original research, analyze findings, write and present recommendations.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=E5hCWf9HM5E', title: 'Consumer Behavior — Crash Course', channel: 'Crash Course Marketing', note: 'Short and clear overview of how consumer psychology works — watch in Week 1–2.' },
      { url: 'https://www.youtube.com/watch?v=u6XAPnuFjJc', title: 'Behavioral Economics — Dan Ariely', channel: 'TED', note: 'Dan Ariely\'s famous TED Talk on how irrational we really are as consumers. Watch for Week 13.' },
      { url: 'https://www.youtube.com/watch?v=VVDmCa67-YM', title: 'How to Design a Survey', channel: 'Qualtrics', note: 'Practical guide to creating effective surveys — use for Week 9–10.' },
      { url: 'https://www.youtube.com/watch?v=M3agHMoJur4', title: 'Focus Group Research — How It Works', channel: 'MRGA Research', note: 'Overview of qualitative research methods for market research.' },
    ],
    quiz: [
      { q: 'What is the FIRST stage of the consumer decision-making process?', opts: ['Information Search', 'Purchase Decision', 'Problem Recognition', 'Post-Purchase Evaluation'], ans: 2, exp: 'Problem Recognition occurs when a consumer realizes a gap between their current state and desired state. Without recognizing a need, a consumer won\'t seek solutions.' },
      { q: 'Which behavioral economics concept describes the tendency to rely too heavily on the first piece of information seen?', opts: ['Loss aversion', 'Anchoring', 'Framing effect', 'Status quo bias'], ans: 1, exp: 'Anchoring is the cognitive bias where people rely heavily on an initial piece of information (the "anchor") when making decisions. Retailers use this by showing original price before discount.' },
      { q: 'In market research, what is the difference between qualitative and quantitative data?', opts: ['Qualitative is more accurate', 'Quantitative is collected in-person; qualitative is online', 'Qualitative explores why and how through words and observations; quantitative measures with numbers', 'Quantitative uses surveys; qualitative uses experiments'], ans: 2, exp: 'Qualitative research (interviews, focus groups) explores motivations and meanings. Quantitative research (surveys, sales data) measures and counts. Both are valuable; the best research uses both.' },
    ],
  },
  {
    id: 'biz-strategy',
    name: 'Business Strategy',
    grade: 12, term: 'Fall', credits: 1.0,
    description: 'How do companies win — and why do they fail? Business Strategy examines competitive advantage, industry analysis, corporate strategy, and global business. Through case studies of companies like Amazon, Tesla, and LVMH, you will learn to think like a CEO and apply frameworks used by management consultants.',
    syllabus: {
      objectives: [
        'Apply Porter\'s Five Forces to analyze industry attractiveness',
        'Use the SWOT framework to evaluate a company\'s strategic position',
        'Explain different sources of competitive advantage and how companies sustain them',
        'Analyze growth strategies (organic, acquisition, partnerships)',
        'Write a strategic recommendation for a real company based on research',
      ],
      units: [
        { week: '1–2',   topic: 'What is Strategy?',         desc: 'Strategy vs. tactics, mission/vision, strategic goals, why most strategies fail.' },
        { week: '3–4',   topic: 'Industry Analysis',         desc: 'Porter\'s Five Forces, industry lifecycle, identifying attractive vs. unattractive industries.' },
        { week: '5–6',   topic: 'Competitive Advantage',     desc: 'Cost leadership, differentiation, niche strategies — how companies build moats.' },
        { week: '7–8',   topic: 'SWOT & Strategic Planning', desc: 'Internal strengths/weaknesses, external opportunities/threats, SWOT analysis in practice.' },
        { week: '9–10',  topic: 'Growth Strategies',         desc: 'Organic growth, M&A, joint ventures, franchising, international expansion.' },
        { week: '11–12', topic: 'Corporate Strategy',        desc: 'Diversification, portfolio management (BCG matrix), vertical integration.' },
        { week: '13',    topic: 'Strategic Failure',         desc: 'Case studies: Kodak, Blockbuster, Nokia — what went wrong and why.' },
        { week: '14–16', topic: 'Strategic Consulting Project', desc: 'Choose a real company. Analyze its strategy. Present a research-backed recommendation.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=mYF2_FBCvXw', title: 'Porter\'s Five Forces Explained', channel: 'Harvard Business Review', note: 'Michael Porter himself explaining his framework. Watch in Week 3.' },
      { url: 'https://www.youtube.com/watch?v=CCnBLNrUrQA', title: 'Strategy — Harvard Business School Case Studies', channel: 'HBS Online', note: 'HBS case study method intro — the same way top MBA programs teach strategy.' },
      { url: 'https://www.youtube.com/watch?v=cH-Dh-rWi9E', title: 'How Amazon Became the World\'s Most Valuable Company', channel: 'CNBC', note: 'Excellent strategy case study — apply Five Forces and competitive advantage frameworks.' },
      { url: 'https://www.youtube.com/watch?v=ZnuL6dJ4qAU', title: 'BCG Matrix Explained', channel: 'Business Basics', note: 'Understand the portfolio analysis tool used in Week 11–12.' },
    ],
    quiz: [
      { q: 'Porter\'s Five Forces does NOT include which of the following?', opts: ['Threat of new entrants', 'Bargaining power of suppliers', 'Company brand recognition', 'Threat of substitute products'], ans: 2, exp: 'Porter\'s Five Forces are: (1) Competitive rivalry, (2) Threat of new entrants, (3) Bargaining power of suppliers, (4) Bargaining power of buyers, (5) Threat of substitutes. Brand recognition is a factor within the framework, not one of the five forces itself.' },
      { q: 'A company that competes by offering the lowest price in the market is using which generic strategy?', opts: ['Differentiation', 'Focus', 'Cost Leadership', 'Market Penetration'], ans: 2, exp: 'Cost Leadership (Porter) means achieving the lowest cost structure in the industry and competing on price. Examples: Walmart, Ryanair, Amazon\'s private-label products.' },
      { q: 'In a SWOT analysis, which quadrant contains factors that are internal to the company AND negative?', opts: ['Strengths', 'Weaknesses', 'Opportunities', 'Threats'], ans: 1, exp: 'Weaknesses are internal negative factors — areas where the company underperforms relative to competitors (e.g., high debt, weak brand, outdated technology). Threats are external negative factors.' },
      { q: 'Kodak\'s failure is most often cited as an example of:', opts: ['Cost leadership failure', 'Poor quality products', 'Failing to adapt to disruptive innovation (digital photography)', 'Government regulation'], ans: 2, exp: 'Kodak actually invented the digital camera in 1975 but failed to pursue it, fearing cannibalization of its film business. This is the classic innovator\'s dilemma — disruption from within a technology a company invented.' },
    ],
  },
  {
    id: 'biz-capstone',
    name: 'Marketing Capstone: Brand Launch',
    grade: 12, term: 'Spring', credits: 1.0,
    description: 'Your senior capstone is a full brand launch project. Starting from market research, you will develop a product or service concept, build its brand identity, write a marketing plan, create sample creative assets, and present a launch strategy to a panel. This is your portfolio centerpiece.',
    syllabus: {
      objectives: [
        'Conduct original market research to validate a product or service concept',
        'Develop a complete brand identity: name, positioning, visual identity, voice',
        'Write a full marketing plan with strategy, tactics, budget, and KPIs',
        'Create sample creative assets (social content, landing page copy, ad concepts)',
        'Present the brand launch to a panel with professional confidence',
      ],
      units: [
        { week: '1–2',   topic: 'Concept Development',       desc: 'Brainstorm product/service ideas. Evaluate feasibility. Choose and define your concept.' },
        { week: '3–4',   topic: 'Market Research',           desc: 'Conduct interviews, surveys, and secondary research. Validate the need.' },
        { week: '5–6',   topic: 'Brand Strategy',            desc: 'Define target audience, positioning statement, brand personality, competitive set.' },
        { week: '7–8',   topic: 'Brand Identity',            desc: 'Name, logo concept, color palette, typography, brand voice and tone.' },
        { week: '9–10',  topic: 'Marketing Plan',            desc: 'Objectives, strategy, channel mix, content plan, paid media, budget, timeline.' },
        { week: '11–12', topic: 'Creative Execution',        desc: 'Create sample social posts, ad copy, landing page draft, email template.' },
        { week: '13–14', topic: 'Plan Refinement',           desc: 'Peer feedback, instructor review, revisions, finalize all materials.' },
        { week: '15–16', topic: 'Brand Launch Presentation', desc: 'Present full brand and marketing plan to panel. Professional Q&A.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=kqEQ4SNSMXE', title: 'How to Write a Marketing Plan', channel: 'HubSpot', note: 'Step-by-step guide to creating a professional marketing plan — use for Week 9–10.' },
      { url: 'https://www.youtube.com/watch?v=ZJJFFkqUNJE', title: 'Brand Strategy From Scratch', channel: 'The Futur', note: 'Chris Do\'s brand strategy process. Essential for Weeks 5–8.' },
      { url: 'https://www.canva.com/learn/brand-guidelines/', title: 'Brand Guidelines — Canva Learn', channel: 'Canva', note: 'How to create brand identity guidelines. Use Canva to design your brand materials.' },
      { url: 'https://www.youtube.com/watch?v=lx6J7Zn1H_s', title: 'Market Research for Startups', channel: 'Stanford GSB', note: 'Stanford\'s practical market research framework — use for Weeks 3–4.' },
    ],
    quiz: [
      { q: 'A positioning statement describes:', opts: ['The technical specifications of a product', 'Who your target customer is, what benefit you offer, and why you\'re different from competitors', 'The price point of your product', 'Your social media strategy'], ans: 1, exp: 'A positioning statement defines: (1) target customer, (2) the frame of reference (market category), (3) the benefit offered, and (4) the reason to believe. Example: "For busy professionals who need healthy food fast, [Brand] is the meal-kit service that delivers gourmet recipes in 15 minutes, because..."' },
      { q: 'What is a KPI in a marketing plan?', opts: ['Key Product Inventory', 'Key Performance Indicator — a measurable value that shows how effectively objectives are being achieved', 'Knowledge and Process Index', 'Key Pricing Information'], ans: 1, exp: 'KPIs (Key Performance Indicators) are specific, measurable metrics tied to your marketing objectives. Examples: website traffic (goal: 10,000 visits/month), conversion rate (goal: 3%), cost per acquisition (goal: under $25).' },
      { q: 'Why is defining a specific target audience important BEFORE creating marketing assets?', opts: ['It is required by law', 'Every creative decision (tone, visuals, channel, message) should be driven by who you\'re trying to reach', 'It makes the budget smaller', 'It reduces the number of ads you need to create'], ans: 1, exp: 'Without a defined audience, you\'re speaking to everyone — which usually means connecting with no one. The target audience should inform every creative decision: what platform they use, what language resonates, what imagery appeals to them.' },
    ],
  },
];

export default function BusinessPathway() {
  return <PathwayPage meta={META} schedule={SCHEDULE} courses={COURSES} />;
}
