import React from 'react';
import { PathwayPage } from './PathwayComponents';

const COLOR = '#E65100'; // deep orange

const META = {
  color: COLOR,
  title: 'Communications & Media',
  subtitle: 'Tell stories that move people. Shape the conversation.',
  emoji: '📡',
  courseEmoji: '📡',
  heroDescription: 'A 4-year pathway for students interested in journalism, public relations, digital media, film production, or strategic communications. From writing and rhetoric through media theory and digital storytelling, you will graduate with a professional media portfolio and the communication skills that top programs at Northwestern, USC Annenberg, and NYU look for.',
  targets: ['Journalism & Mass Communication', 'Public Relations & Strategic Communication', 'Digital Media & Content Creation', 'Film & Television Production', 'Advertising & Marketing Communication', 'Media Studies & Communication Theory'],
  collegeNote: 'Communication programs are highly competitive and look for students who have both theoretical grounding and practical media creation experience. Strong writing samples, a media portfolio, and evidence of analytical thinking about media and society are what distinguish top applicants. This pathway builds all three.',
  stats: [{ label: 'AP Courses', value: 1 }],
};

const SCHEDULE = [
  { grade: 9, term: 'Fall', courses: [
    { name: 'English I',                        type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra I',                        type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology',                          type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'World History',                    type: 'core',       credits: 0.5, dept: 'Social Studies' },
    { name: 'Physical Education',               type: 'core',       credits: 0.5, dept: 'Health & PE' },
    { name: 'Introduction to Media & Communication', type: 'pathway', credits: 0.5, courseId: 'comm-intro' },
  ]},
  { grade: 9, term: 'Spring', courses: [
    { name: 'English I — Writing',              type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Geometry',                         type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Environmental Science',            type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'Geography',                        type: 'core',       credits: 0.5, dept: 'Social Studies' },
    { name: 'Health & Wellness',                type: 'core',       credits: 0.5, dept: 'Health & PE' },
    { name: 'Writing for Media: News & Feature', type: 'pathway',  credits: 0.5, courseId: 'comm-writing' },
  ]},
  { grade: 10, term: 'Fall', courses: [
    { name: 'English II',                       type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra II',                       type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Chemistry',                        type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'U.S. History',                    type: 'core',       credits: 0.5, dept: 'Social Studies' },
    { name: 'Rhetoric & Persuasion',            type: 'pathway',   credits: 0.5, courseId: 'comm-rhetoric' },
    { name: 'Public Speaking',                  type: 'supporting', credits: 0.5, dept: 'Communication' },
  ]},
  { grade: 10, term: 'Spring', courses: [
    { name: 'English II — Literature',          type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Pre-Calculus',                     type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics Fundamentals',             type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'World Politics',                   type: 'core',       credits: 0.5, dept: 'Social Studies' },
    { name: 'Digital Storytelling & Visual Media', type: 'pathway', credits: 0.5, courseId: 'comm-digital' },
  ]},
  { grade: 11, term: 'Fall', courses: [
    { name: 'English III',                      type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Statistics',                       type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology — Advanced',               type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'AP English Language & Composition', type: 'pathway',  credits: 1.0, courseId: 'comm-aplang' },
    { name: 'Business Research Methods',        type: 'supporting', credits: 0.5, dept: 'Social Studies', note: 'Recommended' },
  ]},
  { grade: 11, term: 'Spring', courses: [
    { name: 'English III — Literature',         type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Trigonometry',                     type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics — Mechanics',              type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'Media Theory & Society',           type: 'pathway',   credits: 0.5, courseId: 'comm-theory' },
  ]},
  { grade: 12, term: 'Fall', courses: [
    { name: 'English IV — Writing & Communication', type: 'core',  credits: 1.0, dept: 'English Language Arts' },
    { name: 'Calculus',                         type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Public Relations & Strategic Communication', type: 'pathway', credits: 0.5, courseId: 'comm-pr' },
  ]},
  { grade: 12, term: 'Spring', courses: [
    { name: 'English IV — Advanced Composition', type: 'core',     credits: 1.0, dept: 'English Language Arts' },
    { name: 'Communications Capstone: Original Media Project', type: 'pathway', credits: 1.0, courseId: 'comm-capstone' },
  ]},
];

const COURSES = [
  {
    id: 'comm-intro',
    name: 'Introduction to Media & Communication',
    grade: 9, term: 'Fall', credits: 0.5,
    description: 'A survey of the media landscape — from print and broadcast to social platforms and podcasts. Students explore how different media forms shape the way information travels, who controls it, and how audiences receive and interpret messages. This course establishes the media literacy foundation the entire pathway builds on.',
    syllabus: {
      objectives: [
        'Identify and distinguish major mass media forms and their historical development',
        'Explain how media ownership and economics influence editorial decisions',
        'Apply basic media literacy frameworks to evaluate credibility and bias in news sources',
        'Describe the communication process using models such as Shannon-Weaver and the transactional model',
        'Produce a short original media piece (blog post, photo essay, or podcast segment) demonstrating awareness of audience and purpose',
      ],
      units: [
        { week: '1–2',   topic: 'What Is Communication?',         desc: 'Linear, interactive, and transactional models of communication. Shannon-Weaver signal/noise model. Intrapersonal vs. mass communication — where media fits on the spectrum.' },
        { week: '3–4',   topic: 'History of Mass Media',          desc: 'Gutenberg press through radio, television, and the internet. How each new medium disrupted existing information structures and power relationships.' },
        { week: '5–6',   topic: 'Media Ownership & Economics',    desc: 'Consolidation of media conglomerates (Disney, Comcast, News Corp). Subscription, advertising, and platform business models. How revenue sources shape editorial choices.' },
        { week: '7–8',   topic: 'Media Literacy Fundamentals',    desc: 'The five core media literacy questions (Center for Media Literacy framework). Identifying bias, evaluating source credibility, fact-checking with tools like Snopes, PolitiFact, and AllSides.' },
        { week: '9–10',  topic: 'Print & Broadcast Journalism',   desc: 'Structure of a news organization. The inverted pyramid. Roles: reporter, editor, producer. How a story goes from tip to publication in print and on air.' },
        { week: '11–12', topic: 'Digital & Social Media',         desc: 'Algorithmic curation and filter bubbles. Virality mechanics. The attention economy. How social platforms differ from traditional broadcast in reach, speed, and accountability.' },
        { week: '13',    topic: 'Advertising & Persuasion Basics', desc: 'How advertising funds media. Persuasion techniques: bandwagon, fear appeal, celebrity endorsement, scarcity. Regulation of advertising — FTC guidelines and truth-in-advertising rules.' },
        { week: '14–16', topic: 'Media Literacy Portfolio Project', desc: 'Students choose a current news topic, trace how it is covered across five different media outlets (print, TV, social, podcast, international), and produce an annotated analysis plus one original piece responding to that coverage.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtM6jSpzb5gMgdHYwCayBcOd', title: 'Crash Course Media Literacy', channel: 'Crash Course', note: 'All 12 episodes cover media literacy, news consumption, and how to think critically about information. Watch alongside every unit.' },
      { url: 'https://www.youtube.com/watch?v=lDsG8dMFBkA', title: 'The Attention Economy and How It Shapes Media', channel: 'TED-Ed', note: 'Concise, animated explanation of how platforms monetize attention — essential for the digital media unit.' },
      { url: 'https://newslit.org/educators/resources/', title: 'News Literacy Project — Checkology', channel: 'News Literacy Project', note: 'Free, interactive platform for practicing source verification, bias identification, and misinformation detection.' },
      { url: 'https://www.youtube.com/c/LikeStoriesofOld', title: 'Like Stories of Old — Media & Storytelling Essays', channel: 'Like Stories of Old', note: 'Long-form video essays that model sophisticated analysis of how stories and media shape culture. Excellent for developing analytical writing voice.' },
    ],
    quiz: [
      { q: 'In the Shannon-Weaver communication model, what does "noise" refer to?', opts: ['Loud background sounds during a phone call', 'Any interference that distorts or disrupts the message between sender and receiver', 'The emotional tone of a message', 'The number of people in the audience'], ans: 1, exp: '"Noise" in Shannon-Weaver is any interference — physical (static), semantic (misunderstood words), or psychological (preconceptions) — that prevents the received message from matching the sent message.' },
      { q: 'Which of the following best describes a "filter bubble"?', opts: ['A legal mechanism that keeps harmful content off social platforms', 'A personalized algorithmic environment in which a user sees only content that reinforces existing beliefs', 'A journalistic practice of verifying information before publishing', 'A type of advertising targeting based on demographics'], ans: 1, exp: 'Filter bubbles, a term coined by Eli Pariser, describe how recommendation algorithms show users content similar to what they already engaged with, limiting exposure to different perspectives and reinforcing existing views.' },
      { q: 'What is the "inverted pyramid" structure in journalism?', opts: ['A story format that builds suspense by saving the most important fact for the end', 'A news writing format that presents the most newsworthy information first, followed by supporting details', 'A way of organizing a media organization\'s hierarchy', 'A method for ranking news stories by importance on a front page'], ans: 1, exp: 'The inverted pyramid places the most critical information — who, what, when, where, why, how — at the top of a news story. This allows readers to get the key facts quickly and editors to cut from the bottom without losing essential content.' },
      { q: 'Which of the following best describes vertical integration in media ownership?', opts: ['When a company owns multiple outlets in the same market', 'When a single company controls production, distribution, and exhibition of media content', 'When international media companies merge across borders', 'When a media outlet partners with a government agency'], ans: 1, exp: 'Vertical integration means owning multiple stages of the supply chain. In media, a studio that produces films, distributes them, and owns theaters is vertically integrated — examples include Disney owning studios, streaming platforms, and theme parks.' },
      { q: 'What does the Center for Media Literacy\'s framework ask audiences to do when encountering any media message?', opts: ['Immediately share it if they agree with it', 'Consider who created it, why, what values it represents, and how it might affect different audiences', 'Compare it only to government-approved sources', 'Focus solely on whether the statistics cited are accurate'], ans: 1, exp: 'CML\'s five key questions ask: Who created the message? What techniques are used to attract attention? What values or lifestyles are represented? How might different people interpret it? What is omitted? This framework applies to all media — news, advertising, entertainment, and social content.' },
    ],
  },
  {
    id: 'comm-writing',
    name: 'Writing for Media: News & Feature',
    grade: 9, term: 'Spring', credits: 0.5,
    description: 'The craft of writing for a public audience. Students learn the technical and stylistic conventions of journalism — from hard news leads to long-form feature writing — while also grappling with the ethical responsibilities that come with publishing information. Every student leaves with a portfolio of published-quality written work.',
    syllabus: {
      objectives: [
        'Write clean, accurate news stories using the inverted pyramid structure and AP style',
        'Develop and execute an original feature story with sources, narrative, and scene',
        'Conduct and transcribe interviews, selecting quotes that advance the story',
        'Identify and apply core journalistic ethics principles including accuracy, independence, and minimizing harm',
        'Edit and revise drafts through multiple rounds using peer and instructor feedback',
      ],
      units: [
        { week: '1–2',   topic: 'Grammar & Style for Journalists', desc: 'AP Stylebook conventions — dates, titles, numbers, abbreviations. Subject-verb agreement, active voice, sentence variety. Why clarity and brevity are the journalist\'s primary virtues.' },
        { week: '3–4',   topic: 'The News Story',                   desc: 'The five Ws and H. Crafting a hard news lead. Inverted pyramid structure. Attribution — how and when to cite sources. Writing on deadline.' },
        { week: '5–6',   topic: 'Interviewing & Sources',           desc: 'Preparing interview questions. Conducting interviews respectfully and strategically. On vs. off the record. Selecting and integrating quotes — when to paraphrase, when to quote directly.' },
        { week: '7–8',   topic: 'Feature Writing',                  desc: 'Differences between hard news and features. Narrative techniques: anecdotal lead, scene-setting, character development, nut graf. Finding and pitching feature story ideas.' },
        { week: '9–10',  topic: 'Opinion & Editorial Writing',      desc: 'Argument structure in columns and editorials. The role of opinion in journalism. Separating news from commentary. Writing a structured 600-word op-ed with a clear claim and three supporting reasons.' },
        { week: '11–12', topic: 'Journalistic Ethics',              desc: 'The SPJ Code of Ethics: seek truth, minimize harm, act independently, be accountable. Case studies: when is a story worth publishing despite privacy costs? Covering vulnerable communities. Avoiding conflicts of interest.' },
        { week: '13',    topic: 'Digital Writing & SEO',            desc: 'How web publishing differs from print. Headlines for clicks vs. clarity. Writing for skimming readers. Embedding hyperlinks and multimedia. Basic SEO — why it matters for reach.' },
        { week: '14–16', topic: 'Portfolio Publication',            desc: 'Each student researches and writes a 900–1,200-word feature story on a topic of genuine importance to them. Multiple rounds of editing. Final pieces assembled into a class publication.' },
      ],
    },
    resources: [
      { url: 'https://www.poynter.org/newsu/', title: 'Poynter NewsU — Journalism Training', channel: 'Poynter Institute', note: 'Free online courses covering news writing, fact-checking, digital journalism, and ethics. Complete the "Grammar and Spelling" and "Writing with Clarity" modules.' },
      { url: 'https://www.youtube.com/watch?v=aulP9Rvj8dg', title: 'How to Write a News Article — Step by Step', channel: 'JMC Study Tools', note: 'Practical walkthrough of news article structure from lead to kicker. Watch before starting Unit 2 assignments.' },
      { url: 'https://www.youtube.com/watch?v=T_q71TL6NEg', title: 'AP Style — The Basics Every Journalist Needs', channel: 'Journalism School Resources', note: 'Overview of the most commonly tested AP Style rules. Reference throughout the semester.' },
      { url: 'https://www.spj.org/ethicscode.asp', title: 'SPJ Code of Ethics — Full Text', channel: 'Society of Professional Journalists', note: 'The foundational ethics document for American journalism. Read and annotate as the primary text for Unit 6.' },
    ],
    quiz: [
      { q: 'In journalism, what is a "nut graf"?', opts: ['The first sentence of a news story, also called the lead', 'A paragraph that explains why the story matters and what readers will learn from it', 'A quote from the primary source in a story', 'The final paragraph that wraps up the story'], ans: 1, exp: 'The nut graf (nut paragraph) typically appears after an anecdotal opening and explains the broader significance of the story — "this is why you should care." It gives the reader context and previews the key themes.' },
      { q: 'According to the SPJ Code of Ethics, which of the following is a core principle of journalism?', opts: ['Represent the interests of media owners and advertisers', 'Seek truth and report it as fully as possible', 'Avoid covering stories that might upset the audience', 'Always remain anonymous to protect objectivity'], ans: 1, exp: 'The SPJ Code of Ethics has four principles: Seek Truth and Report It, Minimize Harm, Act Independently, and Be Accountable and Transparent. Serving truth — not owners, advertisers, or audience preferences — is foundational.' },
      { q: 'When a source speaks "on background," what does this mean for the journalist?', opts: ['The journalist can quote the source directly with their name', 'The journalist can use the information but may not attribute it to the named source', 'The journalist must not use the information at all', 'The journalist must get a second source before using any information'], ans: 1, exp: '"On background" means the journalist can use the information but cannot attribute it to the named source — they may attribute it to a general description ("a senior official"). This protects sources who would face retaliation for speaking publicly.' },
      { q: 'Why does journalism traditionally favor active voice over passive voice?', opts: ['Active voice is required by the AP Stylebook in all cases', 'Active voice makes clear who is doing what, creating stronger and more transparent sentences', 'Passive voice is grammatically incorrect in news writing', 'Active voice takes fewer words and therefore saves space in print'], ans: 1, exp: 'Active voice ("The mayor rejected the proposal") is clearer and more direct than passive ("The proposal was rejected"). It keeps the actor visible, which is essential in journalism — readers should know who is responsible for actions.' },
    ],
  },
  {
    id: 'comm-rhetoric',
    name: 'Rhetoric & Persuasion',
    grade: 10, term: 'Fall', credits: 0.5,
    description: 'The art of effective communication, traced from Aristotle\'s Greece to contemporary political speeches and viral advertising campaigns. Students study the classical rhetorical tradition — ethos, pathos, logos — and apply these frameworks to analyze and produce persuasive texts across multiple modes. This course is essential preparation for AP English Language & Composition.',
    syllabus: {
      objectives: [
        'Identify and explain Aristotle\'s three appeals — ethos, pathos, and logos — in real-world texts',
        'Analyze how rhetorical situation (speaker, audience, purpose, context, constraints) shapes communication choices',
        'Recognize and deploy common rhetorical devices including anaphora, antithesis, chiasmus, and appeals to kairos',
        'Write a structured rhetorical analysis essay evaluating how an author builds an argument',
        'Deliver a persuasive speech or presentation using deliberate rhetorical strategies',
      ],
      units: [
        { week: '1–2',   topic: 'The Rhetorical Tradition',        desc: 'Aristotle\'s Rhetoric and its three-part framework. Cicero\'s five canons of rhetoric (invention, arrangement, style, memory, delivery). Why the Greeks believed rhetoric was essential to democratic citizenship.' },
        { week: '3–4',   topic: 'Ethos, Pathos, Logos',           desc: 'Deep dive into each appeal with contemporary examples. How political speeches use all three simultaneously. Analyzing Barack Obama\'s 2004 DNC speech and Martin Luther King Jr.\'s "Letter from Birmingham Jail" as models.' },
        { week: '5–6',   topic: 'Rhetorical Situation',            desc: 'The SPACE framework (Speaker, Purpose, Audience, Context, Exigence). How the same message works differently for different audiences. Analyzing how tone, diction, and framing shift across audiences.' },
        { week: '7–8',   topic: 'Rhetorical Devices',              desc: 'Anaphora, epistrophe, antithesis, chiasmus, alliteration, hypophora, rhetorical questions, parallelism. Students identify these in speeches, essays, and advertising copy, then deliberately use them in their own writing.' },
        { week: '9–10',  topic: 'Propaganda & Manipulation',       desc: 'The difference between legitimate persuasion and manipulation. Propaganda techniques: glittering generalities, transfer, card stacking, plain folks, bandwagon. Case studies in wartime propaganda and modern political advertising.' },
        { week: '11–12', topic: 'Rhetorical Analysis Essay',       desc: 'How to write an AP-style rhetorical analysis: identify the claim, map the appeals, analyze specific devices, explain how choices work together to achieve the author\'s purpose. Practice with multiple short texts before the major essay.' },
        { week: '13',    topic: 'Kairos & Timing',                 desc: 'Kairos as the concept of opportune moment. How skilled communicators read the cultural moment and time their messages. Case studies: Churchill\'s wartime speeches, Greta Thunberg\'s 2019 UN address.' },
        { week: '14–16', topic: 'Persuasive Speech Project',       desc: 'Students select a genuine issue of public concern, research it deeply, draft a 5-minute persuasive speech using deliberate rhetorical strategies, and deliver it. Peer analysis session after each speech identifies which strategies were most effective.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=3klMM9BkW5o', title: 'Rhetoric: How to Use Ethos, Pathos, and Logos', channel: 'TED-Ed', note: 'Clear, animated introduction to the three appeals with contemporary examples. Assign for Unit 1 viewing.' },
      { url: 'https://www.youtube.com/watch?v=8rSMPVGBBP0', title: 'Rhetorical Analysis — AP English Language', channel: 'Khan Academy', note: 'Walks through how to write AP-style rhetorical analysis essays step by step. Essential for Unit 6.' },
      { url: 'https://www.youtube.com/watch?v=i3MLCHpAMeA', title: 'Logical Fallacies — Crash Course Philosophy', channel: 'Crash Course', note: 'Covers the most common errors in reasoning — essential for distinguishing legitimate logos from manipulation in Unit 5.' },
      { url: 'https://americanrhetoric.com/top100speechesall.html', title: 'American Rhetoric — Top 100 Speeches', channel: 'American Rhetoric', note: 'Transcripts, audio, and video of landmark American speeches. Primary source material for every unit of this course.' },
    ],
    quiz: [
      { q: 'A politician opens a speech by describing her upbringing in a working-class family to establish a connection with her audience. Which rhetorical appeal is primarily at work?', opts: ['Logos', 'Ethos', 'Pathos', 'Kairos'], ans: 1, exp: 'Ethos is the appeal to credibility and character. By sharing her personal background, the politician builds trust and relatability with her audience — establishing that she understands their lives. This is a form of ethos through shared identity.' },
      { q: 'What is the rhetorical device in this sentence: "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets"?', opts: ['Antithesis', 'Chiasmus', 'Anaphora', 'Hypophora'], ans: 2, exp: 'Anaphora is the deliberate repetition of a word or phrase at the beginning of successive clauses. Churchill\'s repetition of "we shall fight" creates a drumbeat effect that builds emotional momentum and signals unwavering resolve.' },
      { q: 'In the concept of rhetorical situation, what does "exigence" refer to?', opts: ['The speaker\'s level of expertise on the topic', 'The urgent problem or issue that makes a particular communication necessary', 'The audience\'s emotional state before the speech', 'The constraints imposed by the communication medium'], ans: 1, exp: 'Exigence (from the Latin for "demand") is the specific situation, event, or problem that calls forth the rhetoric — the reason the communication is necessary right now. Lloyd Bitzer\'s rhetorical situation framework defines exigence as an imperfection marked by urgency.' },
      { q: 'Which of the following is an example of the "card stacking" propaganda technique?', opts: ['A celebrity endorsing a product without disclosing payment', 'An advertisement that shows only the positive reviews of a product while omitting all negative feedback', 'A politician using emotional language about national pride', 'A public health campaign using statistics about disease rates'], ans: 1, exp: 'Card stacking presents only one side of an argument — selecting facts, quotes, or images that support the desired conclusion while ignoring contradictory evidence. It is deceptive not through lying but through strategic omission.' },
    ],
  },
  {
    id: 'comm-digital',
    name: 'Digital Storytelling & Visual Media',
    grade: 10, term: 'Spring', credits: 0.5,
    description: 'Stories live in images, sound, motion, and interaction — not just words. This course teaches students to communicate powerfully through photography, video, podcast, and data visualization. Students learn the grammar of visual storytelling and produce a multi-platform media project that demonstrates range and intentionality across formats.',
    syllabus: {
      objectives: [
        'Apply principles of visual composition (rule of thirds, leading lines, depth of field) to purposeful photography',
        'Plan and produce a short documentary-style video with scripted narration, B-roll, and sound design',
        'Record and edit a podcast episode using audio editing software (Audacity or GarageBand)',
        'Create an accessible data visualization that communicates a clear argument to a general audience',
        'Analyze how platform context (Instagram, YouTube, Twitter/X, TikTok) shapes storytelling format and audience expectations',
      ],
      units: [
        { week: '1–2',   topic: 'The Grammar of Visual Language',  desc: 'How images communicate meaning independently of text. Semiotics basics: sign, signifier, signified. Reading photographs as arguments. Rule of thirds, leading lines, framing, depth of field — and how each choice encodes meaning.' },
        { week: '3–4',   topic: 'Photography as Journalism',       desc: 'Documentary photography and its ethical responsibilities. The iconic images that changed public opinion (Nick Ut\'s "Napalm Girl," Dorothea Lange\'s "Migrant Mother"). Students produce a 10-image photo essay on a local or personal story.' },
        { week: '5–6',   topic: 'Video Storytelling',              desc: 'Three-act structure adapted for short-form video. Shot types (establishing, medium, close-up, cutaway). B-roll and its role in covering narration. Storyboarding. Students script and shoot a 2-minute explainer video.' },
        { week: '7–8',   topic: 'Podcast & Audio Storytelling',    desc: 'What audio does that text cannot: voice, pacing, ambient sound, music. Structure of the "This American Life" format. Recording, editing, and mixing in Audacity/GarageBand. Students produce a 5-minute audio story.' },
        { week: '9–10',  topic: 'Data Visualization',              desc: 'Charts, maps, infographics, and interactive graphics as journalism. When to use which chart type. Color and hierarchy as communicative tools. Using Canva, Flourish, or Datawrapper to create publication-quality visualizations.' },
        { week: '11–12', topic: 'Platform & Audience',             desc: 'How TikTok, YouTube, Instagram, podcasts, and newsletters create different storytelling demands. Algorithmic logic and how to work with and against it. Audience engagement and community building. Students adapt one story across three platforms.' },
        { week: '13',    topic: 'Ethics of Visual Media',          desc: 'Photo manipulation and the line between editing and deception. Deepfakes and synthetic media. Consent in documentary filming. The Reuters Standards for digital image alteration.' },
        { week: '14–16', topic: 'Multi-Platform Media Project',    desc: 'Each student tells a single story across three different formats (e.g., photo essay + podcast + data visualization). Final presentation explains storytelling choices for each platform and what each format uniquely contributed to the narrative.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=LMQqNFnAFoY', title: 'Documentary Filmmaking — A Crash Course', channel: 'StudioBinder', note: 'Covers the key phases of documentary production: development, pre-production, production, and post. Watch for the video unit.' },
      { url: 'https://www.youtube.com/watch?v=FihCkqON21s', title: 'How to Make a Podcast — Full Beginner Guide', channel: 'Thomas Frank', note: 'Step-by-step guide to recording, editing, and publishing a podcast. Use as the primary reference for Unit 4.' },
      { url: 'https://www.youtube.com/watch?v=5Aw3kMSMQxQ', title: 'Data Visualization Best Practices', channel: 'Chartio', note: 'Principles of effective data visualization — when to use which chart type and how to avoid misleading graphics.' },
      { url: 'https://www.youtube.com/c/LikeStoriesofOld', title: 'Like Stories of Old — Visual Essay Models', channel: 'Like Stories of Old', note: 'Exceptional model of the video essay format — sophisticated narration paired with visual argument. Analyze the opening of any episode to understand pacing and image-word relationship.' },
    ],
    quiz: [
      { q: 'In visual composition, what is the "rule of thirds"?', opts: ['A guideline that says every photo should have exactly three subjects', 'A principle that places the subject at the intersection of lines dividing the frame into thirds, creating visual tension and interest', 'A rule that the horizon should always appear in the top third of a photo', 'A technique requiring three different light sources for professional photography'], ans: 1, exp: 'The rule of thirds divides the frame into a 3×3 grid. Placing subjects at the intersections of these lines — rather than dead center — creates more dynamic, visually interesting compositions. It is a guide, not an absolute rule, but violating it intentionally requires understanding it first.' },
      { q: 'In documentary filmmaking, what is "B-roll"?', opts: ['The second draft of a film script', 'Secondary footage that illustrates or supplements the main interview or narration', 'The backup copy of the original footage', 'Close-up shots of faces during interviews'], ans: 1, exp: 'B-roll is supplementary footage — visuals of the subject being discussed, locations, hands, objects — cut over narration or interview audio ("A-roll"). B-roll makes stories visual rather than just verbal and is essential for covering jump cuts.' },
      { q: 'What does "semiotics" study in the context of media and communication?', opts: ['The technical specifications of digital media formats', 'The system of signs and symbols and how they produce meaning', 'The history of language development across cultures', 'The business models of media companies'], ans: 1, exp: 'Semiotics, developed by Ferdinand de Saussure and Charles Sanders Peirce, studies how signs create meaning. In media, everything — colors, camera angles, music, typography, word choice — functions as a sign that encodes meaning for an audience.' },
      { q: 'Why might a journalist choose a close-up shot over an establishing shot when covering a protest?', opts: ['Close-ups are technically easier to film', 'Close-ups show individual human faces and emotions, creating empathy; establishing shots show scale but reduce individuals to an anonymous crowd', 'Establishing shots are reserved only for entertainment media', 'Close-ups are required by press photography ethics guidelines'], ans: 1, exp: 'Shot selection is an editorial and ethical decision. A close-up of a specific person at a protest humanizes and individualizes; an establishing shot showing crowd scale emphasizes the collective. The choice shapes how viewers emotionally relate to the story — who they see as people versus as a phenomenon.' },
    ],
  },
  {
    id: 'comm-aplang',
    name: 'AP English Language & Composition',
    grade: 11, term: 'Fall', credits: 1.0,
    description: 'College-level composition and rhetorical analysis. The AP Language exam demands three distinct essay types — synthesis, rhetorical analysis, and argument — and this course prepares students to excel at all three. Students read a wide range of nonfiction prose, develop a flexible analytical vocabulary, and write under timed conditions throughout the year.',
    syllabus: {
      objectives: [
        'Write a rhetorical analysis essay that identifies and evaluates an author\'s persuasive strategies with precision and textual specificity',
        'Compose an evidence-based argument essay that develops a nuanced, defensible claim with well-chosen support',
        'Produce a synthesis essay that integrates at least three sources into a coherent original argument',
        'Read and annotate complex nonfiction prose for rhetorical purpose, audience, and stylistic choices',
        'Achieve a score of 3 or higher on the AP English Language & Composition exam',
      ],
      units: [
        { week: '1–3',   topic: 'Reading Rhetorically',            desc: 'Annotating nonfiction for purpose, audience, and tone. SOAPS(T) analysis (Subject, Occasion, Audience, Purpose, Speaker, Tone). Close reading of Thoreau, Baldwin, Didion, and Orwell to build a model for analytical thinking.' },
        { week: '4–5',   topic: 'Rhetorical Analysis Essay',       desc: 'AP free-response Question 2 (FRQ2). Structuring analysis around the author\'s choices and their intended effects. Moving from identification ("the author uses anaphora") to analysis ("this repetition creates momentum that mirrors the urgency of the moment"). Timed practice every week.' },
        { week: '6–7',   topic: 'Argument Essay',                  desc: 'AP FRQ3: developing a defensible thesis, selecting effective evidence (anecdotal, statistical, analogical), qualifying claims to avoid overreach. The difference between a claim ("social media harms teens") and a nuanced thesis ("social media\'s harm is concentrated among adolescent girls and mediated by passive versus active use patterns").' },
        { week: '8–9',   topic: 'Synthesis Essay',                 desc: 'AP FRQ1: integrating multiple sources in support of an original claim. Distinguishing between summary and synthesis. How to quote, paraphrase, and attribute without letting sources overrun your own argument. The "they say / I say" structure.' },
        { week: '10–11', topic: 'Style & Voice',                   desc: 'Analyzing and imitating the prose styles of accomplished nonfiction writers. Sentence variety (cumulative, periodic, anaphoric). Diction choices and register. Students write imitations of Baldwin, Didion, and Coates to internalize flexibility.' },
        { week: '12–13', topic: 'Timed Writing & Exam Simulation', desc: 'Full AP-format timed exam simulations: 1 hour of multiple choice (45 questions across 5 passages) + 2 hours 15 minutes of three essays. Detailed scoring and feedback using AP rubrics after each simulation.' },
        { week: '14–15', topic: 'AP Multiple Choice Strategies',   desc: 'Close reading under time pressure. Identifying the author\'s purpose in short excerpts. Inference questions about tone and rhetorical effect. Process of elimination strategies. Practice passages from actual released exams.' },
        { week: '16',    topic: 'Final Review & Confidence Building', desc: 'Student-led review of most challenging topics. Focus on essay introductions and thesis quality. Personal feedback sessions on each student\'s weakest essay type. Final timed essay under exam conditions.' },
      ],
    },
    resources: [
      { url: 'https://www.khanacademy.org/humanities/ap-english-language', title: 'AP English Language & Composition — Khan Academy', channel: 'Khan Academy', note: 'Complete AP Lang course covering all three essay types with tutorials, worked examples, and practice questions. Use throughout the year.' },
      { url: 'https://apclassroom.collegeboard.org/', title: 'AP Classroom — Official College Board Resources', channel: 'College Board', note: 'Official AP Daily videos, progress checks, and released exam questions. Use for all timed simulations in Units 12–16.' },
      { url: 'https://www.youtube.com/watch?v=hMSbxTUNQqc', title: 'How to Write a Synthesis Essay — AP Lang', channel: 'Heimler\'s History', note: 'Step-by-step breakdown of the synthesis essay with annotated student examples scored on the AP rubric.' },
      { url: 'https://www.youtube.com/c/AndrewFord-APLang', title: 'AP Lang with Mr. Ford — Full Exam Prep', channel: 'Andrew Ford', note: 'Comprehensive AP Lang video series covering multiple choice strategies and all three essay types. Work through the rhetorical analysis playlist in Units 4–5.' },
    ],
    quiz: [
      { q: 'In AP English Language, what is the primary purpose of the synthesis essay (FRQ1)?', opts: ['To summarize each provided source in your own words', 'To develop your own argument about a topic using at least three of the provided sources as evidence', 'To identify the rhetorical strategies in a single provided document', 'To write a personal narrative about an experience related to the prompt topic'], ans: 1, exp: 'The synthesis essay asks students to formulate their own claim about a topic and support it by integrating evidence from multiple provided sources. The key skill is synthesis — weaving sources into your own argument — rather than summarizing or merely agreeing with sources.' },
      { q: 'What is the key difference between a summary and an analysis in rhetorical analysis writing?', opts: ['A summary is shorter than an analysis', 'A summary describes what the author says; analysis explains how and why specific choices work to achieve the author\'s purpose', 'Analysis requires more sources than summary', 'A summary is used in FRQ1 and analysis in FRQ2'], ans: 1, exp: 'Summary restates content ("the author argues that climate change is urgent"). Analysis examines craft ("the author\'s use of second-person address implicates readers directly in the problem, preventing the emotional distance that statistics alone might produce"). AP graders reward analysis of effect, not identification of techniques.' },
      { q: 'Which of the following is the strongest AP English Language thesis for an argument essay?', opts: ['"Social media has both positive and negative effects on society."', '"In this essay, I will argue that social media is harmful."', '"Social media platforms\' algorithmic design prioritizes engagement over accuracy, making them structurally incapable of self-correcting misinformation without regulatory intervention."', '"Many people think social media is bad, but others think it is good."'], ans: 2, exp: 'A strong AP argument thesis is defensible, specific, and goes beyond the obvious. Option C makes a specific causal claim (algorithmic design) connected to a specific consequence (misinformation) and a specific conclusion (need for external regulation). This is a thesis that requires argument rather than simple agreement.' },
      { q: 'In the SOAPS(T) framework used for rhetorical analysis, what does the "O" stand for?', opts: ['Opinion — the author\'s personal view on the subject', 'Occasion — the time, place, and circumstances that prompted the text', 'Objective — the main factual claim of the text', 'Organization — the structural pattern of the argument'], ans: 1, exp: 'In SOAPS(T), Occasion refers to the context that prompted the communication — the event, moment, or situation the text is responding to. Understanding occasion is essential because the same argument can be appropriate or inappropriate depending on when it is made.' },
      { q: 'What does it mean to "qualify" a claim in an AP argument essay?', opts: ['To remove all hedging language and make the claim as strong as possible', 'To acknowledge the limitations, exceptions, or conditions under which the claim may not hold, making it more defensible', 'To define every key term in the claim with a dictionary definition', 'To add a counterargument paragraph at the end of the essay'], ans: 1, exp: 'Qualifying a claim means acknowledging its boundaries — "social media harms adolescent mental health, particularly for passive users consuming curated content, though active engagement and social connection may have neutral or positive effects." This makes the claim more precise and harder to dismiss, which is what AP scorers reward.' },
    ],
  },
  {
    id: 'comm-theory',
    name: 'Media Theory & Society',
    grade: 11, term: 'Spring', credits: 0.5,
    description: 'The intellectual backbone of communications study. Students engage with the major theoretical frameworks scholars use to analyze how media shapes society, constructs reality, and distributes power. From McLuhan\'s medium theory to Cultivation Theory and Agenda Setting, this course gives students the conceptual vocabulary that distinguishes serious communications scholars from casual observers.',
    syllabus: {
      objectives: [
        'Explain and apply McLuhan\'s medium theory, including "the medium is the message" and the global village concept',
        'Describe Cultivation Theory and explain how prolonged television exposure shapes perceptions of social reality',
        'Apply Agenda Setting Theory to a current news cycle, distinguishing first-level (what to think about) from second-level (how to think about it) agenda setting',
        'Analyze media through the lens of Critical Theory and political economy, examining how ownership structures influence content',
        'Write a theoretical analysis paper applying at least two frameworks to a contemporary media phenomenon',
      ],
      units: [
        { week: '1–2',   topic: 'What Is Media Theory?',           desc: 'Why we need theory to understand media beyond common sense. The positivist vs. critical research traditions. Overview of major theoretical paradigms: effects traditions, cultural studies, political economy, feminist media studies.' },
        { week: '3–4',   topic: 'McLuhan & Medium Theory',         desc: '"The Medium is the Message": why the form of communication matters more than its content. Hot vs. cool media. The global village and its consequences. Applying McLuhan to smartphones and social media — what does the medium itself do to us, regardless of what we post?' },
        { week: '5–6',   topic: 'Agenda Setting Theory',           desc: 'McCombs and Shaw\'s 1972 Chapel Hill study. First-level agenda setting (issue salience) vs. second-level (attribute framing). Priming as a related effect. Case study: how cable news and social media platforms have fragmented the shared agenda.' },
        { week: '7–8',   topic: 'Cultivation Theory',              desc: 'Gerbner\'s Cultural Indicators Project. Heavy television viewers developing a "mean world syndrome" — perceiving the world as more violent than it is. Mainstreaming and resonance effects. Application: how do Netflix binge patterns or TikTok feeds cultivate beliefs?' },
        { week: '9–10',  topic: 'Uses & Gratifications Theory',    desc: 'Shifting from "what media does to people" to "what people do with media." Katz, Blumler, and Gurevitch\'s framework: information, personal identity, integration, entertainment. Active vs. passive audience. Applying the framework to streaming and social media behavior.' },
        { week: '11–12', topic: 'Critical Theory & Political Economy', desc: 'The Frankfurt School: Adorno and Horkheimer\'s culture industry thesis. Manufacturing Consent (Herman and Chomsky): the five filters through which news is shaped — ownership, advertising, sourcing, flak, and ideology. Hegemony and Gramsci\'s concept of cultural leadership.' },
        { week: '13',    topic: 'Feminist Media Studies',          desc: 'Gaze theory and Laura Mulvey\'s male gaze in cinema. Representation and stereotyping. The Bechdel Test as a diagnostic tool. How intersectionality (race, class, gender) shapes representation and reception differently for different audiences.' },
        { week: '14–16', topic: 'Theoretical Analysis Paper',      desc: 'Students select a contemporary media phenomenon — a viral TikTok genre, a news cycle, a streaming series, an influencer category — and analyze it using at least two theoretical frameworks from the course. 1,500 words with academic citations.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=OseOb_wBsi4', title: 'Marshall McLuhan — The Medium is the Message Explained', channel: 'The School of Life', note: 'Clear, engaging explanation of McLuhan\'s core ideas and why they matter for understanding modern media.' },
      { url: 'https://www.youtube.com/watch?v=KD2r-k7AZRY', title: 'Agenda Setting Theory — Communication Explained', channel: 'Communication Coach Alex Lyon', note: 'Accessible explanation of first and second-level agenda setting with current examples. Watch before Unit 3.' },
      { url: 'https://www.youtube.com/watch?v=_tgDt-aGmR4', title: 'Manufacturing Consent — Noam Chomsky Documentary Excerpts', channel: 'Various', note: 'The Propaganda Model explained with historical examples. Foundational for the Critical Theory unit.' },
      { url: 'https://www.youtube.com/c/LikeStoriesofOld', title: 'Like Stories of Old — Media & Cultural Analysis Essays', channel: 'Like Stories of Old', note: 'Model of sophisticated cultural and media criticism in video essay form. Watch "On Self-Improvement" or "Why Society Makes You Feel Empty" as examples of applied media theory.' },
    ],
    quiz: [
      { q: 'McLuhan\'s phrase "the medium is the message" means primarily that:', opts: ['The content of a message is more important than how it is delivered', 'The form or medium of communication itself shapes perception and social behavior independently of any specific content', 'Messages delivered through mainstream media are inherently more credible', 'Media companies should take responsibility for the messages they broadcast'], ans: 1, exp: 'McLuhan argued that the medium shapes cognition and social organization regardless of what content it carries. Television changed society not because of specific programs but because of what it does to perception — passive viewing, emotional immediacy, simultaneous mass experience. The medium restructures human relations.' },
      { q: 'Which of the following is an example of second-level agenda setting?', opts: ['A newspaper running front-page stories about climate change, making it salient to the public', 'Cable news consistently framing immigration as a "crisis" and an "invasion," shaping how audiences conceptualize the issue', 'A social media platform promoting certain topics in its trending section', 'A journalist choosing which sources to interview for a story'], ans: 1, exp: 'First-level agenda setting tells audiences what to think about (salience). Second-level agenda setting shapes how they think about it — which attributes and frames are emphasized. Framing immigration as "invasion" vs. "humanitarian situation" shapes perception even if both outlets cover the same event.' },
      { q: 'Cultivation Theory predicts that heavy television viewers will:', opts: ['Become more politically engaged than light viewers', 'Develop a perception of the world that more closely resembles the world portrayed on television, which tends to overrepresent violence and crime', 'Prefer documentary content over fiction over time', 'Lose interest in real-world news because fiction is more engaging'], ans: 1, exp: 'Gerbner\'s Cultivation Theory found that heavy viewers of television — which disproportionately depicts crime, violence, and danger — develop a "mean world syndrome," believing the world is more dangerous than it is. This effect is called cultivation because it happens gradually through sustained exposure.' },
      { q: 'In Herman and Chomsky\'s "Propaganda Model," what is meant by "flak" as one of the five filters?', opts: ['False information deliberately spread by government agencies', 'Negative feedback, criticism, or threats directed at media organizations to discourage unwelcome coverage', 'Advertising revenue that flows into media companies', 'Leaked information from anonymous sources'], ans: 1, exp: '"Flak" in the Propaganda Model refers to organized attacks on media — letters, lawsuits, boycotts, political pressure — that punish coverage that threatens powerful interests. Over time, the threat of flak causes self-censorship: editors avoid stories they know will generate attacks, without anyone needing to tell them directly.' },
    ],
  },
  {
    id: 'comm-pr',
    name: 'Public Relations & Strategic Communication',
    grade: 12, term: 'Fall', credits: 0.5,
    description: 'How organizations communicate strategically with their publics. Students learn the professional practice of public relations — from crafting press releases and managing crises to building brand narratives and navigating social media. This course bridges communications theory with the real-world demands of a career in PR, corporate communications, or nonprofit advocacy.',
    syllabus: {
      objectives: [
        'Explain the RACE model (Research, Action, Communication, Evaluation) and apply it to a PR campaign plan',
        'Write professional PR documents including press releases, media pitches, and crisis statements',
        'Develop a stakeholder communication plan identifying key publics and tailoring messages to each',
        'Analyze a crisis communication case (e.g., Johnson & Johnson Tylenol recall, United Airlines incident) and evaluate the response strategy',
        'Design and present a complete PR campaign for a real or hypothetical organization',
      ],
      units: [
        { week: '1–2',   topic: 'What Is Public Relations?',       desc: 'Defining PR and distinguishing it from advertising and journalism. The history of PR — Edward Bernays and the engineering of consent. PRSA\'s code of ethics. Two-way symmetrical vs. asymmetrical communication models (Grunig).' },
        { week: '3–4',   topic: 'The RACE Model & Campaign Planning', desc: 'Research: primary and secondary research methods, audience analysis. Action planning: objectives, strategies, and tactics. Communication: message development and channel selection. Evaluation: measuring outcomes, not just outputs.' },
        { week: '5–6',   topic: 'Media Relations',                 desc: 'The relationship between PR professionals and journalists. Writing a press release: headline, dateline, lead, body, boilerplate, contact information. The media pitch: how to make a journalist want to cover your story. Newsworthiness criteria.' },
        { week: '7–8',   topic: 'Crisis Communication',           desc: 'Types of crises and how organizations create vulnerability. The first 24 hours. Benoit\'s Image Restoration Theory: denial, evasion, reduction, corrective action, mortification. Case studies: Tylenol (1982), BP Deepwater Horizon, United Airlines 2017.' },
        { week: '9–10',  topic: 'Social Media & Digital PR',       desc: 'Social media as both a PR tool and a source of crises. Community management. Influencer relations — earned vs. paid. Social listening and monitoring tools. When a tweet becomes a crisis: real-time response strategy.' },
        { week: '11–12', topic: 'Nonprofit & Advocacy Communication', desc: 'PR for causes, not products. Framing issues for public support. Coalition building and grassroots communication. Working with policymakers and the media on social change campaigns.' },
        { week: '13',    topic: 'Ethics in PR',                    desc: 'When does strategic communication become manipulation? Astroturfing, greenwashing, and spin. PRSA Code of Ethics in practice. The difference between representing an organization\'s interests and deceiving the public.' },
        { week: '14–16', topic: 'PR Campaign Project',             desc: 'Student teams develop a full PR campaign for a real organization or cause. Deliverables: situation analysis, audience research, campaign objectives, message strategy, media plan, two sample deliverables (press release + social media plan), and evaluation metrics. Final presentation to simulated client panel.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=RneMF5WHRGQ', title: 'Introduction to Public Relations — Crash Course', channel: 'Crash Course Business', note: 'Overview of PR fundamentals, tools, and ethics. Watch as an introduction before Unit 1.' },
      { url: 'https://www.youtube.com/watch?v=mGBaUMlCK40', title: 'Crisis Communication — How Companies Should Respond', channel: 'Harvard Business Review', note: 'Expert analysis of crisis response strategy. Essential for Unit 4 case study work.' },
      { url: 'https://www.prsa.org/about/ethics/prsa-code-of-ethics', title: 'PRSA Code of Ethics', channel: 'Public Relations Society of America', note: 'The professional ethics code for PR practitioners. Primary reading for Unit 7 and the ethics dimension of the capstone project.' },
      { url: 'https://www.youtube.com/watch?v=_sD_ABQiXJ8', title: 'How to Write a Press Release — Step by Step', channel: 'PR Daily', note: 'Practical, format-based guide to writing a professional press release. Use as a reference template for Unit 3 assignments.' },
    ],
    quiz: [
      { q: 'Which of the following best describes the RACE model in public relations?', opts: ['A competitive framework for measuring PR performance against competitors', 'A four-step planning process: Research, Action planning, Communication, and Evaluation', 'A crisis response protocol used by major corporations', 'A media relations framework for pitch strategy'], ans: 1, exp: 'The RACE model provides a systematic framework for PR campaign planning. Research identifies the problem and audience. Action planning sets objectives. Communication executes the plan across chosen channels. Evaluation measures whether objectives were met. It applies to any PR campaign, from product launches to crisis recovery.' },
      { q: 'In crisis communication, what is "mortification" according to Benoit\'s Image Restoration Theory?', opts: ['A legal term for admitting liability in court', 'A strategy in which the organization acknowledges wrongdoing and sincerely apologizes, asking for forgiveness', 'A PR tactic that involves reducing the severity of the crisis in public statements', 'Transferring blame to another party to reduce the organization\'s responsibility'], ans: 1, exp: 'Mortification is the most direct image restoration strategy — the organization admits fault, expresses genuine remorse, and asks for forgiveness. It is high-risk (legally and reputationally) but often the most effective for long-term trust recovery when guilt is clear and the public demands accountability.' },
      { q: 'What distinguishes "astroturfing" from legitimate grassroots communication?', opts: ['Astroturfing uses social media; grassroots uses traditional media', 'Astroturfing creates the appearance of spontaneous public support that is actually organized and funded by a corporation or special interest', 'Grassroots campaigns are always nonprofit; astroturfing is for-profit', 'Astroturfing uses anonymous sources while grassroots campaigns are fully transparent'], ans: 1, exp: 'Astroturfing — named after the fake grass brand — is the deceptive practice of manufacturing the appearance of organic public support for a position that is actually coordinated by a corporate or political backer. It is a significant PR ethics violation because it deceives both the public and policymakers about the real breadth of support.' },
      { q: 'A press release\'s "boilerplate" section serves what purpose?', opts: ['It provides the most urgent and newsworthy information to journalists', 'It offers standard background information about the organization that appears at the end of every press release', 'It lists the specific journalist contacts the release is addressed to', 'It contains the legal disclaimers required for financial disclosures'], ans: 1, exp: 'The boilerplate is a standardized "About [Company]" paragraph at the end of a press release that provides background on the organization — who they are, what they do, where they operate. It is reused across releases and gives journalists context without requiring them to research the organization.' },
    ],
  },
  {
    id: 'comm-capstone',
    name: 'Communications Capstone: Original Media Project',
    grade: 12, term: 'Spring', credits: 1.0,
    description: 'The culmination of four years of communications study. Students conceive, research, produce, and publish a substantial original media project — a documentary, investigative long-form article, podcast series, or multimedia campaign — that represents their voice, perspective, and the full range of skills developed in this pathway. The capstone becomes the centerpiece of the student\'s college application portfolio.',
    syllabus: {
      objectives: [
        'Identify a genuine story, issue, or argument worth communicating publicly and defend its newsworthiness and audience value',
        'Complete a full production cycle — research, planning, drafting, production, editing, and publication — managing a semester-long timeline independently',
        'Apply theoretical frameworks from Media Theory & Society to reflect critically on your own storytelling choices',
        'Present the completed project in a public defense, explaining editorial and ethical decisions to a panel',
        'Assemble and contextualize a professional communications portfolio for college admissions and future employers',
      ],
      units: [
        { week: '1–2',   topic: 'Capstone Pitch & Proposal',       desc: 'Students develop and present a 10-minute pitch: What is your project? Why does it matter? Who is your audience? What form best serves the story? What are the risks and ethical considerations? Instructor and peer panel approves proposals and sets deliverable milestones.' },
        { week: '3–4',   topic: 'Research & Source Development',    desc: 'Deep background research. For journalism projects: developing human sources, submitting FOIA requests, building a document trail. For documentary: identifying subjects, negotiating access. For campaigns: audience research and stakeholder mapping. All students maintain a research log.' },
        { week: '5–7',   topic: 'Production Sprint 1',              desc: 'First phase of content creation: first interviews conducted, first draft sections written, initial footage shot, or first podcast episode recorded. Weekly check-ins with instructor. Written progress report at end of Week 7.' },
        { week: '8',     topic: 'Mid-Project Critique',             desc: 'Students present work-in-progress to a peer panel. Receive structured feedback on narrative clarity, evidence quality, ethical issues, and production quality. Revise production plan for Sprint 2 based on feedback.' },
        { week: '9–12',  topic: 'Production Sprint 2',              desc: 'Major production phase: complete interviews, write full drafts, edit footage, mix audio, design graphics. Students maintain a decisions journal documenting every significant editorial choice and why they made it.' },
        { week: '13',    topic: 'Ethical Review',                   desc: 'Every project undergoes a formal ethical review: Who could be harmed by this content? Have all subjects given informed consent? Are claims supported by sufficient evidence? Have we handled sensitive topics — trauma, privacy, legal jeopardy — with appropriate care? Revisions required where issues are identified.' },
        { week: '14–15', topic: 'Polish, Publication & Portfolio',  desc: 'Final editing and quality review. Students publish or formally present their work — on the school media site, a personal site, a streaming platform, or a printed publication. Portfolio assembly: curate best work from all four pathway courses with reflective framing for each piece.' },
        { week: '16',    topic: 'Public Defense & Celebration',     desc: 'Formal public defense: 15-minute presentation of the project followed by 10 minutes of Q&A from a panel including instructors, guest communications professionals, and peers. Students explain their editorial vision, the challenges encountered, what they would do differently, and what the project taught them about communication.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=2uqBVAbeqLQ', title: 'How to Make a Documentary — End to End Production Guide', channel: 'StudioBinder', note: 'Comprehensive documentary production guide covering development through distribution. Essential reference for documentary capstone projects.' },
      { url: 'https://www.poynter.org/reporting-editing/2020/how-to-do-an-investigative-story-a-beginners-guide/', title: 'How to Do an Investigative Story — Poynter Guide', channel: 'Poynter Institute', note: 'Step-by-step guide to investigative journalism methodology — sourcing, documents, FOIA, verification. Required reading for journalism capstone projects.' },
      { url: 'https://www.youtube.com/watch?v=Up3P2MpAnTI', title: 'Building a Media Portfolio for College Admissions', channel: 'College Essay Advisors', note: 'Guidance on how to frame and present a media portfolio for communications program admissions. Watch during Weeks 14–15.' },
      { url: 'https://ireporthub.org/', title: 'iReport Hub — Student Journalism Resources', channel: 'iReport Hub', note: 'Platform for student journalism publication and peer community. Consider publishing your capstone work here for a real public audience.' },
    ],
    quiz: [
      { q: 'Before publishing a story that names a private individual in connection with wrongdoing, what ethical obligation does a journalist have that is articulated in the SPJ Code of Ethics?', opts: ['The journalist must obtain approval from their organization\'s legal team', 'The journalist must give the subject an opportunity to respond to the allegations before publication', 'The journalist must get a signed release form from the subject', 'The journalist must have at least five independent sources confirming the allegation'], ans: 1, exp: 'The SPJ Code\'s "minimize harm" principle includes the obligation to give subjects of negative coverage an opportunity to respond before publication. This is both an ethical requirement and good journalistic practice — the subject may have information that changes the story or can provide context that improves accuracy.' },
      { q: 'What distinguishes a "primary source" from a "secondary source" in the context of communications research?', opts: ['Primary sources are always more credible than secondary sources', 'A primary source is original material (interview, document, video); a secondary source analyzes or interprets primary sources', 'Primary sources are published; secondary sources are unpublished', 'A primary source is a named source; a secondary source is anonymous'], ans: 1, exp: 'Primary sources are original, unmediated material — the interview transcript, the government document, the footage, the original study. Secondary sources interpret, analyze, or synthesize primary sources. Strong journalism and scholarship are built on primary sources; secondary sources provide context and analysis.' },
      { q: 'When applying McLuhan\'s medium theory to a capstone documentary project, a student should ask:', opts: ['Which streaming platform has the largest audience?', 'How does the choice of documentary as a form — versus text, versus podcast — shape what the story can be and how audiences will experience it?', 'How long should each interview segment be to maximize viewer retention?', 'What is the minimum production quality required for college portfolio submission?'], ans: 1, exp: 'McLuhan\'s insight is that the medium itself communicates — the embodied experience of watching documentary (sound, image, real faces, time unfolding) does something text cannot. A documentary capstone student should consciously choose documentary form because of what it uniquely enables, and reflect on how that choice shapes the story.' },
      { q: 'What is "informed consent" in the context of documentary filming or journalism interviews?', opts: ['The subject signs a contract promising not to sue after publication', 'The subject agrees to participate with clear understanding of how the material will be used, who will see it, and what risks participation may carry', 'The journalist informs their editor before conducting a sensitive interview', 'The subject consents to every quote being published exactly as spoken'], ans: 1, exp: 'Informed consent means the subject understands what they are agreeing to — the nature of the project, the intended audience, how their words or image will be used, and any potential consequences of participation. It is especially important when working with vulnerable subjects (minors, trauma survivors, people facing legal jeopardy) and is a core requirement of ethical communications practice.' },
    ],
  },
];

export default function CommunicationsPathway() {
  return <PathwayPage meta={META} schedule={SCHEDULE} courses={COURSES} />;
}
