import React from 'react';
import { PathwayPage } from './PathwayComponents';

const COLOR = '#1565C0';

const META = {
  color: COLOR,
  title: 'Computer Science & Engineering',
  subtitle: 'Build the systems that run the world.',
  emoji: '💻',
  courseEmoji: '💻',
  heroDescription: 'A rigorous 4-year pathway for students aiming for top CS and engineering programs. From Python fundamentals to machine learning, you will graduate with a professional portfolio, AP CS credit, and the problem-solving mindset that colleges like MIT, CMU, and UC Berkeley look for.',
  targets: ['Computer Science / Software Engineering', 'Data Science & AI / Machine Learning', 'Computer Engineering & Systems', 'Cybersecurity', 'Game Development', 'Robotics & Embedded Systems'],
  collegeNote: 'AP Computer Science A, a completed software project portfolio, and a full 4-year progression from algorithms through machine learning signal deep commitment to admissions committees at top CS programs. Students who complete this pathway are well-positioned for CS, CE, or Data Science majors at selective universities.',
  stats: [{ label: 'AP Courses', value: 1 }],
};

const SCHEDULE = [
  { grade: 9, term: 'Fall', courses: [
    { name: 'English I',                  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra I',                  type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology',                    type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World History',              type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Physical Education',         type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Intro to Programming',       type: 'pathway',   credits: 0.5, courseId: 'cs-intro' },
  ]},
  { grade: 9, term: 'Spring', courses: [
    { name: 'English I — Writing',        type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Geometry',                   type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Environmental Science',      type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Geography',                  type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Health & Wellness',          type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Web Development Basics',     type: 'pathway',   credits: 0.5, courseId: 'cs-web' },
  ]},
  { grade: 10, term: 'Fall', courses: [
    { name: 'English II',                 type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra II',                 type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Chemistry',                  type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'U.S. History',              type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Data Structures & Algorithms', type: 'pathway', credits: 0.5, courseId: 'cs-dsa' },
    { name: 'Discrete Mathematics',       type: 'supporting', credits: 0.5, dept: 'Mathematics' },
  ]},
  { grade: 10, term: 'Spring', courses: [
    { name: 'English II — Literature',    type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Pre-Calculus',              type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics Fundamentals',      type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World Politics',            type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Computer Systems & Networks', type: 'pathway', credits: 0.5, courseId: 'cs-systems' },
  ]},
  { grade: 11, term: 'Fall', courses: [
    { name: 'English III',               type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Statistics',                type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology — Advanced',        type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'AP Computer Science A',     type: 'pathway',   credits: 1.0, courseId: 'cs-apcs' },
  ]},
  { grade: 11, term: 'Spring', courses: [
    { name: 'English III — Literature',  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Trigonometry',              type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics — Mechanics',       type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Software Engineering',      type: 'pathway',   credits: 0.5, courseId: 'cs-swe' },
    { name: 'AP Statistics',             type: 'supporting', credits: 1.0, dept: 'Mathematics', note: 'Strongly recommended' },
  ]},
  { grade: 12, term: 'Fall', courses: [
    { name: 'English IV — Writing & Communication', type: 'core', credits: 1.0, dept: 'English Language Arts' },
    { name: 'Calculus',                  type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Machine Learning Fundamentals', type: 'pathway', credits: 1.0, courseId: 'cs-ml' },
    { name: 'Linear Algebra',            type: 'supporting', credits: 0.5, dept: 'Mathematics', note: 'College-level prep' },
  ]},
  { grade: 12, term: 'Spring', courses: [
    { name: 'English IV — Advanced Composition', type: 'core', credits: 1.0, dept: 'English Language Arts' },
    { name: 'CS Capstone Project',       type: 'pathway',   credits: 1.0, courseId: 'cs-capstone' },
    { name: 'Ethics in Technology',      type: 'supporting', credits: 0.5, dept: 'Social Studies' },
  ]},
];

const COURSES = [
  {
    id: 'cs-intro',
    name: 'Introduction to Programming',
    grade: 9, term: 'Fall', credits: 0.5,
    description: 'Learn to think like a programmer. This course uses Python to teach variables, conditionals, loops, functions, and basic data structures. By the end you will have built three working programs and understand the foundations every CS course builds on.',
    syllabus: {
      objectives: [
        'Write syntactically correct Python programs using core control structures',
        'Break problems into functions and explain the purpose of each',
        'Debug programs systematically using print statements and error messages',
        'Understand how computers store and process data at a basic level',
        'Build and present a personal project to demonstrate programming skills',
      ],
      units: [
        { week: '1–2',   topic: 'How Computers Work',         desc: 'Binary, CPU, memory, OS — what happens when you run a program.' },
        { week: '3–4',   topic: 'Python Basics',              desc: 'Variables, data types (int, float, str, bool), input/output.' },
        { week: '5–6',   topic: 'Conditionals & Logic',       desc: 'if/elif/else, Boolean expressions, comparison operators.' },
        { week: '7–8',   topic: 'Loops',                      desc: 'for loops, while loops, range(), nested loops, break/continue.' },
        { week: '9–10',  topic: 'Functions',                  desc: 'Defining functions, parameters, return values, scope.' },
        { week: '11–12', topic: 'Lists & Dictionaries',       desc: 'Indexing, slicing, iteration, common list methods, key-value pairs.' },
        { week: '13',    topic: 'File I/O & Error Handling',  desc: 'Reading/writing files, try/except blocks.' },
        { week: '14–16', topic: 'Final Project',              desc: 'Design and build a Python program of your choice. Present with code walkthrough.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=rfscVS0vtbw', title: 'Learn Python — Full Course for Beginners', channel: 'freeCodeCamp', note: '4.5-hour comprehensive Python tutorial, perfect for this course.' },
      { url: 'https://www.khanacademy.org/computing/intro-to-python-fundamentals', title: 'Intro to Python Fundamentals', channel: 'Khan Academy', note: 'Interactive exercises with instant feedback — great for practicing each topic.' },
      { url: 'https://cs50.harvard.edu/python/2022/', title: 'CS50P — Introduction to Programming with Python', channel: 'Harvard CS50', note: 'Free full course from Harvard. Watch the lectures, do the problem sets.' },
      { url: 'https://www.youtube.com/watch?v=eWRfhZUzrAc', title: 'Python for Beginners — Full Course', channel: 'Tech With Tim', note: 'Shorter, beginner-friendly series. Good for reviewing specific topics.' },
    ],
    quiz: [
      { q: 'What will this Python code print?\nx = 10\nif x > 5:\n    print("big")\nelse:\n    print("small")', opts: ['"big"', '"small"', 'Nothing', 'Error'], ans: 0, exp: 'x is 10, which is greater than 5, so the if-branch executes and prints "big".' },
      { q: 'Which data type would you use to store the value True or False?', opts: ['int', 'str', 'bool', 'float'], ans: 2, exp: 'bool (Boolean) is specifically designed to represent True or False values in Python.' },
      { q: 'What does a function\'s return statement do?', opts: ['Prints a value to the screen', 'Sends a value back to whoever called the function', 'Ends the entire program', 'Creates a new variable'], ans: 1, exp: 'return sends a value back to the calling code. The function then "becomes" that value at the call site.' },
      { q: 'How many times does this loop execute?\nfor i in range(3):\n    print(i)', opts: ['2 times', '3 times', '4 times', '0 times'], ans: 1, exp: 'range(3) generates [0, 1, 2] — three values. The loop body executes once for each, so 3 times total.' },
      { q: 'What is the correct way to define a function in Python?', opts: ['function myFunc():', 'def myFunc():', 'func myFunc():', 'define myFunc():'], ans: 1, exp: 'Python uses the "def" keyword to define functions. The syntax is: def function_name(parameters):' },
    ],
  },
  {
    id: 'cs-web',
    name: 'Web Development Basics',
    grade: 9, term: 'Spring', credits: 0.5,
    description: 'Build real websites from scratch. Learn HTML to structure content, CSS to style it, and introductory JavaScript to make it interactive. You will publish a personal portfolio website by the end of the course.',
    syllabus: {
      objectives: [
        'Write semantic HTML5 to structure web pages correctly',
        'Apply CSS properties including flexbox and grid for layout',
        'Use JavaScript to respond to user events and modify the page',
        'Understand how browsers parse and render HTML, CSS, and JS',
        'Deploy a multi-page personal website to the internet',
      ],
      units: [
        { week: '1–2',   topic: 'How the Web Works',         desc: 'HTTP, DNS, servers vs. clients, what a browser does.' },
        { week: '3–4',   topic: 'HTML Fundamentals',         desc: 'Tags, attributes, headings, paragraphs, links, images, tables, forms.' },
        { week: '5–6',   topic: 'CSS Basics',                desc: 'Selectors, the box model, colors, fonts, backgrounds.' },
        { week: '7–8',   topic: 'CSS Layout',                desc: 'Flexbox, grid, responsive design, media queries.' },
        { week: '9–10',  topic: 'JavaScript Intro',          desc: 'Variables, functions, DOM selection, event listeners.' },
        { week: '11–12', topic: 'JS Interactivity',          desc: 'Changing page content, form validation, simple animations.' },
        { week: '13',    topic: 'Deployment',                desc: 'GitHub Pages, file structure, debugging in DevTools.' },
        { week: '14–16', topic: 'Portfolio Project',         desc: 'Design and publish a personal portfolio site. Peer critique and final presentation.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=pQN-pnXPaVg', title: 'HTML Full Course — Build a Website Tutorial', channel: 'freeCodeCamp', note: 'Start here — covers HTML and CSS from scratch in 2 hours.' },
      { url: 'https://www.khanacademy.org/computing/computer-programming/html-css', title: 'Intro to HTML/CSS: Making Webpages', channel: 'Khan Academy', note: 'Interactive lessons with live code editor — ideal for practice.' },
      { url: 'https://www.youtube.com/watch?v=G3e-cpL7ofc', title: 'HTML & CSS Full Course — Beginner to Pro', channel: 'SuperSimpleDev', note: 'Extremely clear explanations of how HTML and CSS work together.' },
      { url: 'https://www.youtube.com/watch?v=jS4aFq5-91M', title: 'JavaScript Full Course for Beginners', channel: 'Dave Gray', note: 'Complete JS fundamentals series. Watch the first 10 episodes for this course.' },
    ],
    quiz: [
      { q: 'Which HTML tag is used to create a hyperlink?', opts: ['<link>', '<a>', '<href>', '<url>'], ans: 1, exp: 'The <a> (anchor) tag creates hyperlinks. The href attribute specifies the destination URL.' },
      { q: 'In CSS, which property controls the space between an element\'s border and surrounding elements?', opts: ['padding', 'margin', 'border', 'spacing'], ans: 1, exp: 'margin controls the space outside an element\'s border. padding controls space inside the border.' },
      { q: 'What does CSS stand for?', opts: ['Creative Style Sheets', 'Cascading Style Sheets', 'Computer Style System', 'Coded Styling Syntax'], ans: 1, exp: 'CSS stands for Cascading Style Sheets. "Cascading" refers to how styles inherit and override each other.' },
      { q: 'Which JavaScript method selects an HTML element by its id?', opts: ['document.getElement()', 'document.getElementById()', 'document.findById()', 'document.select()'], ans: 1, exp: 'document.getElementById("myId") returns the element with that id. It\'s the most direct DOM selector.' },
      { q: 'What is the correct HTML for an image?', opts: ['<image src="pic.jpg">', '<img href="pic.jpg">', '<img src="pic.jpg">', '<picture src="pic.jpg">'], ans: 2, exp: '<img src="..."> is the correct syntax. The src attribute specifies the image file path or URL.' },
    ],
  },
  {
    id: 'cs-dsa',
    name: 'Data Structures & Algorithms',
    grade: 10, term: 'Fall', credits: 0.5,
    description: 'The course that separates programmers from engineers. Learn how to store, organize, and process data efficiently. Master arrays, linked lists, stacks, queues, trees, and graphs — and the algorithms that operate on them. This is core material for every CS college interview.',
    syllabus: {
      objectives: [
        'Analyze algorithm efficiency using Big-O notation',
        'Implement core data structures in Python from scratch',
        'Choose the right data structure for a given problem',
        'Trace and implement recursive algorithms',
        'Solve common coding problems involving searching and sorting',
      ],
      units: [
        { week: '1–2',   topic: 'Complexity & Big-O',        desc: 'Time vs. space complexity, O(1), O(n), O(n²), O(log n) — what they mean in practice.' },
        { week: '3–4',   topic: 'Arrays & Strings',          desc: 'Indexing, two-pointer technique, sliding window, common interview patterns.' },
        { week: '5–6',   topic: 'Linked Lists',              desc: 'Singly and doubly linked lists, insertion, deletion, reversal.' },
        { week: '7',     topic: 'Stacks & Queues',           desc: 'LIFO vs. FIFO, implementation with arrays and linked lists, use cases.' },
        { week: '8–9',   topic: 'Recursion',                 desc: 'Base cases, call stacks, recursion vs. iteration, factorial, Fibonacci, tree traversal.' },
        { week: '10–11', topic: 'Searching & Sorting',       desc: 'Binary search, bubble/selection/insertion sort, merge sort, quicksort.' },
        { week: '12–13', topic: 'Trees',                     desc: 'Binary trees, BSTs, DFS, BFS traversal algorithms.' },
        { week: '14–16', topic: 'Graphs & Final Project',    desc: 'Graph representation, BFS/DFS on graphs, shortest path intro. Final: solve and explain 5 LeetCode-style problems.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=pkYVOmU3MgA', title: 'Data Structures Easy to Advanced — Full Course', channel: 'freeCodeCamp / WilliamFiset', note: 'The most comprehensive free DSA course. Watch alongside the weekly topics.' },
      { url: 'https://www.youtube.com/watch?v=RBSGKlAvoiM', title: 'Data Structures — Full Course Using C and C++', channel: 'freeCodeCamp', note: 'Covers all structures with clear visual animations. Language-agnostic concepts apply to Python.' },
      { url: 'https://neetcode.io/', title: 'NeetCode — Structured DSA Practice', channel: 'NeetCode', note: 'Free roadmap of 150 curated LeetCode problems organized by topic. Ideal for this course.' },
      { url: 'https://www.youtube.com/watch?v=BgLTDT03QtU', title: 'Big O Notation — Full Course', channel: 'freeCodeCamp', note: 'Clear explanation of complexity analysis — watch in Week 1.' },
    ],
    quiz: [
      { q: 'What is the time complexity of accessing an element by index in an array?', opts: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], ans: 2, exp: 'Arrays store elements in contiguous memory, so any index can be accessed in constant time O(1) — no matter how large the array is.' },
      { q: 'Which data structure follows the Last-In, First-Out (LIFO) principle?', opts: ['Queue', 'Stack', 'Array', 'Linked List'], ans: 1, exp: 'A Stack follows LIFO — the last element added is the first removed. Think of a stack of plates.' },
      { q: 'What is the time complexity of binary search?', opts: ['O(n)', 'O(n log n)', 'O(log n)', 'O(1)'], ans: 2, exp: 'Binary search halves the search space each step, giving O(log n) time. Requires a sorted array.' },
      { q: 'In a Linked List, each node contains:', opts: ['Only the data value', 'Data and a pointer to the next node', 'Data and an index', 'A key-value pair'], ans: 1, exp: 'Each linked list node stores data and a pointer (reference) to the next node — this is what creates the chain.' },
      { q: 'Which sorting algorithm has O(n log n) average time complexity?', opts: ['Bubble Sort', 'Insertion Sort', 'Selection Sort', 'Merge Sort'], ans: 3, exp: 'Merge Sort divides the array recursively and merges sorted halves — achieving O(n log n) consistently. Bubble, insertion, and selection sort are all O(n²) on average.' },
    ],
  },
  {
    id: 'cs-systems',
    name: 'Computer Systems & Networks',
    grade: 10, term: 'Spring', credits: 0.5,
    description: 'Go beneath the surface of software. Understand how CPUs execute code, how operating systems manage resources, and how computers communicate across networks. This course bridges theory and the real world — from your laptop to the internet.',
    syllabus: {
      objectives: [
        'Explain the von Neumann architecture and how code becomes machine instructions',
        'Describe how operating systems manage processes, memory, and files',
        'Understand the TCP/IP model and how data travels across the internet',
        'Explain the basics of cryptography and secure communication',
        'Analyze a simple network and describe potential security vulnerabilities',
      ],
      units: [
        { week: '1–2',   topic: 'Number Systems',            desc: 'Binary, hexadecimal, ASCII, Unicode — how computers represent everything as numbers.' },
        { week: '3–4',   topic: 'CPU & Memory',              desc: 'Registers, ALU, fetch-decode-execute cycle, RAM vs. storage, cache.' },
        { week: '5–6',   topic: 'Operating Systems',         desc: 'Processes, threads, scheduling, virtual memory, file systems.' },
        { week: '7–8',   topic: 'Networking Basics',         desc: 'OSI model, IP addressing, DNS, routing, packets.' },
        { week: '9–10',  topic: 'The Internet',              desc: 'HTTP/HTTPS, TCP vs. UDP, how browsers request web pages end-to-end.' },
        { week: '11–12', topic: 'Cryptography',              desc: 'Symmetric vs. asymmetric encryption, public/private keys, TLS, hashing.' },
        { week: '13',    topic: 'Cybersecurity Intro',       desc: 'Common attacks (phishing, SQL injection, XSS), defense strategies.' },
        { week: '14–16', topic: 'Systems Analysis Project',  desc: 'Diagram a real-world system (e.g., "how does streaming video work?") from hardware to user screen.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=zOjov-2OZ0E', title: 'How Computers Work — Crash Course', channel: 'Crash Course Computer Science', note: '10-episode playlist covering CPU, OS, and networking. Watch episodes 1–10.' },
      { url: 'https://www.khanacademy.org/computing/computers-and-internet', title: 'Computers and the Internet', channel: 'Khan Academy', note: 'Interactive unit covering bits, circuits, internet protocols, and cybersecurity.' },
      { url: 'https://www.youtube.com/watch?v=AEaKrq3SpW8', title: 'Computer Networking Full Course', channel: 'freeCodeCamp', note: 'In-depth networking course — relevant for weeks 7–12 of this course.' },
      { url: 'https://cs50.harvard.edu/x/', title: 'CS50x Week 0–4', channel: 'Harvard CS50', note: 'CS50 weeks 0–4 cover C, memory, and algorithms at the systems level. Watch Weeks 0–2.' },
    ],
    quiz: [
      { q: 'How many bits are in a byte?', opts: ['4', '8', '16', '32'], ans: 1, exp: '1 byte = 8 bits. This is a fundamental unit — all storage (KB, MB, GB) is measured in multiples of bytes.' },
      { q: 'What does DNS stand for and what does it do?', opts: ['Data Network System — routes data packets', 'Domain Name System — translates domain names to IP addresses', 'Digital Network Service — manages internet connections', 'Direct Node System — connects devices directly'], ans: 1, exp: 'DNS translates human-readable domain names (like google.com) to numeric IP addresses that routers can use to deliver data.' },
      { q: 'Which layer of the OSI model handles IP addressing and routing?', opts: ['Physical Layer', 'Data Link Layer', 'Network Layer', 'Transport Layer'], ans: 2, exp: 'The Network Layer (Layer 3) handles logical addressing (IP) and routing — determining the best path for data packets.' },
      { q: 'What is the key difference between symmetric and asymmetric encryption?', opts: ['Symmetric is slower', 'Symmetric uses one key for both encrypt and decrypt; asymmetric uses a public/private key pair', 'Asymmetric can only encrypt, not decrypt', 'Symmetric requires the internet to work'], ans: 1, exp: 'Symmetric encryption uses the same secret key to encrypt and decrypt. Asymmetric uses a public key to encrypt and a private key to decrypt — enabling secure communication without sharing secrets.' },
      { q: 'In the context of operating systems, what is a process?', opts: ['A file stored on disk', 'A running instance of a program in memory', 'A type of CPU instruction', 'A network connection'], ans: 1, exp: 'A process is a program that is currently loaded into memory and being executed by the CPU, along with its resources (memory, file handles, etc.).' },
    ],
  },
  {
    id: 'cs-apcs',
    name: 'AP Computer Science A',
    grade: 11, term: 'Fall', credits: 1.0,
    description: 'College-level Java programming and object-oriented design. This is the standard CS AP exam that demonstrates college readiness. You will learn OOP principles (classes, inheritance, polymorphism), work with arrays and ArrayLists, and develop problem-solving skills tested in the AP exam in May.',
    syllabus: {
      objectives: [
        'Write and debug Java programs using correct syntax and OOP principles',
        'Design class hierarchies using inheritance and interfaces',
        'Work with arrays, ArrayLists, and 2D arrays',
        'Trace recursive algorithms and write recursive solutions',
        'Achieve a score of 3 or higher on the AP CS A exam',
      ],
      units: [
        { week: '1–3',   topic: 'Java Fundamentals',         desc: 'Primitive types, variables, operators, control flow — parallel to Python but with static typing.' },
        { week: '4–5',   topic: 'Classes & Objects',         desc: 'Writing classes, constructors, instance variables, methods, encapsulation.' },
        { week: '6–7',   topic: 'Inheritance',               desc: 'extends, super, method overriding, polymorphism, abstract classes.' },
        { week: '8–9',   topic: 'Arrays',                    desc: '1D and 2D arrays, for-each loops, passing arrays to methods.' },
        { week: '10',    topic: 'ArrayLists',                desc: 'Dynamic arrays, add/remove/get, iterating, comparing to arrays.' },
        { week: '11–12', topic: 'Searching & Sorting',       desc: 'Sequential search, binary search, selection sort, insertion sort, merge sort in Java.' },
        { week: '13',    topic: 'Recursion',                 desc: 'Recursive methods, tracing call stacks, classic recursive problems.' },
        { week: '14–16', topic: 'AP Exam Prep',              desc: 'Practice FRQs, multiple-choice review, timed exam simulations.' },
      ],
    },
    resources: [
      { url: 'https://apclassroom.collegeboard.org/', title: 'AP Classroom — Official AP CS A Resources', channel: 'College Board', note: 'Official practice FRQs, progress checks, and AP Daily videos. Use this throughout the year.' },
      { url: 'https://www.youtube.com/watch?v=A74TOX803D0', title: 'AP Computer Science A — Full Course', channel: 'Replit / APCS Academy', note: 'Complete AP CS A course covering every exam topic with practice problems.' },
      { url: 'https://codehs.com/course/apjava', title: 'CodeHS AP Computer Science A', channel: 'CodeHS', note: 'Interactive Java programming environment with built-in AP CS A curriculum.' },
      { url: 'https://www.youtube.com/watch?v=2Xa3Y4xz8_s', title: 'Java Inheritance and Polymorphism', channel: 'Coding with John', note: 'Clear explanation of OOP concepts — watch before the Inheritance unit.' },
    ],
    quiz: [
      { q: 'What keyword is used to create a subclass in Java?', opts: ['implements', 'extends', 'inherits', 'super'], ans: 1, exp: 'extends creates a subclass. For example: class Dog extends Animal { } means Dog inherits from Animal.' },
      { q: 'What is the index of the last element in a Java array of length 5?', opts: ['5', '4', '0', '6'], ans: 1, exp: 'Arrays are zero-indexed. A length-5 array has elements at indices 0, 1, 2, 3, 4. The last index is always length − 1 = 4.' },
      { q: 'Which of the following correctly creates an ArrayList of Strings in Java?', opts: ['ArrayList list = new ArrayList<String>();', 'ArrayList<String> list = new ArrayList<String>();', 'String[] list = new ArrayList<>();', 'List list = new String ArrayList();'], ans: 1, exp: 'ArrayList<String> list = new ArrayList<String>(); is the correct declaration. The type parameter <String> specifies what type of objects the list holds.' },
      { q: 'What does method overriding allow a subclass to do?', opts: ['Add new instance variables to the superclass', 'Provide its own implementation of a method defined in the superclass', 'Call private methods in the superclass', 'Create multiple versions of a method in the same class'], ans: 1, exp: 'Method overriding allows a subclass to provide its own implementation of a method inherited from the superclass. The @Override annotation marks overridden methods.' },
      { q: 'What is the base case in a recursive method?', opts: ['The first call to the method', 'The condition that stops the recursion', 'The return type of the method', 'The deepest level of recursion'], ans: 1, exp: 'The base case is the condition under which the recursive method stops calling itself and returns a value directly. Without it, the method would recurse infinitely and cause a stack overflow.' },
    ],
  },
  {
    id: 'cs-swe',
    name: 'Software Engineering',
    grade: 11, term: 'Spring', credits: 0.5,
    description: 'Professional programming is more than writing code — it is designing systems, collaborating with teams, managing versions, and shipping products. Learn Git, agile methodologies, code review, testing, and how real software teams operate.',
    syllabus: {
      objectives: [
        'Use Git and GitHub for version control and collaborative coding',
        'Apply agile sprint planning to a group software project',
        'Write unit tests and explain the role of test-driven development',
        'Design software using UML diagrams and system design principles',
        'Present and demo a team-built web application',
      ],
      units: [
        { week: '1–2',   topic: 'Software Development Lifecycle', desc: 'Waterfall, agile, scrum — how software goes from idea to product.' },
        { week: '3–4',   topic: 'Git & Version Control',    desc: 'init, commit, branch, merge, pull requests, resolving conflicts on GitHub.' },
        { week: '5–6',   topic: 'System Design Basics',     desc: 'Requirements gathering, UML diagrams, architecture patterns (MVC, client-server).' },
        { week: '7–8',   topic: 'Testing',                  desc: 'Unit testing, integration testing, test-driven development (TDD), test coverage.' },
        { week: '9–10',  topic: 'Databases & APIs',         desc: 'Relational vs. NoSQL databases, REST APIs, making HTTP requests from code.' },
        { week: '11–12', topic: 'Agile Team Sprint 1',      desc: 'Sprint planning, daily standups, backlog grooming, retrospective.' },
        { week: '13–14', topic: 'Agile Team Sprint 2',      desc: 'Build and integrate features, code review process, merge PRs.' },
        { week: '15–16', topic: 'Demo Day',                 desc: 'Present working application, reflect on technical decisions and team process.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=RGOj5yH7evk', title: 'Git and GitHub for Beginners — Crash Course', channel: 'freeCodeCamp', note: 'Master Git from scratch. Complete this in Week 1 before starting any team project.' },
      { url: 'https://www.youtube.com/watch?v=2ReR1YJrNom', title: 'Agile Methodology — Full Introduction', channel: 'freeCodeCamp', note: 'Clear introduction to agile, scrum, and sprint workflows.' },
      { url: 'https://www.youtube.com/watch?v=BJe1EcW4x4M', title: 'System Design for Beginners', channel: 'Exponent', note: 'Intro to thinking about scale, architecture, and real-world system design.' },
      { url: 'https://www.youtube.com/watch?v=6sNmJtoKDCo', title: 'Test-Driven Development (TDD) — Full Guide', channel: 'Fireship', note: 'Short, practical video showing how to write tests before writing code.' },
    ],
    quiz: [
      { q: 'In Git, what does a "commit" represent?', opts: ['Uploading code to GitHub', 'A snapshot of the project at a specific point in time', 'Creating a new branch', 'Merging two branches together'], ans: 1, exp: 'A commit is a saved snapshot of your code. Git stores the entire history of commits, allowing you to go back to any previous state.' },
      { q: 'What is the main benefit of Test-Driven Development (TDD)?', opts: ['It makes code run faster', 'Tests are written before code, ensuring features meet requirements from the start', 'It eliminates the need for code review', 'It automatically deploys your code'], ans: 1, exp: 'In TDD, you write a failing test first, then write just enough code to make it pass. This ensures code correctness and forces you to think about design before implementation.' },
      { q: 'In agile methodology, what is a "sprint"?', opts: ['Running your code as fast as possible', 'A fixed time period (usually 1-2 weeks) in which the team completes a set of tasks', 'A type of automated test', 'A code review session'], ans: 1, exp: 'A sprint is a time-boxed iteration — typically 1–2 weeks — in which the team commits to completing a specific set of user stories from the backlog.' },
      { q: 'What does a REST API primarily use to communicate between client and server?', opts: ['File transfers', 'HTTP requests and responses', 'Direct database connections', 'WebSockets only'], ans: 1, exp: 'REST APIs use standard HTTP methods (GET, POST, PUT, DELETE) to transfer data between client and server, typically in JSON format.' },
    ],
  },
  {
    id: 'cs-ml',
    name: 'Machine Learning Fundamentals',
    grade: 12, term: 'Fall', credits: 1.0,
    description: 'Understand the algorithms powering AI. This course covers the mathematical intuition behind supervised and unsupervised learning, and applies it using Python (scikit-learn, NumPy, pandas). You will train real models on real datasets — from linear regression to neural network basics.',
    syllabus: {
      objectives: [
        'Explain the difference between supervised, unsupervised, and reinforcement learning',
        'Implement and evaluate linear regression and classification models',
        'Apply the train/test split methodology and understand overfitting',
        'Use scikit-learn to train, evaluate, and tune models',
        'Build and train a basic neural network using a framework',
      ],
      units: [
        { week: '1–2',   topic: 'What is Machine Learning?',    desc: 'AI vs. ML vs. deep learning. Types of learning. Real-world applications.' },
        { week: '3–4',   topic: 'Data & NumPy/Pandas',         desc: 'Arrays, DataFrames, data cleaning, exploratory data analysis (EDA).' },
        { week: '5–6',   topic: 'Linear Regression',           desc: 'Cost function, gradient descent, evaluating with MSE and R².' },
        { week: '7–8',   topic: 'Classification',              desc: 'Logistic regression, decision trees, k-NN, confusion matrix, precision/recall.' },
        { week: '9',     topic: 'Model Evaluation',            desc: 'Train/test split, cross-validation, bias-variance tradeoff, overfitting.' },
        { week: '10–11', topic: 'Unsupervised Learning',       desc: 'K-means clustering, dimensionality reduction (PCA), t-SNE.' },
        { week: '12–13', topic: 'Neural Networks Intro',       desc: 'Perceptrons, activation functions, forward/backpropagation, basic Keras model.' },
        { week: '14–16', topic: 'ML Project',                  desc: 'End-to-end ML project: problem definition, data collection, model training, evaluation, and presentation.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=KNAWp2S3w94', title: 'Machine Learning for Everybody — Full Course', channel: 'freeCodeCamp / Kylie Ying', note: 'Beginner-friendly ML course using Python and scikit-learn. Work through it in the first 8 weeks.' },
      { url: 'https://www.youtube.com/watch?v=aircAruvnKk', title: 'Neural Networks — 3Blue1Brown', channel: '3Blue1Brown', note: 'The best visual explanation of how neural networks and backpropagation work. Watch the entire playlist.' },
      { url: 'https://www.kaggle.com/learn', title: 'Kaggle Learn — ML Micro-Courses', channel: 'Kaggle', note: 'Free courses on Python, Pandas, ML, and deep learning with interactive notebooks. Use for the data and modeling units.' },
      { url: 'https://www.youtube.com/watch?v=i_LwzRVP7bg', title: 'Pandas Tutorial — Data Science in Python', channel: 'Tech With Tim', note: 'Comprehensive Pandas tutorial for data manipulation — essential for Week 3–4.' },
    ],
    quiz: [
      { q: 'In supervised learning, what does the "label" refer to?', opts: ['The name of the dataset', 'The correct answer / output that the model is trained to predict', 'A feature used as input', 'The model\'s prediction'], ans: 1, exp: 'In supervised learning, labels are the known correct outputs for each training example. The model learns to map inputs to these labels.' },
      { q: 'What is overfitting?', opts: ['When a model trains too quickly', 'When a model performs well on training data but poorly on new data', 'When a model has too few parameters', 'When training data is too large'], ans: 1, exp: 'Overfitting occurs when a model memorizes training data (including noise) instead of learning general patterns. It shows high training accuracy but low test accuracy.' },
      { q: 'Which algorithm is best described as: "find K groups of similar data points"?', opts: ['Linear Regression', 'K-Nearest Neighbors', 'K-Means Clustering', 'Logistic Regression'], ans: 2, exp: 'K-Means Clustering is an unsupervised algorithm that partitions data into K groups (clusters) based on similarity. K-Nearest Neighbors (KNN) is a classification algorithm — different concept.' },
      { q: 'What is the purpose of splitting data into training and test sets?', opts: ['To make the model train faster', 'To evaluate how well the model generalizes to unseen data', 'To increase the size of the dataset', 'To remove outliers from the data'], ans: 1, exp: 'The test set contains data the model has never seen. Evaluating on it measures how well the model generalizes — not just how well it memorized training data.' },
      { q: 'In a neural network, what does an "activation function" do?', opts: ['Sets the learning rate', 'Introduces non-linearity so the network can learn complex patterns', 'Determines the number of layers', 'Normalizes the input data'], ans: 1, exp: 'Activation functions (like ReLU, sigmoid) introduce non-linearity. Without them, a neural network — no matter how many layers — is mathematically equivalent to a single linear transformation.' },
    ],
  },
  {
    id: 'cs-capstone',
    name: 'CS Capstone Project',
    grade: 12, term: 'Spring', credits: 1.0,
    description: 'Your senior capstone is the centerpiece of your college application portfolio. Over one semester, you will conceive, design, build, and present a substantial software project. Past projects have included mobile apps, data analysis tools, game engines, and AI models.',
    syllabus: {
      objectives: [
        'Define a clear problem and explain why software is the right solution',
        'Design system architecture and create a project timeline',
        'Build a working software project with clean, documented code',
        'Use Git for version control with regular, meaningful commits',
        'Present the completed project to a panel including technical Q&A',
      ],
      units: [
        { week: '1–2',   topic: 'Project Ideation',          desc: 'Brainstorm, research, scope — define your problem, user, and success criteria.' },
        { week: '3',     topic: 'Architecture & Planning',   desc: 'System diagram, tech stack selection, timeline, MVP definition.' },
        { week: '4–6',   topic: 'Build Sprint 1',            desc: 'Implement core features. Weekly code reviews with instructor. Git commits daily.' },
        { week: '7',     topic: 'Mid-project Demo',          desc: 'Present MVP to peers. Collect feedback. Adjust scope if needed.' },
        { week: '8–11',  topic: 'Build Sprint 2',            desc: 'Extend features, improve UI/UX, add error handling and testing.' },
        { week: '12–13', topic: 'Polish & Documentation',    desc: 'Write README, code comments, user guide. Record demo video.' },
        { week: '14–15', topic: 'Final Presentation Prep',  desc: 'Prepare slides, practice Q&A, technical explanation of key design decisions.' },
        { week: '16',    topic: 'Capstone Demo Day',         desc: 'Present to panel. Technical Q&A. Celebrate your work.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=ysEN5RaKOlA', title: 'How to Design a System — System Design Basics', channel: 'Gaurav Sen', note: 'Watch to help plan your project architecture in Weeks 2–3.' },
      { url: 'https://docs.github.com/en/get-started', title: 'GitHub Documentation — Getting Started', channel: 'GitHub', note: 'Use GitHub for version control throughout. Keep your repo clean with regular commits.' },
      { url: 'https://www.youtube.com/watch?v=2Xa3Y4xz8_s', title: 'Writing a Great README', channel: 'Eddie Jaoude', note: 'Your documentation matters. Learn how to write a professional README.' },
      { url: 'https://www.kaggle.com/datasets', title: 'Kaggle Datasets', channel: 'Kaggle', note: 'If your project involves data analysis or ML, Kaggle has thousands of free datasets.' },
    ],
    quiz: [
      { q: 'What is an MVP in software development?', opts: ['Most Valuable Player', 'Minimum Viable Product — a basic version with core features only', 'Maximum Version Protocol', 'Main Visual Plan'], ans: 1, exp: 'MVP (Minimum Viable Product) is the simplest version of your product that delivers value. Build the MVP first, then add features.' },
      { q: 'Why is writing a README file important for a software project?', opts: ['It makes the code run faster', 'It helps others (and future you) understand what the project does and how to use it', 'It is required for the code to compile', 'It automatically generates documentation'], ans: 1, exp: 'A README is often the first thing someone reads about your project. A good README explains the purpose, setup instructions, and usage — essential for portfolio projects.' },
      { q: 'What is the purpose of making frequent, small Git commits?', opts: ['It speeds up the code', 'It creates a detailed history of changes and makes it easy to roll back specific changes', 'It automatically tests your code', 'It deploys to production'], ans: 1, exp: 'Frequent commits with clear messages create a history you can navigate. If something breaks, you can identify exactly which change caused the problem and revert to a working state.' },
    ],
  },
];

export default function CSPathway() {
  return <PathwayPage meta={META} schedule={SCHEDULE} courses={COURSES} />;
}
