import React from 'react';
import { PathwayPage } from './PathwayComponents';

const COLOR = '#1B6B3A';

const META = {
  color: COLOR,
  title: 'Economics & Finance',
  subtitle: 'Understand markets. Master money. Shape policy.',
  emoji: '📈',
  courseEmoji: '📈',
  heroDescription: 'A 4-year pathway for students drawn to economics, finance, public policy, or investment banking. You will study micro and macro economics at AP level, learn to analyze financial markets, model real data, and explore behavioral economics — the science of why people make the financial decisions they do.',
  targets: ['Economics / Applied Economics', 'Finance & Investment Banking', 'Public Policy & Government', 'Accounting & Financial Analysis', 'Actuarial Science', 'International Relations & Development'],
  collegeNote: 'Two AP Economics courses, quantitative modeling, and a senior research thesis demonstrate the exact combination of analytical rigor and intellectual curiosity that top economics programs at LSE, UChicago, and Northwestern look for. Students in this pathway consistently outperform peers in introductory college economics.',
  stats: [{ label: 'AP Courses', value: 2 }],
};

const SCHEDULE = [
  { grade: 9, term: 'Fall', courses: [
    { name: 'English I',                  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra I',                  type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology',                    type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World History',              type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Physical Education',         type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Microeconomics Foundations', type: 'pathway',   credits: 0.5, courseId: 'econ-micro' },
  ]},
  { grade: 9, term: 'Spring', courses: [
    { name: 'English I — Writing',        type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Geometry',                   type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Environmental Science',      type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Geography',                  type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Health & Wellness',          type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Personal Finance & Budgeting', type: 'pathway', credits: 0.5, courseId: 'econ-finance' },
  ]},
  { grade: 10, term: 'Fall', courses: [
    { name: 'English II',                 type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra II',                 type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Chemistry',                  type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'U.S. History',              type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Macroeconomics',            type: 'pathway',   credits: 0.5, courseId: 'econ-macro' },
    { name: 'AP Microeconomics',         type: 'supporting', credits: 1.0, dept: 'Economics', note: 'Take concurrently — strong foundation for AP exam' },
  ]},
  { grade: 10, term: 'Spring', courses: [
    { name: 'English II — Literature',    type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Pre-Calculus',              type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics Fundamentals',      type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World Politics',            type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'AP Macroeconomics',         type: 'pathway',   credits: 1.0, courseId: 'econ-apmacro' },
  ]},
  { grade: 11, term: 'Fall', courses: [
    { name: 'English III',               type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Statistics',                type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology — Advanced',        type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Financial Markets & Investing', type: 'pathway', credits: 0.5, courseId: 'econ-markets' },
    { name: 'AP Statistics',             type: 'supporting', credits: 1.0, dept: 'Mathematics', note: 'Essential for quantitative economics' },
  ]},
  { grade: 11, term: 'Spring', courses: [
    { name: 'English III — Literature',  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Trigonometry',              type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics — Mechanics',       type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'International Trade & Globalization', type: 'pathway', credits: 0.5, courseId: 'econ-trade' },
    { name: 'US & World History (AP)',   type: 'supporting', credits: 0.5, dept: 'Social Studies' },
  ]},
  { grade: 12, term: 'Fall', courses: [
    { name: 'English IV — Writing & Communication', type: 'core', credits: 1.0, dept: 'English Language Arts' },
    { name: 'Calculus',                  type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Behavioral Economics',      type: 'pathway',   credits: 1.0, courseId: 'econ-behavioral' },
    { name: 'Game Theory',               type: 'supporting', credits: 0.5, dept: 'Mathematics / Economics', note: 'College-level elective' },
  ]},
  { grade: 12, term: 'Spring', courses: [
    { name: 'English IV — Advanced Composition', type: 'core', credits: 1.0, dept: 'English Language Arts' },
    { name: 'Economics Research & Policy Analysis', type: 'pathway', credits: 1.0, courseId: 'econ-research' },
  ]},
];

const COURSES = [
  {
    id: 'econ-micro',
    name: 'Microeconomics Foundations',
    grade: 9, term: 'Fall', credits: 0.5,
    description: 'Begin your economics journey with the building blocks: how individuals and firms make decisions under scarcity. Supply, demand, markets, prices, competition, and market failures — the tools economists use to analyze everything from coffee prices to tech monopolies.',
    syllabus: {
      objectives: [
        'Apply the concept of opportunity cost to individual and firm decisions',
        'Draw and interpret supply and demand diagrams',
        'Explain how price controls and taxes affect market outcomes',
        'Identify different market structures (perfect competition, monopoly)',
        'Explain sources of market failure and potential government responses',
      ],
      units: [
        { week: '1–2',   topic: 'Scarcity & Opportunity Cost', desc: 'Why economics exists. The production possibilities curve. Comparative advantage.' },
        { week: '3–4',   topic: 'Supply & Demand',            desc: 'Law of demand/supply, determinants, equilibrium, shifts vs. movements.' },
        { week: '5–6',   topic: 'Elasticity',                 desc: 'Price elasticity of demand, income elasticity, cross-price elasticity — why it matters for business.' },
        { week: '7–8',   topic: 'Consumer Theory',            desc: 'Utility, marginal utility, consumer surplus, budget constraints.' },
        { week: '9–10',  topic: 'Production & Costs',         desc: 'Fixed vs. variable costs, marginal cost, average cost, economies of scale.' },
        { week: '11–12', topic: 'Market Structures',          desc: 'Perfect competition, monopoly, oligopoly, monopolistic competition — how structure affects price and profit.' },
        { week: '13',    topic: 'Market Failures',            desc: 'Externalities, public goods, information asymmetry, government intervention rationale.' },
        { week: '14–16', topic: 'Economic Analysis Project',  desc: 'Apply microeconomic concepts to analyze a real market of your choice (e.g., Uber, streaming, sneakers).' },
      ],
    },
    resources: [
      { url: 'https://www.khanacademy.org/economics-finance-domain/ap-microeconomics', title: 'AP Microeconomics — Full Course', channel: 'Khan Academy', note: 'Complete microeconomics curriculum with interactive exercises. Work through every unit.' },
      { url: 'https://www.youtube.com/watch?v=aaukVfOqMCk', title: 'Microeconomics — Crash Course', channel: 'Crash Course', note: 'Watch episodes 1–10 of Crash Course Economics for the core microeconomics topics.' },
      { url: 'https://www.youtube.com/watch?v=u7xnIXeXMSk', title: 'Supply and Demand — Full Explanation', channel: 'Jacob Clifford (ACDC Economics)', note: 'The best single teacher for AP Economics on YouTube. Watch his supply and demand series.' },
      { url: 'https://www.youtube.com/watch?v=mUDOQ8DWNUQ', title: 'Market Failures Explained', channel: 'Marginal Revolution University', note: 'Clear video explanations of externalities and market failure from top economists.' },
    ],
    quiz: [
      { q: 'You decide to spend Saturday studying instead of working your part-time job. The opportunity cost of studying is:', opts: ['The cost of your textbooks', 'The wages you would have earned at work', 'Zero, because studying is free', 'The time you spent at work last week'], ans: 1, exp: 'Opportunity cost is the value of the next best alternative you give up. Since your alternative was working, the opportunity cost is the wages you forfeited.' },
      { q: 'When demand for a product increases and supply stays the same, what happens?', opts: ['Price falls, quantity falls', 'Price rises, quantity rises', 'Price falls, quantity rises', 'Price rises, quantity falls'], ans: 1, exp: 'Increased demand shifts the demand curve right. At the old price, there\'s now excess demand (shortage). This bids up the price until a new, higher equilibrium is reached — both price and quantity increase.' },
      { q: 'A product has a price elasticity of demand of -2.0. If the price rises 10%, quantity demanded will:', opts: ['Fall by 10%', 'Fall by 20%', 'Rise by 20%', 'Fall by 2%'], ans: 1, exp: 'PED = % change in Qd / % change in Price. So -2.0 = % change in Qd / 10%. Quantity demanded falls by 20%. A PED of -2.0 means demand is elastic (|PED| > 1).' },
      { q: 'What is a "negative externality"?', opts: ['A company that loses money', 'A cost imposed on a third party not involved in the transaction', 'A government tax on businesses', 'A product that no one wants to buy'], ans: 1, exp: 'A negative externality is a cost to parties not involved in the transaction. Example: a factory polluting a river imposes costs on downstream communities who did not participate in the factory\'s production decisions.' },
    ],
  },
  {
    id: 'econ-finance',
    name: 'Personal Finance & Budgeting',
    grade: 9, term: 'Spring', credits: 0.5,
    description: 'The financial skills most high school students never learn — and wish they had. Income, taxes, banking, credit, insurance, investing, and retirement planning. By the end of this course, you will have a personal budget, understand compound interest, and know how to start investing.',
    syllabus: {
      objectives: [
        'Create and maintain a realistic personal budget using income and expenses',
        'Explain how compound interest works and calculate future values',
        'Understand how credit scores work and why they matter',
        'Compare investment options: savings accounts, stocks, bonds, index funds',
        'Design a basic long-term savings and investment plan',
      ],
      units: [
        { week: '1–2',   topic: 'Income & Taxes',             desc: 'Gross vs. net income, paycheck deductions, FICA, W-2 and W-4 forms, filing basics.' },
        { week: '3–4',   topic: 'Budgeting',                  desc: '50/30/20 rule, fixed vs. variable expenses, tracking spending, budget apps.' },
        { week: '5–6',   topic: 'Banking & Saving',           desc: 'Checking vs. savings accounts, interest rates, compound interest, emergency funds.' },
        { week: '7–8',   topic: 'Credit & Debt',              desc: 'Credit scores, how credit cards work, APR, avoiding debt traps, student loans.' },
        { week: '9–10',  topic: 'Investing Basics',           desc: 'Stocks, bonds, mutual funds, ETFs, risk vs. return, diversification.' },
        { week: '11–12', topic: 'Retirement Planning',        desc: '401(k), IRA, compound growth over time, why starting early matters enormously.' },
        { week: '13',    topic: 'Insurance',                  desc: 'Health, car, renter\'s, life insurance — what they cover and how to choose.' },
        { week: '14–16', topic: 'Personal Financial Plan',    desc: 'Build a complete personal financial plan: budget, savings goal, debt plan, investment allocation.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=FXy_rnAVBLg', title: 'Personal Finance for Beginners', channel: 'Graham Stephan', note: 'Popular personal finance YouTuber covering budgeting and investing basics.' },
      { url: 'https://www.khanacademy.org/college-careers-more/personal-finance', title: 'Personal Finance — Khan Academy', channel: 'Khan Academy', note: 'Complete personal finance curriculum with exercises on budgeting, credit, and investing.' },
      { url: 'https://www.youtube.com/watch?v=b-pMFBVJKJ4', title: 'Compound Interest Explained', channel: '3Blue1Brown / Khan Academy', note: 'Visual explanation of how compound interest grows wealth over time.' },
      { url: 'https://www.youtube.com/watch?v=gFQNPmLKj1k', title: 'How to Invest as a Teenager / Young Adult', channel: 'Andrei Jikh', note: 'Practical investing guide for beginners — use for Weeks 9–12.' },
    ],
    quiz: [
      { q: 'You invest $1,000 at 8% annual interest, compounded annually. After 3 years, you have approximately:', opts: ['$1,240', '$1,260', '$1,080', '$1,000'], ans: 1, exp: 'Compound interest: $1,000 × (1.08)³ = $1,000 × 1.2597 ≈ $1,260. Compounding means you earn interest on your interest, accelerating growth over time.' },
      { q: 'What does a credit score primarily measure?', opts: ['How much money you have in the bank', 'Your likelihood of repaying debt based on your credit history', 'Your annual income', 'How many credit cards you own'], ans: 1, exp: 'A credit score (300–850) predicts your likelihood of repaying debt. Higher scores mean better terms on loans. Key factors: payment history (35%), amounts owed (30%), length of credit history (15%), new credit (10%), credit mix (10%).' },
      { q: 'An index fund is best described as:', opts: ['A fund managed by a top investor who picks stocks', 'A fund that tracks a market index like the S&P 500, offering broad diversification at low cost', 'A bank savings account with higher interest', 'A type of government bond'], ans: 1, exp: 'Index funds track a market index (like the S&P 500) and hold all or most of its constituent stocks. They offer instant diversification and typically have very low fees — making them one of the most recommended investments for long-term wealth building.' },
      { q: 'The 50/30/20 budgeting rule allocates income as:', opts: ['50% savings, 30% wants, 20% needs', '50% needs, 30% wants, 20% savings/debt', '50% investments, 30% needs, 20% entertainment', '50% wants, 30% savings, 20% needs'], ans: 1, exp: '50% of after-tax income goes to needs (rent, food, bills), 30% to wants (dining, entertainment, hobbies), and 20% to savings and debt repayment. It\'s a simple, flexible framework — not a rigid rule.' },
    ],
  },
  {
    id: 'econ-macro',
    name: 'Macroeconomics',
    grade: 10, term: 'Fall', credits: 0.5,
    description: 'Zoom out from individual markets to the entire economy. GDP, unemployment, inflation, business cycles, and central banking. Understand why recessions happen, how governments respond, and what the Fed does when the economy slows down. A required foundation before AP Macroeconomics.',
    syllabus: {
      objectives: [
        'Calculate GDP using the expenditure approach and interpret the result',
        'Explain the causes and types of unemployment and inflation',
        'Describe the phases of the business cycle and their indicators',
        'Explain how commercial banks create money through lending',
        'Analyze a government\'s policy response to a recession or inflationary period',
      ],
      units: [
        { week: '1–2',   topic: 'Measuring Economic Output',  desc: 'GDP calculation, real vs. nominal, limitations of GDP as a welfare measure.' },
        { week: '3–4',   topic: 'Unemployment',               desc: 'Frictional, structural, cyclical unemployment. Natural rate. Labor force participation.' },
        { week: '5–6',   topic: 'Inflation',                  desc: 'CPI calculation, causes of inflation (demand-pull vs. cost-push), hyperinflation case studies.' },
        { week: '7–8',   topic: 'Business Cycles',            desc: 'Expansion, peak, contraction, trough. Leading vs. lagging indicators.' },
        { week: '9–10',  topic: 'Banking & Money Creation',   desc: 'Fractional reserve banking, money multiplier, how lending creates money.' },
        { week: '11–12', topic: 'The Federal Reserve',        desc: 'Structure of the Fed, tools of monetary policy, open market operations, discount rate.' },
        { week: '13',    topic: 'Fiscal Policy',              desc: 'Government spending and taxation, automatic stabilizers, the multiplier effect.' },
        { week: '14–16', topic: 'Economic Policy Analysis',   desc: 'Evaluate a real recession (2008, 2020) — what happened, what policies were used, did they work?' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=PHe0bXAIuk0', title: 'How the Economic Machine Works — Ray Dalio', channel: 'Ray Dalio / Bridgewater', note: 'The most-watched economics explainer ever. Watch this first — 30 minutes that will change how you see the world.' },
      { url: 'https://www.youtube.com/watch?v=d8uTB5XorBw', title: 'Macroeconomics — Crash Course', channel: 'Crash Course', note: 'Episodes 19–30 cover the macro topics. Clear and entertaining.' },
      { url: 'https://www.khanacademy.org/economics-finance-domain/ap-macroeconomics', title: 'AP Macroeconomics — Khan Academy', channel: 'Khan Academy', note: 'Use for practice exercises on each topic. Highly interactive.' },
      { url: 'https://www.youtube.com/watch?v=6sNmJtoKDCo', title: 'The 2008 Financial Crisis Explained', channel: 'CNBC', note: 'A clear account of what caused the Great Recession — use for the Week 14–16 case study.' },
    ],
    quiz: [
      { q: 'Which formula correctly calculates GDP using the expenditure approach?', opts: ['GDP = C + G + I + NX', 'GDP = Wages + Profits + Rent + Interest', 'GDP = Total Output × Price Level', 'GDP = C + S + T'], ans: 0, exp: 'GDP = C (Consumption) + I (Investment) + G (Government spending) + NX (Net exports = exports minus imports). This is the most common GDP calculation method.' },
      { q: 'Structural unemployment is caused by:', opts: ['People between jobs searching for new ones', 'A mismatch between workers\' skills and available jobs (often due to technology or industry shifts)', 'An economic recession reducing overall demand for labor', 'Workers choosing to leave the labor force temporarily'], ans: 1, exp: 'Structural unemployment arises when the skills workers have don\'t match the skills employers need — often because of technological change or industry decline. It requires retraining, unlike frictional unemployment which is temporary.' },
      { q: 'If the Federal Reserve wants to reduce inflation, it would most likely:', opts: ['Lower the federal funds rate', 'Buy government securities (bonds)', 'Raise the federal funds rate', 'Print more money'], ans: 2, exp: 'To reduce inflation, the Fed raises interest rates (contractionary monetary policy). Higher rates increase borrowing costs, reduce spending, and cool demand — putting downward pressure on prices.' },
      { q: 'What is the "money multiplier"?', opts: ['The rate at which inflation erodes purchasing power', '1 / reserve requirement — how many times a dollar deposited can be multiplied through bank lending', 'The amount of money the Fed prints each year', 'The ratio of government debt to GDP'], ans: 1, exp: 'With a 10% reserve requirement, banks keep $1 and lend $9 of every $10 deposited. That $9 gets redeposited, $8.10 gets lent again, and so on. The money multiplier = 1/0.10 = 10 — meaning $1 deposited can create up to $10 in money supply.' },
    ],
  },
  {
    id: 'econ-apmacro',
    name: 'AP Macroeconomics',
    grade: 10, term: 'Spring', credits: 1.0,
    description: 'College-level macroeconomics with AP exam preparation. This course goes deeper than the introductory macro course — covering the full AD-AS model, the Phillips Curve, loanable funds market, foreign exchange markets, and complex policy analysis. Aim for a 4 or 5 on the AP exam.',
    syllabus: {
      objectives: [
        'Use the AD-AS model to analyze economic shocks and policy responses',
        'Explain the short-run and long-run Phillips Curve tradeoff',
        'Analyze the loanable funds market and how it determines real interest rates',
        'Interpret foreign exchange market graphs and explain their effects on trade',
        'Write thorough AP free-response answers that include labeled graphs',
      ],
      units: [
        { week: '1–3',   topic: 'Basic Economic Concepts',    desc: 'PPC, comparative advantage, circular flow, economic measurements — quick review plus deeper analysis.' },
        { week: '4–5',   topic: 'National Income',            desc: 'Expenditure and income approaches to GDP. GDP deflator. Real vs. nominal output.' },
        { week: '6–7',   topic: 'AD-AS Model',               desc: 'Aggregate demand, SRAS, LRAS. Demand and supply shocks. Self-correcting mechanism.' },
        { week: '8–9',   topic: 'Fiscal Policy',              desc: 'Discretionary vs. automatic. Multiplier effect. Crowding out. Debt considerations.' },
        { week: '10',    topic: 'Financial Sector',           desc: 'Money demand/supply, loanable funds market, nominal vs. real interest rates.' },
        { week: '11',    topic: 'Monetary Policy',            desc: 'Tools of the Fed, open market operations, money creation, expansionary vs. contractionary.' },
        { week: '12',    topic: 'Phillips Curve',             desc: 'Short-run and long-run Phillips Curve. Stagflation. Rational expectations.' },
        { week: '13',    topic: 'International Economics',    desc: 'Balance of payments, exchange rates, foreign exchange market, current account.' },
        { week: '14–16', topic: 'AP Exam Preparation',        desc: 'Past AP free-response questions, multiple-choice drills, graph practice, timed simulations.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=6_mfAOSaFEo', title: 'AP Macroeconomics Full Review', channel: 'Heimler\'s History', note: 'Watch Heimler\'s entire AP Macro playlist — it is the gold standard for AP exam prep.' },
      { url: 'https://www.khanacademy.org/economics-finance-domain/ap-macroeconomics', title: 'AP Macroeconomics', channel: 'Khan Academy', note: 'Complete AP Macro with exercises for every unit. Use the progress checks to prepare.' },
      { url: 'https://www.youtube.com/c/ACDCLeadership', title: 'AP Economics — Jacob Clifford (ACDC Economics)', channel: 'ACDC Economics', note: 'Excellent AP Economics teacher. His AP Macro playlist covers every topic with practice problems.' },
      { url: 'https://apclassroom.collegeboard.org/', title: 'AP Classroom — Official Resources', channel: 'College Board', note: 'Official AP Macro progress checks, daily videos, and released FRQs. Essential for exam prep.' },
    ],
    quiz: [
      { q: 'In the AD-AS model, a decrease in consumer confidence would most directly cause:', opts: ['SRAS to shift left', 'AD to shift right', 'AD to shift left', 'LRAS to shift right'], ans: 2, exp: 'Consumer confidence affects consumption (C), which is the largest component of AD. Lower confidence → less spending → AD shifts left → lower output and lower price level in the short run.' },
      { q: 'The short-run Phillips Curve shows a tradeoff between:', opts: ['Inflation and GDP growth', 'Unemployment and inflation', 'Interest rates and investment', 'Exchange rates and exports'], ans: 1, exp: 'The short-run Phillips Curve shows an inverse relationship between unemployment and inflation. Lower unemployment is associated with higher inflation and vice versa — in the short run.' },
      { q: 'In the loanable funds market, an increase in the government budget deficit will:', opts: ['Increase the supply of loanable funds', 'Decrease the real interest rate', 'Crowd out private investment by increasing the real interest rate', 'Shift demand for loanable funds left'], ans: 2, exp: 'Government borrowing to fund a deficit increases demand for loanable funds, raising the real interest rate. This higher rate discourages private borrowing and investment — the "crowding out" effect.' },
      { q: 'If a country\'s currency appreciates, what is the MOST likely effect on its exports?', opts: ['Exports increase because domestic goods are cheaper', 'Exports decrease because domestic goods are more expensive for foreign buyers', 'No effect on exports', 'Exports increase because of higher domestic income'], ans: 1, exp: 'When a currency appreciates, it takes more foreign currency to buy the same domestic goods. Foreign buyers pay more for exports, reducing quantity demanded. Exports fall, and imports increase (as foreign goods become relatively cheaper).' },
    ],
  },
  {
    id: 'econ-markets',
    name: 'Financial Markets & Investing',
    grade: 11, term: 'Fall', credits: 0.5,
    description: 'How do stock markets, bond markets, and financial systems actually work? This course takes you from how companies raise capital to how investors analyze stocks, what drives interest rates, and how financial crises unfold. You will manage a simulated investment portfolio throughout the course.',
    syllabus: {
      objectives: [
        'Explain how companies raise capital through stocks and bonds',
        'Read and interpret basic financial statements (income statement, balance sheet)',
        'Apply fundamental analysis to evaluate a company\'s stock',
        'Explain how central bank policy affects financial markets',
        'Manage a simulated portfolio and justify investment decisions with analysis',
      ],
      units: [
        { week: '1–2',   topic: 'Financial System Overview',  desc: 'Role of financial markets, types of financial institutions, how capital flows in the economy.' },
        { week: '3–4',   topic: 'Stock Markets',              desc: 'How stocks work, IPOs, stock exchanges, market indices (S&P 500, Dow, Nasdaq).' },
        { week: '5–6',   topic: 'Bond Markets',               desc: 'How bonds work, yield, duration, relationship between bond prices and interest rates.' },
        { week: '7–8',   topic: 'Financial Statements',       desc: 'Reading income statements and balance sheets, key ratios (P/E, ROE, debt/equity).' },
        { week: '9–10',  topic: 'Fundamental Analysis',       desc: 'Valuing a company, DCF basics, comparing to competitors, reading analyst reports.' },
        { week: '11',    topic: 'Monetary Policy & Markets',  desc: 'How Fed rate decisions affect stocks, bonds, and the broader economy.' },
        { week: '12–13', topic: 'Financial Crises',           desc: 'Case study: 2008 crisis — subprime mortgages, CDOs, systemic risk, Lehman Brothers.' },
        { week: '14–16', topic: 'Portfolio Project',          desc: 'Present your simulated portfolio: investment thesis for each holding, performance analysis, lessons learned.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=p7HKvqRI_Bo', title: 'How the Stock Market Works', channel: 'Plain Bagel', note: 'Excellent explainer of how stock markets actually function — watch in Week 3–4.' },
      { url: 'https://www.youtube.com/watch?v=7O0YQCSaeG8', title: 'How to Read a Balance Sheet', channel: 'Accounting Stuff', note: 'Clear and approachable introduction to financial statements.' },
      { url: 'https://www.youtube.com/watch?v=ZCFkWDdmXG8', title: 'Warren Buffett: How to Analyze a Business', channel: 'CNBC / Berkshire', note: 'Fundamental analysis principles from the world\'s most famous investor.' },
      { url: 'https://www.youtube.com/watch?v=3-pCVlZEMBk', title: 'The 2008 Financial Crisis Explained', channel: 'Investopedia', note: 'Step-by-step explanation of what caused the crisis — use for Week 12–13.' },
    ],
    quiz: [
      { q: 'When a company issues new shares in an "IPO," what is happening?', opts: ['The company is buying back existing shares', 'The company is selling ownership stakes to the public for the first time to raise capital', 'The company is paying dividends', 'The company is splitting existing shares'], ans: 1, exp: 'An IPO (Initial Public Offering) is when a private company first sells shares to the public. The company receives the proceeds and uses them for growth. After the IPO, shares trade on an exchange.' },
      { q: 'If interest rates rise, what typically happens to existing bond prices?', opts: ['Bond prices rise', 'Bond prices fall', 'Bond prices are unaffected', 'Bond prices become zero'], ans: 1, exp: 'There is an inverse relationship between interest rates and bond prices. When rates rise, new bonds pay higher yields, making existing lower-yield bonds less attractive — their prices fall.' },
      { q: 'The P/E (Price-to-Earnings) ratio measures:', opts: ['A company\'s total debt', 'How much investors are willing to pay per dollar of the company\'s earnings', 'The company\'s profit margin', 'The company\'s annual revenue'], ans: 1, exp: 'P/E = Stock Price / Earnings Per Share. A P/E of 20 means investors pay $20 for every $1 of earnings. Higher P/E suggests investors expect strong future growth; lower P/E may indicate undervaluation or a mature/declining business.' },
    ],
  },
  {
    id: 'econ-trade',
    name: 'International Trade & Globalization',
    grade: 11, term: 'Spring', credits: 0.5,
    description: 'Why do countries trade? Who benefits — and who loses — from globalization? This course examines comparative advantage, trade policy (tariffs, quotas, subsidies), foreign exchange markets, multinational corporations, global supply chains, and the economic debates around free trade vs. protectionism.',
    syllabus: {
      objectives: [
        'Apply the comparative advantage theory to explain the basis of trade',
        'Analyze how tariffs and quotas affect consumers, producers, and government revenue',
        'Explain how exchange rates are determined and what causes them to change',
        'Evaluate arguments for and against free trade with evidence',
        'Analyze a current global trade issue using economic reasoning',
      ],
      units: [
        { week: '1–2',   topic: 'Why Countries Trade',        desc: 'Absolute vs. comparative advantage, terms of trade, the gains from trade.' },
        { week: '3–4',   topic: 'Trade Policy',               desc: 'Tariffs, quotas, subsidies — how they work, who benefits, who loses.' },
        { week: '5–6',   topic: 'Free Trade vs. Protectionism', desc: 'Arguments for and against each side. WTO, trade agreements, trade wars.' },
        { week: '7–8',   topic: 'Foreign Exchange Markets',   desc: 'How currency exchange works, supply and demand for currencies, fixed vs. floating rates.' },
        { week: '9–10',  topic: 'Balance of Payments',        desc: 'Current account, capital account, trade surplus vs. deficit.' },
        { week: '11–12', topic: 'Globalization & Multinationals', desc: 'Global supply chains, FDI, offshoring — economic and social effects.' },
        { week: '13',    topic: 'Emerging Markets',           desc: 'China, India, Southeast Asia — economic development models, growth drivers.' },
        { week: '14–16', topic: 'Trade Policy Analysis',      desc: 'Research and argue a position on a current trade dispute (e.g., US-China tariffs, digital trade). Debate format.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=rcW9SFGasUE', title: 'Comparative Advantage — Explained', channel: 'Marginal Revolution University', note: 'Tyler Cowen and Alex Tabarrok (top economists) explain comparative advantage clearly.' },
      { url: 'https://www.youtube.com/watch?v=7Qco5oSyxCU', title: 'Trade Policy — Tariffs and Quotas', channel: 'ACDC Economics', note: 'Visual explanation of how trade policies affect welfare — good for Week 3–4.' },
      { url: 'https://www.youtube.com/watch?v=9qKoaQzl7EE', title: 'Globalization Explained', channel: 'Kurzgesagt', note: 'Visual explainer on globalization and its economic effects.' },
      { url: 'https://www.youtube.com/watch?v=JHRnqJJ0rhc', title: 'China\'s Economy Explained', channel: 'CNBC', note: 'Use for the Emerging Markets unit — how China\'s economic model works.' },
    ],
    quiz: [
      { q: 'Country A can produce both wheat and cloth more efficiently than Country B. According to comparative advantage, trade:', opts: ['Only benefits Country A', 'Can still benefit both countries if each specializes in what it produces at lower opportunity cost', 'Should not occur since Country A is more efficient at everything', 'Only benefits the country with more natural resources'], ans: 1, exp: 'Comparative advantage, not absolute advantage, drives trade. Even if Country A is better at everything, trade is beneficial if each country specializes in production where their opportunity cost is relatively lower.' },
      { q: 'A tariff on imported steel MOST directly benefits:', opts: ['Domestic consumers of steel', 'Foreign steel producers', 'Domestic steel producers', 'All industries that use steel as input'], ans: 2, exp: 'A tariff raises the price of imported steel, reducing competition for domestic producers and allowing them to charge higher prices. Consumers and steel-using industries (like auto makers) are harmed by higher costs.' },
      { q: 'If the US dollar strengthens against the Chinese yuan, what happens to US exports to China?', opts: ['US exports become cheaper for Chinese buyers and increase', 'US exports become more expensive for Chinese buyers and decrease', 'No change in exports', 'US exports are priced in yuan, so there is no effect'], ans: 1, exp: 'A stronger dollar means Chinese buyers need to spend more yuan to buy the same US goods. US exports become more expensive, reducing demand from China. This is why a strong dollar tends to harm US export industries.' },
    ],
  },
  {
    id: 'econ-behavioral',
    name: 'Behavioral Economics',
    grade: 12, term: 'Fall', credits: 1.0,
    description: 'Classical economics assumes people are rational. They are not. Behavioral economics — the field that earned three Nobel Prizes — explores how psychology, emotion, and cognitive biases shape real economic decisions. From Kahneman and Tversky\'s prospect theory to Thaler\'s nudge theory, this is one of the most fascinating courses in the pathway.',
    syllabus: {
      objectives: [
        'Explain the key cognitive biases documented in behavioral economics research',
        'Describe prospect theory and how loss aversion differs from rational utility theory',
        'Apply the concept of "nudges" to design interventions that improve decisions',
        'Analyze financial market phenomena (bubbles, crashes) through a behavioral lens',
        'Design and report on an original behavioral economics mini-experiment',
      ],
      units: [
        { week: '1–2',   topic: 'Rational vs. Real Humans',   desc: 'The homo economicus assumption. Heuristics and biases. Kahneman\'s System 1 vs. System 2 thinking.' },
        { week: '3–4',   topic: 'Cognitive Biases',           desc: 'Anchoring, availability heuristic, confirmation bias, representativeness, overconfidence.' },
        { week: '5–6',   topic: 'Prospect Theory',            desc: 'Kahneman & Tversky. Loss aversion. How people value gains vs. losses asymmetrically.' },
        { week: '7–8',   topic: 'Intertemporal Choice',       desc: 'Present bias, hyperbolic discounting, procrastination — why we choose smaller-sooner over larger-later.' },
        { week: '9–10',  topic: 'Social Preferences',         desc: 'Fairness, reciprocity, altruism, social norms — how we care about others\' outcomes.' },
        { week: '11–12', topic: 'Nudge Theory',               desc: 'Thaler and Sunstein. Choice architecture. Default effects. Real-world nudge programs.' },
        { week: '13',    topic: 'Behavioral Finance',         desc: 'Market bubbles (tulip mania, dot-com, 2008), herd behavior, investor psychology.' },
        { week: '14–16', topic: 'Behavioral Experiment',      desc: 'Design, run, and report on a simple behavioral economics experiment. Present findings with analysis.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=vBX-KulgJ1o', title: 'Thinking Fast and Slow — Daniel Kahneman', channel: 'Talks at Google', note: 'The Nobel laureate explaining his work in person. Watch at the start of the course.' },
      { url: 'https://www.youtube.com/watch?v=u6XAPnuFjJc', title: 'Are We In Control of Our Own Decisions?', channel: 'TED / Dan Ariely', note: 'Classic TED talk on irrational behavior by the author of Predictably Irrational. Watch Week 1.' },
      { url: 'https://www.youtube.com/watch?v=fMnmRBsC22A', title: 'Nudge Theory Explained', channel: 'The School of Life', note: 'Short, clear explanation of Thaler\'s nudge concept with examples — use for Week 11–12.' },
      { url: 'https://www.youtube.com/watch?v=3hG4X5iTNDM', title: 'Loss Aversion and Prospect Theory', channel: 'Behavioral Economics in Action', note: 'Visual explanation of the core concepts in Weeks 5–6.' },
    ],
    quiz: [
      { q: 'According to behavioral economics, "loss aversion" means:', opts: ['People prefer to lose money rather than win it', 'People feel the pain of a loss about twice as strongly as the pleasure of an equal gain', 'People avoid all financial risk', 'People make rational decisions to minimize losses'], ans: 1, exp: 'Kahneman and Tversky showed that losing $100 feels roughly twice as bad as gaining $100 feels good. This asymmetry — loss aversion — leads to irrational decisions like holding losing investments too long.' },
      { q: 'The "anchoring" bias describes:', opts: ['The tendency to follow what everyone else is doing', 'Over-relying on the first piece of information encountered when making a decision', 'Preferring the current state of affairs', 'Making decisions based on vivid recent memories'], ans: 1, exp: 'Anchoring means initial information (even irrelevant information) influences subsequent judgments. A $500 price feels cheap after seeing a $2,000 anchor; the same $500 feels expensive after seeing a $200 anchor.' },
      { q: 'A "nudge" in Thaler and Sunstein\'s framework is:', opts: ['A government mandate that forces specific behavior', 'A choice architecture change that predictably alters behavior while preserving freedom of choice', 'A financial incentive to change behavior', 'A tax on harmful behavior'], ans: 1, exp: 'A nudge changes the environment to make beneficial choices easier or more likely — without removing options or coercing. Examples: opt-out default enrollment in pension plans, placing healthy food at eye level in cafeterias.' },
      { q: 'Kahneman\'s "System 1" thinking is best described as:', opts: ['Slow, analytical, deliberate reasoning', 'Fast, automatic, intuitive processing that operates below conscious awareness', 'The part of the brain that controls emotion', 'Rational economic decision-making'], ans: 1, exp: 'System 1 is fast, automatic, and requires little effort — it handles routine decisions using heuristics. System 2 is slow and deliberate. Most of our daily decisions are System 1, which is where cognitive biases originate.' },
    ],
  },
  {
    id: 'econ-research',
    name: 'Economics Research & Policy Analysis',
    grade: 12, term: 'Spring', credits: 1.0,
    description: 'Your senior capstone is an original economics research paper — the kind of work that appears in your college application and demonstrates intellectual rigor. Choose a real-world policy question, review the literature, develop a hypothesis, analyze data, and write a structured research report with policy recommendations.',
    syllabus: {
      objectives: [
        'Formulate a clear, researchable economic policy question',
        'Review and summarize academic and policy literature on a topic',
        'Analyze quantitative data using basic statistical methods',
        'Write a structured economics research paper (introduction, literature review, analysis, conclusion)',
        'Present findings and defend recommendations in a formal Q&A',
      ],
      units: [
        { week: '1–2',   topic: 'Research Design',            desc: 'Choosing a question, reviewing existing research, formulating a hypothesis.' },
        { week: '3–4',   topic: 'Literature Review',          desc: 'Finding academic sources, reading and summarizing papers, identifying research gaps.' },
        { week: '5–6',   topic: 'Data Sources & Collection',  desc: 'World Bank, FRED, Census data — how economists get data. Dataset selection.' },
        { week: '7–8',   topic: 'Data Analysis',              desc: 'Descriptive statistics, correlation analysis, visualizing economic data with charts.' },
        { week: '9–10',  topic: 'Policy Analysis Frameworks', desc: 'Cost-benefit analysis, equity vs. efficiency tradeoffs, evaluating policy alternatives.' },
        { week: '11–12', topic: 'Writing the Paper',          desc: 'Structure, academic tone, citations (APA), argument construction, tables and graphs.' },
        { week: '13–14', topic: 'Revision & Peer Review',     desc: 'Peer feedback sessions, instructor review, revisions for clarity and rigor.' },
        { week: '15–16', topic: 'Research Presentation',      desc: 'Present paper to a panel. Defend methodology and recommendations. Q&A.' },
      ],
    },
    resources: [
      { url: 'https://fred.stlouisfed.org/', title: 'FRED Economic Data — Federal Reserve Bank of St. Louis', channel: 'Federal Reserve', note: 'Free database of hundreds of thousands of economic indicators — the primary data source for this course.' },
      { url: 'https://data.worldbank.org/', title: 'World Bank Open Data', channel: 'World Bank', note: 'Comprehensive global development and economic data — use for international topics.' },
      { url: 'https://www.youtube.com/watch?v=t-DB2PcrHdk', title: 'How to Read an Economics Paper', channel: 'Marginal Revolution University', note: 'Practical guide to reading academic economics papers — watch in Weeks 3–4.' },
      { url: 'https://www.youtube.com/watch?v=8sB0GBOaF2M', title: 'Introduction to Cost-Benefit Analysis', channel: 'MIT OpenCourseWare', note: 'Understanding the core framework for evaluating policy interventions.' },
    ],
    quiz: [
      { q: 'In a research paper, what is the purpose of the literature review section?', opts: ['To prove your hypothesis', 'To summarize and critically evaluate existing research on the topic, showing how your paper fits into the field', 'To list all the books you read', 'To describe your data collection method'], ans: 1, exp: 'A literature review synthesizes existing research, identifies what is known, what is debated, and where gaps exist. It demonstrates scholarly context and justifies why your research question matters.' },
      { q: 'In cost-benefit analysis, a policy is generally considered worthwhile when:', opts: ['The government supports it', 'Total benefits to society exceed total costs to society', 'Benefits to the private sector exceed all costs', 'Costs to producers are zero'], ans: 1, exp: 'CBA compares the total social benefits of a policy against its total social costs. When net benefits (benefits minus costs) are positive, the policy improves overall social welfare, though distributional effects must also be considered.' },
      { q: 'FRED (Federal Reserve Economic Data) is primarily used for:', opts: ['Filing tax returns', 'Accessing and visualizing real economic data for research and analysis', 'Reading academic journals', 'Getting stock market information'], ans: 1, exp: 'FRED is the Federal Reserve Bank of St. Louis\'s free database of over 800,000 economic time series. It\'s one of the most-used data sources by economists, journalists, and researchers for analyzing economic trends.' },
    ],
  },
];

export default function EconomicsPathway({ language, toggleLanguage }) {
  return <PathwayPage meta={META} schedule={SCHEDULE} courses={COURSES} language={language} toggleLanguage={toggleLanguage} />;
}
