import React from 'react';
import { PathwayPage } from './PathwayComponents';

const COLOR = '#B71C1C'; // dark red

const META = {
  color: COLOR,
  title: 'Engineering Science',
  subtitle: 'Design, build, and solve the world\'s hardest problems.',
  emoji: '⚙️',
  courseEmoji: '⚙️',
  heroDescription: 'A rigorous 4-year pathway for students targeting top engineering programs at universities like MIT, Stanford, Georgia Tech, and Purdue. From physics and design principles through thermodynamics and structural analysis, you will graduate with AP Physics credit, an engineering design portfolio, and the analytical foundation that engineering schools demand.',
  targets: ['Mechanical Engineering', 'Electrical Engineering', 'Civil & Structural Engineering', 'Aerospace Engineering', 'Chemical Engineering', 'Biomedical Engineering'],
  collegeNote: 'US engineering schools evaluate applicants on math depth (Calculus is essential), science breadth, and evidence of hands-on problem-solving. AP Physics is a major differentiator. This pathway is designed to signal rigorous STEM preparation and genuine engineering curiosity to competitive admissions committees.',
  stats: [{ label: 'AP Courses', value: 1 }],
};

const SCHEDULE = [
  { grade: 9, term: 'Fall', courses: [
    { name: 'English I',                        type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra I',                        type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology',                          type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'World History',                    type: 'core',       credits: 0.5, dept: 'Social Studies' },
    { name: 'Physical Education',               type: 'core',       credits: 0.5, dept: 'Health & PE' },
    { name: 'Introduction to Engineering Design', type: 'pathway',  credits: 0.5, courseId: 'eng-design' },
  ]},
  { grade: 9, term: 'Spring', courses: [
    { name: 'English I — Writing',              type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Geometry',                         type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Environmental Science',            type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'Geography',                        type: 'core',       credits: 0.5, dept: 'Social Studies' },
    { name: 'Health & Wellness',                type: 'core',       credits: 0.5, dept: 'Health & PE' },
    { name: 'Engineering Materials & Manufacturing', type: 'pathway', credits: 0.5, courseId: 'eng-materials' },
  ]},
  { grade: 10, term: 'Fall', courses: [
    { name: 'English II',                       type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra II',                       type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Chemistry',                        type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'U.S. History',                    type: 'core',       credits: 0.5, dept: 'Social Studies' },
    { name: 'Statics & Structural Analysis',    type: 'pathway',    credits: 0.5, courseId: 'eng-statics' },
    { name: 'Discrete Mathematics',             type: 'supporting', credits: 0.5, dept: 'Mathematics' },
  ]},
  { grade: 10, term: 'Spring', courses: [
    { name: 'English II — Literature',          type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Pre-Calculus',                     type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics Fundamentals',             type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'World Politics',                   type: 'core',       credits: 0.5, dept: 'Social Studies' },
    { name: 'Circuits & Electrical Systems',    type: 'pathway',    credits: 0.5, courseId: 'eng-circuits' },
  ]},
  { grade: 11, term: 'Fall', courses: [
    { name: 'English III',                      type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Statistics',                       type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology — Advanced',               type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'AP Physics 1',                     type: 'pathway',    credits: 1.0, courseId: 'eng-apphysics' },
  ]},
  { grade: 11, term: 'Spring', courses: [
    { name: 'English III — Literature',         type: 'core',       credits: 1.0, dept: 'English Language Arts' },
    { name: 'Trigonometry',                     type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics — Mechanics',              type: 'core',       credits: 1.0, dept: 'Science' },
    { name: 'Thermodynamics & Fluid Mechanics', type: 'pathway',    credits: 0.5, courseId: 'eng-thermo' },
    { name: 'AP Statistics',                    type: 'supporting', credits: 1.0, dept: 'Mathematics', note: 'Strongly recommended' },
  ]},
  { grade: 12, term: 'Fall', courses: [
    { name: 'English IV — Writing & Communication', type: 'core',   credits: 1.0, dept: 'English Language Arts' },
    { name: 'Calculus',                         type: 'core',       credits: 1.0, dept: 'Mathematics' },
    { name: 'CAD & Engineering Software',       type: 'pathway',    credits: 0.5, courseId: 'eng-cad' },
    { name: 'Linear Algebra',                   type: 'supporting', credits: 0.5, dept: 'Mathematics', note: 'College-level prep' },
  ]},
  { grade: 12, term: 'Spring', courses: [
    { name: 'English IV — Advanced Composition', type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Engineering Capstone Project',     type: 'pathway',    credits: 1.0, courseId: 'eng-capstone' },
  ]},
];

const COURSES = [
  {
    id: 'eng-design',
    name: 'Introduction to Engineering Design',
    grade: 9, term: 'Fall', credits: 0.5,
    description: 'Discover how engineers transform a problem into a solution. This course introduces the engineering design process — from identifying needs and brainstorming concepts through prototyping, testing, and iterating — using hands-on challenges that build spatial reasoning and creative problem-solving. Students learn to document their designs professionally using engineering sketches and technical drawings, establishing habits that carry through every subsequent engineering course.',
    syllabus: {
      objectives: [
        'Apply the complete engineering design process to an open-ended design challenge',
        'Produce annotated freehand engineering sketches and orthographic projections',
        'Define and measure problem constraints and success criteria quantitatively',
        'Test a prototype, collect data, and use results to drive design revisions',
        'Communicate design decisions clearly in a written engineering journal',
      ],
      units: [
        { week: '1–2',   topic: 'What Is Engineering?',           desc: 'Overview of engineering disciplines, famous structures and systems, and how engineers are different from scientists.' },
        { week: '3–4',   topic: 'The Engineering Design Process', desc: 'Define, research, brainstorm, prototype, test, evaluate, redesign — applied to a simple challenge.' },
        { week: '5–6',   topic: 'Engineering Sketching',          desc: 'Freehand isometric and orthographic drawing, dimensioning, section views, and annotation standards.' },
        { week: '7–8',   topic: 'Constraints & Criteria',         desc: 'Identifying design constraints (budget, material, size), writing measurable success criteria, and using decision matrices.' },
        { week: '9–10',  topic: 'Materials & Forces',             desc: 'Introduction to material properties (strength, flexibility, density) and how forces (tension, compression) affect structures.' },
        { week: '11–12', topic: 'Prototyping & Testing',          desc: 'Building physical and digital prototypes, defining test procedures, recording quantitative results.' },
        { week: '13',    topic: 'Iteration & Redesign',           desc: 'Using test data to identify failure modes and make targeted design improvements.' },
        { week: '14–16', topic: 'Design Challenge & Presentation', desc: 'Teams complete a full design cycle for a real-world prompt and present their solution, data, and reflections.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=IFa7pEbkKPs', title: 'The Engineering Design Process — Crash Course Engineering', channel: 'CrashCourse', note: 'Clear 12-minute overview of the design process — watch in Week 1 before the first challenge.' },
      { url: 'https://www.khanacademy.org/college-careers-more/career-content/career-content-whats-it-like-to-be/engineers', title: 'What Do Engineers Do? — Career Exploration', channel: 'Khan Academy', note: 'Short videos featuring real engineers from different disciplines — great for Week 1 career mapping.' },
      { url: 'https://www.youtube.com/c/PracticalEngineeringChannel', title: 'Practical Engineering — YouTube Channel', channel: 'Practical Engineering', note: 'Grady Hillhouse explains real engineering concepts and infrastructure with physical demonstrations — watch throughout the course.' },
      { url: 'https://ocw.mit.edu/courses/res-2-006-girls-who-build-cameras-summer-2016/', title: 'MIT OCW — Introduction to Design Thinking', channel: 'MIT OpenCourseWare', note: 'Free MIT resource showing design-thinking methodology applied to engineering projects.' },
    ],
    quiz: [
      { q: 'Which step in the engineering design process comes AFTER testing a prototype?', opts: ['Define the problem', 'Brainstorm solutions', 'Evaluate results and iterate', 'Select materials'], ans: 2, exp: 'After testing, engineers analyze results against the success criteria and use that data to improve the design — the evaluate-and-redesign step. The process is intentionally iterative, not linear.' },
      { q: 'A bridge must hold 10 kg, cost under $5 in materials, and span 30 cm. These requirements are best described as:', opts: ['Design objectives', 'Constraints and criteria', 'Test procedures', 'Material properties'], ans: 1, exp: 'Specific, measurable limits on weight capacity, cost, and span are constraints (limits) and criteria (targets). Distinguishing them from vague objectives is a core engineering skill.' },
      { q: 'In an orthographic projection drawing, how many standard views are typically shown?', opts: ['1', '2', '3', '6'], ans: 2, exp: 'A standard orthographic projection shows three views: front, top, and right side. Together they fully define a 3-D object in 2-D, which is the basis of all engineering technical drawings.' },
      { q: 'When a rope is pulled from both ends, the internal force it experiences is called:', opts: ['Compression', 'Torsion', 'Tension', 'Shear'], ans: 2, exp: 'Tension is a pulling or stretching force. Compression is a pushing or squishing force. Understanding the difference is fundamental to structural design.' },
      { q: 'Why do engineers use a decision matrix when evaluating design concepts?', opts: ['To calculate the cost of materials', 'To objectively compare options against weighted criteria', 'To draw technical sketches', 'To write the project report'], ans: 1, exp: 'A decision matrix assigns scores to each concept based on how well it meets each criterion (weighted by importance), providing a systematic, less-biased way to select the best concept.' },
    ],
  },
  {
    id: 'eng-materials',
    name: 'Engineering Materials & Manufacturing',
    grade: 9, term: 'Spring', credits: 0.5,
    description: 'Every engineered object is made of something — and the choice of material determines whether a design succeeds or fails. This course surveys metals, polymers, ceramics, and composites through the lens of their mechanical, thermal, and chemical properties, and connects those properties to real manufacturing processes like casting, machining, welding, and additive manufacturing. Students learn to read material data sheets, select materials for given applications, and understand how manufacturing constraints shape design decisions.',
    syllabus: {
      objectives: [
        'Compare the mechanical properties of metals, polymers, ceramics, and composites using quantitative data',
        'Interpret a stress-strain curve and identify yield strength, tensile strength, and fracture point',
        'Match a material to an application based on required properties and constraints',
        'Describe at least five major manufacturing processes and when each is appropriate',
        'Analyze a real product failure and identify the material or manufacturing root cause',
      ],
      units: [
        { week: '1–2',   topic: 'Material Categories Overview',   desc: 'Metals, polymers, ceramics, composites, semiconductors — structure determines properties.' },
        { week: '3–4',   topic: 'Mechanical Properties',          desc: 'Stress, strain, elasticity, plasticity, hardness, toughness, fatigue — reading a stress-strain curve.' },
        { week: '5–6',   topic: 'Metals & Alloys',                desc: 'Steel, aluminum, titanium, copper alloys — heat treatment, corrosion, and common engineering uses.' },
        { week: '7–8',   topic: 'Polymers & Composites',          desc: 'Thermoplastics vs. thermosets, carbon fiber reinforced polymer (CFRP), fiberglass — lightweight structure applications.' },
        { week: '9–10',  topic: 'Manufacturing Processes',        desc: 'Casting, forging, machining (turning, milling), injection molding, welding — process capabilities and tolerances.' },
        { week: '11–12', topic: 'Additive Manufacturing',         desc: 'FDM, SLA, SLS 3-D printing — layer-by-layer construction, design for additive manufacturing (DfAM).' },
        { week: '13',    topic: 'Material Selection Case Studies', desc: 'Aircraft fuselage, bicycle frame, hip implant — multi-criteria selection using CES EduPack logic.' },
        { week: '14–16', topic: 'Failure Analysis Project',       desc: 'Research a real engineering failure (e.g., Tacoma Narrows, Space Shuttle Challenger), identify the material or manufacturing cause, and present findings.' },
      ],
    },
    resources: [
      { url: 'https://ocw.mit.edu/courses/3-091sc-introduction-to-solid-state-chemistry-fall-2010/', title: 'MIT OCW 3.091 — Introduction to Solid State Chemistry', channel: 'MIT OpenCourseWare', note: 'Free MIT course covering atomic structure and bonding that underpins material properties — Lectures 1–12 are most relevant.' },
      { url: 'https://www.youtube.com/watch?v=BHZALtqAjeM', title: 'Stress and Strain — Mechanical Engineering Basics', channel: 'The Engineering Mindset', note: 'Clear visual explanation of the stress-strain curve — watch before Week 4.' },
      { url: 'https://www.youtube.com/c/TheEngineeringMindset', title: 'The Engineering Mindset — YouTube Channel', channel: 'The Engineering Mindset', note: 'Covers manufacturing processes, materials, and mechanical systems with excellent diagrams throughout the course.' },
      { url: 'https://www.youtube.com/watch?v=6XMpnrBKFCw', title: 'How 3D Printing Works — Explained', channel: 'Practical Engineering', note: 'In-depth look at additive manufacturing technology — ideal for the additive manufacturing unit.' },
    ],
    quiz: [
      { q: 'On a stress-strain curve, the yield strength is the point at which:', opts: ['The material breaks', 'The material begins to deform permanently (plastically)', 'The material returns to its original shape', 'Stress and strain are no longer proportional'], ans: 1, exp: 'Below yield strength, a material deforms elastically and returns to its original shape. Above it, permanent plastic deformation occurs. Engineers design structures to stay below this point.' },
      { q: 'Carbon fiber reinforced polymer (CFRP) is classified as a:', opts: ['Metal alloy', 'Ceramic', 'Composite material', 'Thermoplastic'], ans: 2, exp: 'CFRP is a composite — carbon fibers (high stiffness) embedded in a polymer matrix (lightweight, binds fibers). Composites combine properties of two or more materials to exceed what either can achieve alone.' },
      { q: 'Which manufacturing process is most suitable for producing thousands of identical complex plastic parts at low cost per unit?', opts: ['CNC Machining', 'Injection Molding', 'Sand Casting', 'FDM 3-D Printing'], ans: 1, exp: 'Injection molding has high tooling cost but very low per-unit cost at volume. It produces complex plastic shapes with tight tolerances — ideal for mass production.' },
      { q: 'A material that deforms significantly before fracturing (like soft steel) is described as:', opts: ['Brittle', 'Ductile', 'Hard', 'Elastic'], ans: 1, exp: 'Ductile materials undergo significant plastic deformation before fracture, absorbing energy (toughness). Brittle materials (like glass or ceramics) fracture with little deformation. Ductility is critical in structures that must not fail suddenly.' },
      { q: 'Aluminum is preferred over steel for aircraft fuselage panels primarily because:', opts: ['It is stronger than steel', 'It has a significantly higher strength-to-weight ratio', 'It melts at a higher temperature', 'It is cheaper than steel'], ans: 1, exp: 'Aluminum alloys are much lighter than steel (density ~2.7 vs. 7.8 g/cm³) while still providing adequate strength. The high specific strength (strength per unit weight) reduces aircraft mass and fuel consumption.' },
    ],
  },
  {
    id: 'eng-statics',
    name: 'Statics & Structural Analysis',
    grade: 10, term: 'Fall', credits: 0.5,
    description: 'Statics is the mathematical foundation of all structural and mechanical engineering — the study of forces and moments acting on bodies in equilibrium. Students apply vector mathematics and free-body diagrams to analyze trusses, beams, and frames, developing the analytical skills that underpin every structural design from bridges to buildings. By the end of the course, students can determine internal forces, identify failure modes, and verify whether a structure is safe under a given loading condition.',
    syllabus: {
      objectives: [
        'Resolve forces into components and apply equilibrium equations in 2-D and 3-D',
        'Draw accurate free-body diagrams for particles, beams, and truss members',
        'Calculate reactions at supports for beams under distributed and point loads',
        'Determine internal forces in all members of a simple truss using the method of joints',
        'Identify tension and compression members and explain their implications for structural design',
      ],
      units: [
        { week: '1–2',   topic: 'Forces & Vectors',               desc: 'Scalars vs. vectors, vector addition (graphical and component), force components in 2-D and 3-D.' },
        { week: '3–4',   topic: 'Equilibrium of a Particle',       desc: 'Conditions for static equilibrium (ΣF=0), free-body diagrams for concurrent force systems.' },
        { week: '5–6',   topic: 'Moments & Couples',               desc: 'Moment of a force about a point, the moment equation (ΣM=0), couples and equivalent force-couple systems.' },
        { week: '7–8',   topic: 'Equilibrium of Rigid Bodies',     desc: 'Support reactions (pin, roller, fixed), free-body diagrams for beams and frames, solving for unknowns.' },
        { week: '9–10',  topic: 'Truss Analysis — Method of Joints', desc: 'Identifying zero-force members, applying joint equilibrium to find member forces, tension vs. compression.' },
        { week: '11–12', topic: 'Beam Shear & Bending Moment',     desc: 'Shear force and bending moment diagrams, distributed loads, identifying critical cross-sections.' },
        { week: '13',    topic: 'Friction',                        desc: 'Coulomb friction, coefficient of friction, impending motion, wedge and screw problems.' },
        { week: '14–16', topic: 'Bridge Analysis Project',         desc: 'Analyze a real truss bridge design: calculate all member forces, identify the critical member, and present safety assessment.' },
      ],
    },
    resources: [
      { url: 'https://ocw.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/', title: 'MIT OCW 2.001 — Mechanics and Materials I', channel: 'MIT OpenCourseWare', note: 'Free MIT undergraduate statics and mechanics course — lecture notes and problem sets directly support this course.' },
      { url: 'https://www.youtube.com/watch?v=SKolB8YKP_A', title: 'Statics — Introduction, Free Body Diagrams', channel: 'The Organic Chemistry Tutor', note: 'Step-by-step worked examples of free-body diagrams and equilibrium — ideal for Weeks 3–6.' },
      { url: 'https://www.youtube.com/watch?v=1e-rHPvkBDM', title: 'Method of Joints — Truss Analysis', channel: 'The Organic Chemistry Tutor', note: 'Detailed walkthrough of truss analysis by method of joints — watch in Week 9.' },
      { url: 'https://www.youtube.com/c/PracticalEngineeringChannel', title: 'Practical Engineering — Bridge & Structures Playlist', channel: 'Practical Engineering', note: 'Real-world applications of statics concepts: how bridges, retaining walls, and dams resist forces.' },
    ],
    quiz: [
      { q: 'For a body in static equilibrium, which conditions must be satisfied?', opts: ['ΣF = 0 only', 'ΣM = 0 only', 'Both ΣF = 0 and ΣM = 0', 'ΣF = ma and ΣM = Iα'], ans: 2, exp: 'Static equilibrium requires that the sum of all forces AND the sum of all moments about any point both equal zero. Satisfying only one condition is insufficient.' },
      { q: 'A simply supported beam carries a single concentrated load at midspan. The support reactions at each end are:', opts: ['Each equal to the full load', 'Each equal to half the load', 'Zero at one end and the full load at the other', 'Cannot be determined without more information'], ans: 1, exp: 'By symmetry and equilibrium (ΣF=0 and ΣM=0), each support carries exactly half the applied load. This is one of the simplest and most important beam problems.' },
      { q: 'In a planar truss, a member under compression experiences:', opts: ['A pulling force along its axis — it is being stretched', 'A pushing force along its axis — it is being squeezed', 'A bending moment about its midpoint', 'No internal force'], ans: 1, exp: 'Compression members are pushed inward from both ends (squeezed). They are at risk of buckling rather than yielding. Tension members are pulled outward (stretched) and may yield.' },
      { q: 'The moment of a 100 N force applied perpendicular to the end of a 2 m wrench arm is:', opts: ['50 N·m', '100 N·m', '200 N·m', '0 N·m'], ans: 2, exp: 'Moment = Force × perpendicular distance = 100 N × 2 m = 200 N·m. A force applied perpendicular to the moment arm produces the maximum possible moment.' },
      { q: 'A zero-force member in a truss:', opts: ['Carries the largest load in the truss', 'Carries no internal force under the given loading, but may still serve a structural purpose', 'Is always found at the supports', 'Indicates the truss is incorrectly designed'], ans: 1, exp: 'Zero-force members carry no load under the current loading condition, but they prevent buckling of adjacent members under different loads and maintain the truss geometry. They are identified quickly using inspection rules.' },
    ],
  },
  {
    id: 'eng-circuits',
    name: 'Circuits & Electrical Systems',
    grade: 10, term: 'Spring', credits: 0.5,
    description: 'Electrical systems power everything from smartphones to power grids, and understanding them is essential for any engineer. This course builds from charge, voltage, and current through Ohm\'s Law, Kirchhoff\'s laws, and circuit analysis techniques, then extends to capacitors, inductors, and introductory AC circuits. Students apply concepts through hands-on virtual labs (Falstad circuit simulator) and connect theory to real-world devices, preparing for AP Physics and any electrical engineering coursework ahead.',
    syllabus: {
      objectives: [
        'Apply Ohm\'s Law and Kirchhoff\'s Voltage and Current Laws to solve DC circuits',
        'Calculate equivalent resistance for series, parallel, and combination circuits',
        'Analyze circuits using the node-voltage and mesh-current methods',
        'Explain the behavior of capacitors and inductors in DC and basic AC circuits',
        'Design a simple circuit meeting a specified voltage, current, or power requirement',
      ],
      units: [
        { week: '1–2',   topic: 'Charge, Voltage & Current',      desc: 'Atomic model of charge, electric potential, current direction convention, power and energy.' },
        { week: '3–4',   topic: 'Resistance & Ohm\'s Law',        desc: 'Resistivity, Ohm\'s Law (V=IR), series resistors, parallel resistors, voltage and current dividers.' },
        { week: '5–6',   topic: 'Kirchhoff\'s Laws',              desc: 'KVL (loop law) and KCL (node law) — systematic circuit equation setup and solution.' },
        { week: '7–8',   topic: 'Circuit Analysis Techniques',    desc: 'Node-voltage method, mesh-current method, superposition, Thévenin and Norton equivalents.' },
        { week: '9–10',  topic: 'Capacitors',                     desc: 'Charge storage, capacitance, RC circuits, time constant, charging and discharging behavior.' },
        { week: '11–12', topic: 'Inductors & Magnetic Fields',    desc: 'Faraday\'s law, inductance, RL circuits, energy storage, transformer basics.' },
        { week: '13',    topic: 'Introduction to AC Circuits',    desc: 'Sinusoidal sources, phasor notation, impedance, resonance — qualitative understanding.' },
        { week: '14–16', topic: 'Circuit Design Project',         desc: 'Design and simulate a functional circuit (LED driver, voltage regulator, or sensor interface) using Falstad and present the analysis.' },
      ],
    },
    resources: [
      { url: 'https://www.khanacademy.org/science/electrical-engineering', title: 'Electrical Engineering — Full Unit', channel: 'Khan Academy', note: 'Complete Khan Academy EE section covering circuit analysis, Kirchhoff\'s laws, capacitors, and inductors with interactive practice.' },
      { url: 'https://falstad.com/circuit/', title: 'Circuit Simulator Applet', channel: 'Falstad', note: 'Free, browser-based circuit simulator — use this for every lab in the course to build and test circuits without hardware.' },
      { url: 'https://www.youtube.com/c/TheEngineeringMindset', title: 'The Engineering Mindset — Electrical Engineering Playlist', channel: 'The Engineering Mindset', note: 'Visual tutorials on voltage, current, resistance, capacitors, and AC circuits — aligned with course units.' },
      { url: 'https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/', title: 'MIT OCW 6.002 — Circuits and Electronics', channel: 'MIT OpenCourseWare', note: 'MIT\'s undergraduate circuits course, free online — video lectures provide rigorous treatment of every topic in this course.' },
    ],
    quiz: [
      { q: 'Three 6 Ω resistors are connected in parallel. What is the equivalent resistance?', opts: ['18 Ω', '6 Ω', '2 Ω', '3 Ω'], ans: 2, exp: '1/R_eq = 1/6 + 1/6 + 1/6 = 3/6 = 1/2, so R_eq = 2 Ω. Parallel resistors always reduce equivalent resistance below the smallest individual resistor.' },
      { q: 'Kirchhoff\'s Current Law (KCL) states that at any node in a circuit:', opts: ['Voltage must equal zero', 'The sum of currents entering equals the sum of currents leaving', 'Current is constant throughout the loop', 'Resistance increases with the number of branches'], ans: 1, exp: 'KCL is a statement of charge conservation: charge cannot accumulate at a node, so all current flowing in must flow out. ΣI_in = ΣI_out at every node.' },
      { q: 'A capacitor in a DC circuit after a long time (fully charged) behaves like:', opts: ['A short circuit (wire)', 'An open circuit (no current flows)', 'A resistor of fixed value', 'An AC voltage source'], ans: 1, exp: 'Once fully charged, no current flows through a capacitor in a DC circuit — it acts as an open circuit. This is because dV/dt = 0 when voltage is constant, and I = C·dV/dt = 0.' },
      { q: 'If a resistor dissipates 48 W with 4 A flowing through it, what is its resistance?', opts: ['3 Ω', '12 Ω', '0.75 Ω', '192 Ω'], ans: 0, exp: 'P = I²R → R = P/I² = 48/16 = 3 Ω. The power dissipated in a resistor can be calculated as P = I²R, P = V²/R, or P = VI — knowing any two of voltage, current, and resistance lets you find the third.' },
      { q: 'The time constant τ of an RC circuit determines:', opts: ['The maximum voltage the capacitor can hold', 'How quickly the capacitor charges or discharges (63% charged after 1τ)', 'The frequency of oscillation', 'The total resistance in the circuit'], ans: 1, exp: 'τ = RC. After one time constant, the capacitor has charged to ~63% of its final voltage (or discharged to ~37%). After 5τ the circuit is essentially at steady state. τ governs the speed of transient response.' },
    ],
  },
  {
    id: 'eng-apphysics',
    name: 'AP Physics 1',
    grade: 11, term: 'Fall', credits: 1.0,
    description: 'AP Physics 1 is the single most important course for aspiring engineers — it provides the mathematical and conceptual framework for mechanics, energy, waves, and electrical phenomena that underpins every engineering discipline. Covering kinematics, Newton\'s laws, work and energy, rotational motion, oscillations, and waves at a college-algebra level, this course prepares students for the AP exam in May and for university-level physics and engineering courses. A score of 4 or 5 on AP Physics 1 is one of the strongest signals engineering admissions committees look for.',
    syllabus: {
      objectives: [
        'Solve kinematics problems in 1-D and 2-D using equations of motion and graphical analysis',
        'Apply Newton\'s three laws to predict the motion of objects in static and dynamic situations',
        'Use the work-energy theorem and conservation of energy to solve mechanical problems',
        'Analyze linear and angular momentum, including collision scenarios',
        'Demonstrate understanding of waves, sound, and simple harmonic motion through quantitative problems',
      ],
      units: [
        { week: '1–3',   topic: 'Kinematics',                     desc: 'Displacement, velocity, acceleration; constant-acceleration equations; projectile motion; position-time and velocity-time graphs.' },
        { week: '4–6',   topic: 'Newton\'s Laws of Motion',       desc: 'Force, mass, inertia; Newton\'s 1st, 2nd, 3rd laws; free-body diagrams; friction; circular motion and centripetal force.' },
        { week: '7–8',   topic: 'Work, Energy & Power',           desc: 'Work by constant and variable forces, kinetic and potential energy, conservation of mechanical energy, power.' },
        { week: '9',     topic: 'Linear Momentum & Collisions',   desc: 'Impulse-momentum theorem, conservation of momentum, elastic and inelastic collisions, center of mass.' },
        { week: '10–11', topic: 'Rotational Motion',              desc: 'Torque, angular kinematics, moment of inertia, angular momentum, rolling without slipping.' },
        { week: '12',    topic: 'Simple Harmonic Motion',         desc: 'Period and frequency, mass-spring system, simple pendulum, energy in SHM.' },
        { week: '13',    topic: 'Waves & Sound',                  desc: 'Wave properties, standing waves, resonance, Doppler effect.' },
        { week: '14–16', topic: 'AP Exam Preparation',            desc: 'Free-response practice, timed multiple-choice drills, laboratory investigations, and comprehensive review.' },
      ],
    },
    resources: [
      { url: 'https://apclassroom.collegeboard.org/', title: 'AP Classroom — Official AP Physics 1 Resources', channel: 'College Board', note: 'Official AP Daily video lessons, progress checks, and released FRQs. Use from Day 1 of the course.' },
      { url: 'https://www.khanacademy.org/science/ap-physics-1', title: 'AP Physics 1 — Khan Academy', channel: 'Khan Academy', note: 'Complete AP Physics 1 curriculum with videos and practice aligned to the AP exam units.' },
      { url: 'https://www.youtube.com/c/flippingphysics', title: 'Flipping Physics — AP Physics 1 Playlist', channel: 'Flipping Physics', note: 'Every AP Physics 1 topic taught with clear worked examples and multiple-choice strategies — the best free AP Physics channel.' },
      { url: 'https://phet.colorado.edu/en/simulations/filter?subjects=physics', title: 'PhET Interactive Simulations — Physics', channel: 'University of Colorado Boulder', note: 'Free, research-based physics simulations for projectile motion, forces, energy, waves, and more — use for every unit\'s lab component.' },
    ],
    quiz: [
      { q: 'A ball is thrown horizontally from a cliff at 20 m/s. Ignoring air resistance, what is its horizontal velocity after 3 seconds?', opts: ['0 m/s', '20 m/s', '29.4 m/s', '49.4 m/s'], ans: 1, exp: 'In projectile motion, the horizontal component of velocity is constant (no horizontal force). The ball maintains 20 m/s horizontally for the entire flight.' },
      { q: 'Newton\'s Third Law states that when Object A exerts a force on Object B:', opts: ['Object B exerts a smaller force back on A', 'Object B exerts an equal and opposite force on A', 'Object A stops exerting the force', 'The net force on the system is doubled'], ans: 1, exp: 'Newton\'s Third Law: forces always come in equal-magnitude, opposite-direction pairs acting on different objects. The reaction force acts on A, so it does not cancel the action force on B.' },
      { q: 'A 2 kg block slides down a frictionless ramp from a height of 5 m. Using conservation of energy, what is its speed at the bottom? (g = 10 m/s²)', opts: ['5 m/s', '10 m/s', '50 m/s', '100 m/s'], ans: 1, exp: 'mgh = ½mv² → v = √(2gh) = √(2 × 10 × 5) = √100 = 10 m/s. Mass cancels, so speed depends only on height.' },
      { q: 'In a perfectly inelastic collision between a 3 kg cart at 4 m/s and a stationary 1 kg cart, what is the final velocity of the combined system?', opts: ['4 m/s', '3 m/s', '1 m/s', '2 m/s'], ans: 1, exp: 'Conservation of momentum: p_i = (3 kg)(4 m/s) = 12 kg·m/s. p_f = (3+1)v_f. So v_f = 12/4 = 3 m/s. In a perfectly inelastic collision, objects stick together and kinetic energy is not conserved.' },
      { q: 'The period of a simple pendulum depends on:', opts: ['The mass of the bob and the length of the string', 'The length of the string and gravitational acceleration only', 'The amplitude of swing and the mass of the bob', 'The mass and the amplitude of swing'], ans: 1, exp: 'T = 2π√(L/g). For small angles, the period of a simple pendulum depends only on length and g — not mass or amplitude. This is a classic and frequently tested AP Physics result.' },
    ],
  },
  {
    id: 'eng-thermo',
    name: 'Thermodynamics & Fluid Mechanics',
    grade: 11, term: 'Spring', credits: 0.5,
    description: 'Thermodynamics and fluid mechanics govern how energy flows and how fluids behave under pressure and flow — knowledge essential for mechanical, chemical, civil, and aerospace engineers. This course covers the laws of thermodynamics, heat transfer mechanisms, and fluid statics and dynamics, with engineering applications ranging from internal combustion engines and HVAC systems to pipe flow and aerodynamics. Students work through quantitative problems and case studies connecting theory to designed systems they will encounter in university engineering courses.',
    syllabus: {
      objectives: [
        'Apply the First and Second Laws of Thermodynamics to engineering systems and cycles',
        'Calculate heat transfer by conduction, convection, and radiation',
        'Solve fluid statics problems including hydrostatic pressure and buoyancy',
        'Apply the continuity equation and Bernoulli\'s equation to pipe and channel flow',
        'Analyze the thermal efficiency of an ideal heat engine using the Carnot cycle',
      ],
      units: [
        { week: '1–2',   topic: 'Thermal Properties & Temperature', desc: 'Temperature scales, thermal equilibrium, specific heat, heat capacity, phase changes and latent heat.' },
        { week: '3–4',   topic: 'First Law of Thermodynamics',     desc: 'Internal energy, work, heat, energy conservation; open vs. closed systems; enthalpy.' },
        { week: '5–6',   topic: 'Second Law & Entropy',            desc: 'Heat engines, Carnot cycle, thermal efficiency, entropy as disorder and irreversibility.' },
        { week: '7–8',   topic: 'Heat Transfer',                   desc: 'Fourier\'s law of conduction, Newton\'s law of cooling (convection), Stefan-Boltzmann radiation law, thermal resistance networks.' },
        { week: '9–10',  topic: 'Fluid Statics',                   desc: 'Pressure variation with depth, Pascal\'s law, hydrostatic forces on submerged surfaces, buoyancy and Archimedes\' principle.' },
        { week: '11–12', topic: 'Fluid Dynamics',                  desc: 'Continuity equation (mass conservation), Bernoulli\'s equation, applications: Venturi meter, Pitot tube, lift.' },
        { week: '13',    topic: 'Viscosity & Pipe Flow',           desc: 'Reynolds number, laminar vs. turbulent flow, Poiseuille\'s law, head loss in pipes.' },
        { week: '14–16', topic: 'Engineering Application Project', desc: 'Analyze a thermal or fluid system (e.g., car radiator, dam spillway, heat pump) — calculate performance metrics and propose an efficiency improvement.' },
      ],
    },
    resources: [
      { url: 'https://ocw.mit.edu/courses/2-005-thermal-fluids-engineering-i-spring-2021/', title: 'MIT OCW 2.005 — Thermal-Fluids Engineering I', channel: 'MIT OpenCourseWare', note: 'MIT\'s free thermodynamics and fluids course — notes and problem sets directly support this course.' },
      { url: 'https://www.youtube.com/watch?v=Xb05CaG7TsQ', title: 'Thermodynamics — Full College Course', channel: 'freeCodeCamp / Chad Nickell', note: 'Complete undergraduate thermodynamics course covering all topics from the First Law through heat engines.' },
      { url: 'https://www.youtube.com/c/PracticalEngineeringChannel', title: 'Practical Engineering — Fluid Mechanics & Infrastructure', channel: 'Practical Engineering', note: 'Videos on real-world hydraulics, dams, and pipe systems — excellent companion to the fluid mechanics units.' },
      { url: 'https://www.khanacademy.org/science/physics/fluids', title: 'Fluids — Khan Academy Physics', channel: 'Khan Academy', note: 'Interactive coverage of fluid pressure, buoyancy, and Bernoulli\'s equation with practice problems.' },
    ],
    quiz: [
      { q: 'The First Law of Thermodynamics states that for a closed system:', opts: ['Energy cannot be created or destroyed — ΔU = Q − W', 'Heat flows spontaneously from cold to hot', 'Entropy always decreases in a natural process', 'No process can reach absolute zero'], ans: 0, exp: 'The First Law is conservation of energy applied to thermodynamic systems: the change in internal energy (ΔU) equals the heat added (Q) minus the work done by the system (W). Energy is always conserved.' },
      { q: 'The Carnot efficiency of a heat engine operating between a hot reservoir at 600 K and a cold reservoir at 300 K is:', opts: ['50%', '100%', '25%', '75%'], ans: 0, exp: 'η_Carnot = 1 − T_cold/T_hot = 1 − 300/600 = 0.50 = 50%. This is the maximum possible efficiency for any heat engine operating between these temperatures. Real engines are always less efficient.' },
      { q: 'Bernoulli\'s equation states that along a streamline in steady, incompressible flow:', opts: ['Pressure increases where velocity increases', 'The sum of pressure, kinetic, and potential energy per unit volume is constant', 'Velocity is constant everywhere', 'Temperature is constant everywhere'], ans: 1, exp: 'Bernoulli\'s equation (P + ½ρv² + ρgh = constant) expresses conservation of energy in a fluid: where velocity increases, pressure decreases, and vice versa. This is why airplane wings generate lift.' },
      { q: 'A 0.5 m³ object submerged in water (density 1000 kg/m³) experiences a buoyant force of approximately:', opts: ['500 N', '4900 N', '5000 N', '9800 N'], ans: 1, exp: 'F_b = ρ_fluid × V × g = 1000 × 0.5 × 9.8 = 4900 N. Archimedes\' principle: the buoyant force equals the weight of fluid displaced.' },
      { q: 'Fourier\'s Law of heat conduction states that the heat flux through a material is proportional to:', opts: ['The temperature at the hot surface', 'The temperature gradient (rate of change of temperature with distance)', 'The total mass of the material', 'The heat capacity of the material'], ans: 1, exp: 'q = −k(dT/dx). Heat flux is proportional to the temperature gradient — the steeper the temperature change per unit length, the higher the heat flow. The thermal conductivity k depends on the material.' },
    ],
  },
  {
    id: 'eng-cad',
    name: 'CAD & Engineering Software',
    grade: 12, term: 'Fall', credits: 0.5,
    description: 'Modern engineers design entirely in software before anything is built. This course teaches industry-standard Computer-Aided Design (CAD) using Autodesk Fusion 360 (free for students), covering 2-D drafting, 3-D solid modeling, assembly, and engineering drawings with full GD&T annotations. Students also receive an introduction to Finite Element Analysis (FEA) for stress simulation and to computer-aided manufacturing (CAM) toolpath generation, equipping them with the digital tool fluency that engineering internships and university labs expect from Day 1.',
    syllabus: {
      objectives: [
        'Create fully-constrained parametric 2-D sketches with correct geometric and dimensional constraints',
        'Build 3-D solid models using extrude, revolve, sweep, loft, fillet, and shell operations',
        'Assemble multiple components with correct mate/joint relationships in an assembly file',
        'Produce a complete engineering drawing with orthographic views, section views, and GD&T annotations',
        'Run a basic FEA stress simulation and interpret the von Mises stress contour plot',
      ],
      units: [
        { week: '1–2',   topic: 'CAD Fundamentals & Interface',   desc: 'Parametric modeling concept, Fusion 360 workspace, sketch plane selection, reference geometry.' },
        { week: '3–4',   topic: '2-D Sketching',                  desc: 'Geometric constraints (coincident, tangent, parallel), dimensional constraints, fully constrained sketches.' },
        { week: '5–6',   topic: '3-D Solid Modeling',             desc: 'Extrude, cut, revolve, fillet, chamfer, shell — building parts from sketches.' },
        { week: '7–8',   topic: 'Advanced Modeling Features',     desc: 'Sweep, loft, mirror, pattern, in-context design, surface modeling introduction.' },
        { week: '9–10',  topic: 'Assembly & Motion',              desc: 'Importing components, joints (rigid, revolute, slider), motion studies, interference checking.' },
        { week: '11–12', topic: 'Engineering Drawings & GD&T',    desc: 'Orthographic and section views, title block, dimensioning standards, GD&T symbols (flatness, perpendicularity, true position).' },
        { week: '13',    topic: 'Intro to FEA Simulation',        desc: 'Applying loads and constraints, meshing, running static stress analysis, interpreting von Mises stress and safety factor.' },
        { week: '14–16', topic: 'CAD Design Portfolio Project',   desc: 'Model, assemble, and document an original mechanical design (e.g., clamp, gear train, bracket). Submit drawing package and FEA report.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/watch?v=A5bc9c3S12g', title: 'Fusion 360 Tutorial for Absolute Beginners', channel: 'Lars Christensen', note: 'The best beginner Fusion 360 series — watch the first four episodes in Week 1 to get up to speed on the interface.' },
      { url: 'https://www.autodesk.com/education/edu-software/overview', title: 'Autodesk Education — Free Student Software', channel: 'Autodesk', note: 'Download Fusion 360 and other Autodesk tools for free with a student account — required for this course.' },
      { url: 'https://www.youtube.com/c/ProductDesignOnline', title: 'Product Design Online — Fusion 360 Tutorials', channel: 'Product Design Online', note: 'Kevin Kennedy\'s channel has the most comprehensive Fusion 360 tutorials covering every modeling operation in this course.' },
      { url: 'https://ocw.mit.edu/courses/2-007-design-and-manufacturing-i-spring-2009/', title: 'MIT OCW 2.007 — Design and Manufacturing I', channel: 'MIT OpenCourseWare', note: 'MIT\'s freshman engineering design course — see how CAD integrates into a full engineering project.' },
    ],
    quiz: [
      { q: 'In parametric CAD, a "fully constrained" sketch means:', opts: ['The sketch has the maximum number of lines possible', 'Every point in the sketch has its position uniquely defined — it cannot move freely', 'The sketch is locked and cannot be edited', 'All lines must be horizontal or vertical'], ans: 1, exp: 'A fully constrained sketch has zero degrees of freedom — every geometry is fixed by a combination of geometric (tangent, coincident) and dimensional constraints. Under-constrained sketches produce unpredictable model changes.' },
      { q: 'Which 3-D modeling operation creates a solid by rotating a 2-D profile around an axis?', opts: ['Extrude', 'Sweep', 'Revolve', 'Loft'], ans: 2, exp: 'Revolve rotates a 2-D cross-section around a specified axis to create solids of revolution — ideal for cylindrical and axisymmetric parts like shafts, valves, and bottles.' },
      { q: 'In an FEA static stress analysis, the von Mises stress contour shows:', opts: ['Temperature distribution in the part', 'A scalar measure of combined stress state — used to predict yielding in ductile materials', 'The displacement of the part under load', 'The safety factor at each point'], ans: 1, exp: 'Von Mises stress combines all stress components (normal and shear) into a single scalar. When von Mises stress exceeds the material\'s yield strength, the material is predicted to yield. It\'s the most common failure criterion for ductile metals in FEA.' },
      { q: 'GD&T (Geometric Dimensioning and Tolerancing) is used in engineering drawings to:', opts: ['Show the material a part is made from', 'Specify allowable variation in size, form, orientation, and location of features', 'Indicate the color of the finished part', 'Show the manufacturing sequence'], ans: 1, exp: 'GD&T provides precise, unambiguous specifications for how much a manufactured feature can deviate from its ideal geometry. It replaces vague ±tolerance notes with functional tolerances based on how the part actually fits and works.' },
      { q: 'In a CAD assembly, a "revolute joint" between two components allows:', opts: ['Translation along one axis only', 'Rotation about one axis only', 'Free motion in all 6 degrees of freedom', 'No motion at all'], ans: 1, exp: 'A revolute (pin) joint removes 5 degrees of freedom, leaving 1 rotational DOF about the joint axis. This models hinges, bearings, and pivot points — the most common joint type in mechanism design.' },
    ],
  },
  {
    id: 'eng-capstone',
    name: 'Engineering Capstone Project',
    grade: 12, term: 'Spring', credits: 1.0,
    description: 'The Engineering Capstone is the culmination of four years of analytical study — an original, self-directed engineering design project completed with the rigor expected at the university level. Students identify a real problem, perform structured engineering analysis (statics, thermal, electrical, or fluid — appropriate to the problem), create CAD models or circuit schematics, build a prototype or simulation, and present a professional engineering report and oral defense. The capstone is the centerpiece of the student\'s college application portfolio and demonstrates every competency engineering admissions officers seek.',
    syllabus: {
      objectives: [
        'Define an engineering problem with measurable performance requirements and constraints',
        'Conduct a structured literature review and benchmark competing solutions',
        'Apply quantitative engineering analysis (statics, thermodynamics, circuits, or fluid mechanics) to validate the design',
        'Produce a complete design package: CAD drawings, analysis report, and prototype or simulation',
        'Deliver a professional oral defense including technical Q&A with the review panel',
      ],
      units: [
        { week: '1–2',   topic: 'Problem Definition & Scope',     desc: 'Identify the problem, stakeholders, and need. Write a formal problem statement with measurable success criteria.' },
        { week: '3',     topic: 'Conceptual Design',              desc: 'Generate at least three design concepts using brainstorming and morphological analysis. Select the best using a weighted decision matrix.' },
        { week: '4–6',   topic: 'Engineering Analysis Sprint 1',  desc: 'Perform quantitative analysis to validate the chosen concept — stress calculations, circuit analysis, thermal modeling, or fluid simulation.' },
        { week: '7',     topic: 'Mid-Project Design Review',      desc: 'Present analysis results and revised design to instructor and peers. Receive and incorporate feedback.' },
        { week: '8–11',  topic: 'Detailed Design & Prototype',    desc: 'Complete CAD model or schematic; build a physical or digital prototype; conduct testing and compare to success criteria.' },
        { week: '12–13', topic: 'Analysis Refinement & Report',   desc: 'Refine design based on test data; write full engineering report (problem, analysis, design, results, conclusions).' },
        { week: '14–15', topic: 'Presentation Preparation',       desc: 'Create professional slides; practice oral defense including expected technical questions from the review panel.' },
        { week: '16',    topic: 'Final Design Defense',           desc: 'Present the complete engineering project to a panel. Answer technical questions. Receive final evaluation.' },
      ],
    },
    resources: [
      { url: 'https://ocw.mit.edu/courses/2-009-the-product-engineering-process-fall-2008/', title: 'MIT OCW 2.009 — The Product Engineering Process', channel: 'MIT OpenCourseWare', note: 'Watch MIT\'s famous senior capstone class for inspiration on how to structure a rigorous engineering design project.' },
      { url: 'https://www.youtube.com/c/PracticalEngineeringChannel', title: 'Practical Engineering — Project Documentation Standards', channel: 'Practical Engineering', note: 'Watch episodes on technical writing and how engineers document and communicate design decisions professionally.' },
      { url: 'https://www.autodesk.com/education/edu-software/overview', title: 'Autodesk Fusion 360 — Student Edition', channel: 'Autodesk', note: 'Use Fusion 360 for all CAD modeling, simulation, and engineering drawing production in the capstone.' },
      { url: 'https://engineeringdesignprocess.com/', title: 'Engineering Design Process — Reference Guide', channel: 'TeachEngineering / NSF', note: 'Structured reference for each phase of the engineering design process — use to check that your project follows professional methodology.' },
    ],
    quiz: [
      { q: 'In a formal engineering design process, what is the purpose of a design requirements document?', opts: ['To list the materials needed for the prototype', 'To specify measurable performance targets and constraints the design must satisfy', 'To describe the manufacturing process', 'To document the final test results'], ans: 1, exp: 'A design requirements document (or product design specification) translates the customer\'s needs into measurable engineering targets. Every subsequent design decision is evaluated against these requirements.' },
      { q: 'A morphological analysis chart is used in engineering design to:', opts: ['Calculate stress in structural members', 'Systematically explore design alternatives by identifying independent sub-functions and options for each', 'Select the best material for a component', 'Test the prototype against requirements'], ans: 1, exp: 'A morphological chart lists design sub-functions (e.g., power source, structure, actuation) in rows and possible solutions for each in columns. Combining one option from each row generates a complete design concept, encouraging creative exploration.' },
      { q: 'The Factor of Safety (FoS) in structural engineering is defined as:', opts: ['The ratio of actual load to designed load', 'The ratio of material strength to the applied stress — how much stronger the design is than the minimum required', 'The percentage of the budget reserved for contingency', 'The number of test cycles before failure'], ans: 1, exp: 'FoS = Strength / Applied Stress. A FoS of 2.0 means the structure is twice as strong as the minimum needed. Engineers use FoS > 1 to account for material variability, unexpected loads, and model uncertainty.' },
      { q: 'Why is a mid-project design review valuable in engineering practice?', opts: ['It replaces the need for final testing', 'It provides structured feedback before significant resources are committed to detailed design, reducing costly late-stage changes', 'It allows the team to change the problem statement', 'It is required by building codes'], ans: 1, exp: 'Early feedback (at concept or preliminary design stage) is dramatically cheaper to act on than changes after prototyping or manufacturing. Design reviews are a core professional practice in industry for exactly this reason.' },
      { q: 'When a prototype test result does not meet a success criterion, the correct engineering response is:', opts: ['Report the failure and end the project', 'Change the success criterion to match the result', 'Analyze the failure mode, identify the design change needed, and iterate', 'Build more prototypes until one passes by chance'], ans: 2, exp: 'Engineering is inherently iterative — prototypes rarely meet all requirements on the first attempt. Systematic failure analysis identifies the root cause, guides a targeted design improvement, and restarts the test cycle. This is the engineering method.' },
    ],
  },
];

export default function EngineeringPathway() {
  return <PathwayPage meta={META} schedule={SCHEDULE} courses={COURSES} />;
}
