import React from 'react';
import { PathwayPage } from './PathwayComponents';

const COLOR = '#1A237E'; // deep navy blue

const META = {
  color: COLOR,
  title: 'Political Science & International Relations',
  subtitle: 'Understand power. Shape policy. Change the world.',
  emoji: '🌐',
  courseEmoji: '🌐',
  heroDescription: 'A 4-year pathway for students interested in politics, international affairs, law, diplomacy, or public policy. From comparative government to international trade theory and geopolitical analysis, you will graduate with a strong foundation in political thought and research skills that programs at Georgetown, Columbia, George Washington, and top policy schools demand.',
  targets: ['Political Science / Government', 'International Relations & Diplomacy', 'Pre-Law / Law School Track', 'Public Policy & Administration', 'International Business', 'Global Affairs & Area Studies'],
  collegeNote: 'Political science and IR programs look for students with strong analytical writing, evidence of global curiosity, and research skills. AP Human Geography and AP Government are key differentiators. Chinese students who can articulate US-China relations, global trade, or geopolitical trends from an informed perspective stand out strongly at programs like Georgetown SFS.',
  stats: [{ label: 'AP Courses', value: 2 }],
};

const SCHEDULE = [
  { grade: 9, term: 'Fall', courses: [
    { name: 'English I',                         type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra I',                         type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology',                           type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World History',                     type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Physical Education',                type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Introduction to Political Science', type: 'pathway',   credits: 0.5, courseId: 'pol-intro' },
  ]},
  { grade: 9, term: 'Spring', courses: [
    { name: 'English I — Writing',               type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Geometry',                          type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Environmental Science',             type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Geography',                         type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Health & Wellness',                 type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Comparative Government & World Systems', type: 'pathway', credits: 0.5, courseId: 'pol-comp' },
  ]},
  { grade: 10, term: 'Fall', courses: [
    { name: 'English II',                        type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra II',                        type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Chemistry',                         type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'U.S. History',                      type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'International Relations Theory',    type: 'pathway',   credits: 0.5, courseId: 'pol-ir' },
    { name: 'Public Speaking',                   type: 'supporting', credits: 0.5, dept: 'Communication', note: 'Essential for debate and policy argumentation' },
  ]},
  { grade: 10, term: 'Spring', courses: [
    { name: 'English II — Literature',           type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Pre-Calculus',                      type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics Fundamentals',              type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World Politics',                    type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'AP Human Geography',                type: 'pathway',   credits: 1.0, courseId: 'pol-aphg' },
  ]},
  { grade: 11, term: 'Fall', courses: [
    { name: 'English III',                       type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Statistics',                        type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology — Advanced',                type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'US Government & Constitutional Law', type: 'pathway',  credits: 0.5, courseId: 'pol-uslaw' },
  ]},
  { grade: 11, term: 'Spring', courses: [
    { name: 'English III — Literature',          type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Trigonometry',                      type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics — Mechanics',               type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'AP Government & Politics: US',      type: 'pathway',   credits: 1.0, courseId: 'pol-apgov' },
    { name: 'Research Methods in Social Science', type: 'supporting', credits: 0.5, dept: 'Social Studies', note: 'Builds quantitative skills for policy analysis and the senior capstone' },
  ]},
  { grade: 12, term: 'Fall', courses: [
    { name: 'English IV — Writing & Communication', type: 'core',   credits: 1.0, dept: 'English Language Arts' },
    { name: 'Calculus',                          type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Global Economics & Trade Policy',   type: 'pathway',   credits: 0.5, courseId: 'pol-trade' },
  ]},
  { grade: 12, term: 'Spring', courses: [
    { name: 'English IV — Advanced Composition', type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Policy Research Capstone',          type: 'pathway',   credits: 1.0, courseId: 'pol-capstone' },
  ]},
];

const COURSES = [
  {
    id: 'pol-intro',
    name: 'Introduction to Political Science',
    grade: 9, term: 'Fall', credits: 0.5,
    description: 'Your entry point into the study of politics: what it is, why it matters, and how political scientists analyze power, governance, and collective decision-making. Students examine core concepts — the state, sovereignty, legitimacy, democracy, and authoritarianism — using real examples from history and current events.',
    syllabus: {
      objectives: [
        'Define key political science concepts: state, sovereignty, legitimacy, and power',
        'Distinguish between major regime types: democracy, authoritarianism, and hybrid systems',
        'Explain the social contract theory and its influence on modern governance',
        'Analyze a current political event using a political science framework',
        'Construct a structured analytical argument in a short political science essay',
      ],
      units: [
        { week: '1–2',   topic: 'What Is Politics?',             desc: 'Why political science exists. Defining power, authority, and legitimacy. Who rules and why they are obeyed.' },
        { week: '3–4',   topic: 'The State & Sovereignty',       desc: 'What is a state? Sovereignty in theory and practice. Failed states, disputed territories, and international recognition.' },
        { week: '5–6',   topic: 'Democracy: Theory & Varieties', desc: 'Direct vs. representative democracy. Liberal democracy, illiberal democracy, and the global democratic recession.' },
        { week: '7–8',   topic: 'Authoritarianism',              desc: 'Types of authoritarian regimes: military, single-party, personalist. How they maintain power and how they fall.' },
        { week: '9–10',  topic: 'Political Ideology',            desc: 'Liberalism, conservatism, socialism, nationalism — what they stand for and where they come from.' },
        { week: '11–12', topic: 'Social Contract Theories',      desc: 'Hobbes, Locke, and Rousseau. How their ideas shaped constitutions, rights, and the basis of government authority.' },
        { week: '13',    topic: 'Political Participation',       desc: 'Voting, activism, civil disobedience, and revolution as forms of political engagement.' },
        { week: '14–16', topic: 'Current Events Analysis',       desc: 'Apply course concepts to analyze one contemporary political development (e.g., an election, a protest movement, a leadership transition).' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtOfse2ncvffeelTrqvhrz8H', title: 'Crash Course Government & Politics — Full Playlist', channel: 'Crash Course', note: 'Watch episodes 1–10 for the core concepts of political science: government, democracy, and political ideology.' },
      { url: 'https://www.khanacademy.org/humanities/us-government-and-civics', title: 'US Government & Civics — Khan Academy', channel: 'Khan Academy', note: 'Interactive exercises and videos on the foundations of government. Strong for concepts in Weeks 1–6.' },
      { url: 'https://www.cfr.org/global-conflict-tracker', title: 'Global Conflict Tracker — Council on Foreign Relations', channel: 'Council on Foreign Relations', note: 'Use for the Week 14–16 current events project. Real-time maps and analysis of political crises worldwide.' },
      { url: 'https://www.youtube.com/watch?v=rStL7niR7gs', title: 'What is Democracy? — TED-Ed', channel: 'TED-Ed', note: 'Clear explainer on what democracy means and the different forms it takes. Use in Weeks 5–6.' },
    ],
    quiz: [
      { q: 'Max Weber\'s definition of the state emphasizes its monopoly on:', opts: ['Economic production', 'The legitimate use of physical force within a given territory', 'Free elections and civil rights', 'The right to declare war on other nations'], ans: 1, exp: 'Weber\'s classic definition: the state is a human community that claims the monopoly of the legitimate use of physical force within a given territory. Legitimacy is key — without it, force becomes mere coercion.' },
      { q: 'A regime that holds elections but restricts civil liberties, press freedom, and genuine political competition is best described as:', opts: ['A liberal democracy', 'A totalitarian state', 'An illiberal or hybrid democracy', 'A failed state'], ans: 2, exp: 'Hybrid or illiberal democracies use the procedural tools of democracy (elections) while undermining its substantive conditions (free press, independent judiciary, civil liberties). Hungary and Russia are often cited as examples.' },
      { q: 'John Locke argued that governments derive their legitimate authority from:', opts: ['Divine right of rulers', 'Military conquest', 'The consent of the governed and the protection of natural rights', 'Traditions and customs inherited from the past'], ans: 2, exp: 'Locke\'s social contract theory holds that people have natural rights (life, liberty, property) and that government authority is legitimate only when it protects those rights with the ongoing consent of the governed. This directly influenced the US Declaration of Independence.' },
      { q: 'Which of the following is BEST described as a form of political participation?', opts: ['Watching the news', 'Paying taxes', 'Signing a petition to change a law', 'Obeying traffic laws'], ans: 2, exp: 'Political participation involves actions intended to influence government decisions or the political process. Signing a petition is a direct form of political engagement. Watching news, paying taxes, and obeying laws are not forms of participation per se.' },
      { q: 'The concept of "sovereignty" in international relations means:', opts: ['A country\'s military strength', 'A state\'s supreme authority within its territory, free from external interference', 'The right of citizens to vote in free elections', 'A treaty obligation to assist other countries in conflict'], ans: 1, exp: 'Sovereignty is the foundational principle of the international state system established by the Peace of Westphalia (1648). It means each state has supreme authority within its own borders and no external power has the right to interfere in its internal affairs.' },
    ],
  },
  {
    id: 'pol-comp',
    name: 'Comparative Government & World Systems',
    grade: 9, term: 'Spring', credits: 0.5,
    description: 'Political scientists learn by comparing — how do different countries organize their governments, and what explains those differences? This course examines presidential vs. parliamentary systems, federal vs. unitary states, electoral systems, and the role of political culture through case studies of the US, UK, China, France, and others.',
    syllabus: {
      objectives: [
        'Compare presidential and parliamentary systems of government and their trade-offs',
        'Explain the difference between federal and unitary state structures with examples',
        'Analyze how different electoral systems produce different political outcomes',
        'Describe the key features of the Chinese political system and contrast them with liberal democracies',
        'Write a structured comparative political analysis of two countries on a chosen dimension',
      ],
      units: [
        { week: '1–2',   topic: 'Why Compare Governments?',      desc: 'The comparative method in political science. Variables, cases, and the logic of comparison.' },
        { week: '3–4',   topic: 'Presidential vs. Parliamentary', desc: 'Structure of each system, pros and cons, examples: US (presidential), UK and Germany (parliamentary), France (semi-presidential).' },
        { week: '5–6',   topic: 'Federal vs. Unitary States',    desc: 'How power is distributed vertically. US federalism, German federalism, French unitary state, China\'s administrative hierarchy.' },
        { week: '7–8',   topic: 'Electoral Systems',             desc: 'First-past-the-post vs. proportional representation vs. ranked choice. How rules shape party systems and who wins.' },
        { week: '9–10',  topic: 'Political Parties & Interest Groups', desc: 'Two-party vs. multi-party systems. How parties form, compete, and govern.' },
        { week: '11–12', topic: 'China\'s Political System',     desc: 'The Chinese Communist Party, National People\'s Congress, state structure, governance under Xi Jinping — and comparison with Western systems.' },
        { week: '13',    topic: 'Political Culture',             desc: 'How values, history, and norms shape political behavior. Collectivism vs. individualism in cross-national perspective.' },
        { week: '14–16', topic: 'Comparative Analysis Paper',    desc: 'Write a structured comparison of two countries on a dimension of your choice: e.g., how the US and Germany handle immigration policy, or how China and India approach economic governance.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtOfse2ncvffeelTrqvhrz8H', title: 'Crash Course Government & Politics — Comparative Systems', channel: 'Crash Course', note: 'Episodes on parliamentary government, electoral systems, and constitutions directly support this course.' },
      { url: 'https://www.youtube.com/watch?v=rStL7niR7gs', title: 'How China Is Ruled — Explained', channel: 'Vox', note: 'Clear visual explainer of how the Chinese Communist Party structures political power. Use for Weeks 11–12.' },
      { url: 'https://www.cfr.org/backgrounder/chinas-political-system', title: 'China\'s Political System — CFR Backgrounder', channel: 'Council on Foreign Relations', note: 'Authoritative reference on the structure of China\'s government and party system.' },
      { url: 'https://www.youtube.com/watch?v=YbpNfGYkRv0', title: 'Electoral Systems Explained — TED-Ed', channel: 'TED-Ed', note: 'Visual explanation of how different voting systems work and why the choice of system matters.' },
    ],
    quiz: [
      { q: 'In a parliamentary system, the head of government (prime minister) is:', opts: ['Elected directly by the public in a national vote', 'Appointed by a constitutional monarch', 'Drawn from the legislature and dependent on maintaining its confidence', 'Selected by the military to govern'], ans: 2, exp: 'In parliamentary systems, the prime minister is typically the leader of the party or coalition that controls the legislature. They remain in power only as long as they maintain the confidence (majority support) of parliament — unlike a president who is independently elected.' },
      { q: 'Federalism, as practiced in the United States, means:', opts: ['All power rests with the national government', 'States have no independent legal authority', 'Power is constitutionally divided between national and state governments', 'Local governments make all major policy decisions'], ans: 2, exp: 'US federalism divides sovereignty between the federal government and state governments. States have their own constitutions, legislatures, and powers — not just delegated authority from the center. This is constitutionally guaranteed by the Tenth Amendment.' },
      { q: 'Proportional representation (PR) electoral systems tend to produce:', opts: ['Stable two-party systems like the United States', 'Multi-party systems where coalition governments are common', 'Military governments due to political fragmentation', 'Winner-takes-all outcomes that amplify majorities'], ans: 1, exp: 'PR systems allocate seats based on each party\'s vote share, making it easier for smaller parties to win seats. This typically produces multi-party legislatures where no single party wins a majority, requiring coalition governments to form.' },
      { q: 'The Chinese Communist Party\'s "dual state" structure means:', opts: ['China has two separate constitutions', 'The party hierarchy runs parallel to the state hierarchy and ultimately controls it', 'China\'s economy is split between public and private sectors', 'Both the military and civilian authorities share equal governing power'], ans: 1, exp: 'In China, the CCP and state institutions (government ministries, courts, military) operate in parallel, with party structures holding ultimate authority at each level. The state implements policies, but the party decides them. This is a defining feature of Leninist one-party systems.' },
    ],
  },
  {
    id: 'pol-ir',
    name: 'International Relations Theory',
    grade: 10, term: 'Fall', credits: 0.5,
    description: 'How do we explain why states go to war, form alliances, or cooperate through international institutions? This course introduces the major theoretical frameworks of international relations — Realism, Liberalism, and Constructivism — and applies them to historical and contemporary world events, from World War I to US-China competition.',
    syllabus: {
      objectives: [
        'Explain the core assumptions of Realism, Liberalism, and Constructivism in IR',
        'Apply each theory to a historical or contemporary international conflict or cooperation',
        'Describe the structure and limitations of the United Nations system',
        'Analyze how international institutions and norms constrain state behavior',
        'Write a theory-driven analysis of a current international relations issue',
      ],
      units: [
        { week: '1–2',   topic: 'What Is IR Theory?',            desc: 'Why theory matters. Levels of analysis: individual, state, international system. Introduction to the discipline.' },
        { week: '3–4',   topic: 'Realism',                       desc: 'Classical realism (Thucydides, Morgenthau) and structural realism (Waltz). Anarchy, power, and the security dilemma.' },
        { week: '5–6',   topic: 'Liberalism',                    desc: 'Liberal internationalism, democratic peace theory, Kantian perpetual peace. Interdependence and international institutions.' },
        { week: '7–8',   topic: 'Constructivism',                desc: 'Alexander Wendt: "anarchy is what states make of it." How identity, norms, and ideas shape international behavior.' },
        { week: '9–10',  topic: 'The United Nations System',     desc: 'Structure of the UN (Security Council, General Assembly, Secretariat). Peacekeeping, veto power, and the limits of multilateralism.' },
        { week: '11–12', topic: 'Great Power Competition',       desc: 'US-China rivalry through the lens of IR theory. Power transition theory, Thucydides Trap, and the Taiwan question.' },
        { week: '13',    topic: 'International Law & Norms',     desc: 'How international law works without a world government. Custom, treaties, and the International Court of Justice.' },
        { week: '14–16', topic: 'Theory Application Project',    desc: 'Choose a current international issue — a conflict, trade dispute, or diplomatic crisis — and analyze it using all three theoretical frameworks.' },
      ],
    },
    resources: [
      { url: 'https://www.cfr.org/international-relations-theory', title: 'International Relations Theory — CFR Primer', channel: 'Council on Foreign Relations', note: 'Authoritative overview of IR theories with current examples. Bookmark this as your primary reference for Weeks 3–8.' },
      { url: 'https://www.youtube.com/c/PoliticsInMinutes', title: 'International Relations Explained — IR Theory Videos', channel: 'E-International Relations / Various', note: 'Search YouTube for "Realism IR theory explained" and "Constructivism Wendt" for clear academic explainers on each framework.' },
      { url: 'https://www.youtube.com/watch?v=MCr3NQ5JNDE', title: 'Is War Between the US and China Inevitable? — Graham Allison TED', channel: 'TED', note: 'Harvard\'s Graham Allison on the Thucydides Trap and US-China competition. Essential viewing for Week 11–12.' },
      { url: 'https://www.youtube.com/watch?v=NNhw3Lk2_a4', title: 'The United Nations Explained', channel: 'Kurzgesagt', note: 'Clear visual explainer on how the UN works, why it struggles, and what it has achieved.' },
    ],
    quiz: [
      { q: 'In IR theory, Realism\'s core claim is that international politics is best understood as:', opts: ['Cooperative exchange driven by shared values and institutions', 'A struggle for power among states in an anarchic system with no world government', 'A process shaped by ideas, identities, and social norms', 'A game where all states rationally pursue economic gain'], ans: 1, exp: 'Realism holds that the international system is anarchic — there is no world government to enforce rules. States are the main actors, they prioritize survival and power, and they cannot fully trust one another. This leads to balance-of-power politics, arms races, and war.' },
      { q: 'The "democratic peace theory," associated with Liberal IR theory, argues that:', opts: ['Democracies always win wars against authoritarian states', 'Democracies rarely go to war with each other, due to shared norms and mutual interests', 'Economic interdependence alone prevents wars', 'Democratic states have stronger militaries than authoritarian ones'], ans: 1, exp: 'Democratic peace theory is one of the most robust empirical findings in IR: liberal democracies almost never go to war with each other. Explanations include shared norms of peaceful dispute resolution and mutual economic interdependence that makes war costly.' },
      { q: 'Alexander Wendt\'s Constructivist argument that "anarchy is what states make of it" means:', opts: ['Anarchy does not actually exist in the international system', 'The meaning and effects of anarchy depend on the ideas, identities, and norms states develop', 'States should create a world government to end anarchy', 'Powerful states define the rules for weaker ones'], ans: 1, exp: 'Wendt argues that anarchy (the absence of world government) does not automatically lead to conflict. How states behave depends on their identities and social relationships. States that see each other as friends (like the US and Canada) treat anarchy differently than rivals (US and USSR).' },
      { q: 'The UN Security Council\'s "veto power" is held by:', opts: ['All 15 Security Council members', 'The five permanent members: US, UK, France, Russia, and China', 'The UN Secretary-General', 'Any country that contributes troops to UN peacekeeping'], ans: 1, exp: 'The five permanent members (P5) of the UN Security Council — the US, UK, France, Russia, and China — each hold veto power. Any one of them can block a resolution, which severely limits the UN\'s ability to act when P5 interests conflict.' },
      { q: 'Power transition theory, often used to analyze US-China relations, predicts conflict is most likely when:', opts: ['A rising power surpasses a declining hegemon in capabilities', 'Two states have similar military forces', 'A powerful state is isolated diplomatically', 'Economic ties between two states become very strong'], ans: 0, exp: 'Power transition theory (Organski) argues that wars are most likely when a rising power approaches and challenges the dominant power. The "Thucydides Trap" — the fear and miscalculation that occur during such transitions — is why US-China competition is widely studied through this lens.' },
    ],
  },
  {
    id: 'pol-aphg',
    name: 'AP Human Geography',
    grade: 10, term: 'Spring', credits: 1.0,
    description: 'AP Human Geography examines how human populations are distributed, how they reshape landscapes, and how geographic patterns explain political and cultural phenomena. Students analyze migration, urbanization, political boundaries, economic development, and cultural diffusion — earning college credit with a strong AP exam score.',
    syllabus: {
      objectives: [
        'Apply geographic concepts (scale, region, diffusion) to analyze human patterns',
        'Explain demographic transition theory and interpret population pyramids',
        'Analyze how political boundaries are drawn, contested, and changed',
        'Use the Human Development Index (HDI) to compare levels of development across regions',
        'Interpret maps, data sets, and geographic models on AP free-response questions',
      ],
      units: [
        { week: '1–2',   topic: 'Thinking Geographically',       desc: 'Scale, place, region, diffusion, spatial interaction. Key geographic models and how to use maps as analytical tools.' },
        { week: '3–4',   topic: 'Population & Migration',        desc: 'Population distribution, demographic transition model, population pyramids, push/pull migration factors, refugee crises.' },
        { week: '5–6',   topic: 'Cultural Patterns & Processes', desc: 'Language diffusion, world religions, cultural landscapes, folk vs. popular culture, cultural imperialism.' },
        { week: '7–8',   topic: 'Political Organization of Space', desc: 'Nation-states, boundaries and border disputes, centripetal vs. centrifugal forces, devolution, supranationalism (EU).' },
        { week: '9–10',  topic: 'Agricultural & Rural Patterns', desc: 'Agricultural revolutions, Von Thünen model, land use, food security, GMOs, subsistence vs. commercial farming.' },
        { week: '11',    topic: 'Industrialization & Economic Development', desc: 'Rostow\'s stages of growth, Wallerstein\'s world-systems theory, HDI, core-periphery model, global supply chains.' },
        { week: '12',    topic: 'Cities & Urban Land Use',       desc: 'Urban models (Burgess concentric zone, Hoyt sector, multiple nuclei), urbanization trends, megacities, gentrification.' },
        { week: '13–14', topic: 'Globalization & Development',   desc: 'Gender inequality index, informal economies, microlending, international development goals, environmental sustainability.' },
        { week: '15–16', topic: 'AP Exam Preparation',           desc: 'AP-style multiple choice, free-response practice with map analysis, stimulus-based questions, timed full exam simulations.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PL7C0E0E93E4B0B99E', title: 'AP Human Geography Full Review — Heimler\'s History', channel: 'Heimler\'s History', note: 'The best YouTube resource for AP HUG exam prep. Watch the entire playlist and use his unit reviews before each test.' },
      { url: 'https://www.khanacademy.org/humanities/ap-human-geography', title: 'AP Human Geography — Khan Academy', channel: 'Khan Academy', note: 'Full AP HUG curriculum with interactive exercises. Use for every unit — especially population models and economic development.' },
      { url: 'https://www.cfr.org/global-conflict-tracker', title: 'CFR Global Conflict Tracker & Country Resources', channel: 'Council on Foreign Relations', note: 'Use to research boundary disputes, separatist movements, and political geography examples for Weeks 7–8.' },
      { url: 'https://apclassroom.collegeboard.org/', title: 'AP Classroom — Official AP Human Geography Resources', channel: 'College Board', note: 'Official progress checks, released FRQs, and daily video lessons. Essential for AP exam preparation in Weeks 15–16.' },
    ],
    quiz: [
      { q: 'The Demographic Transition Model (DTM) predicts that as countries industrialize, they move toward:', opts: ['High birth rates and high death rates', 'High birth rates and low death rates, causing rapid population growth', 'Low birth rates and low death rates, stabilizing population', 'High death rates due to industrial pollution'], ans: 2, exp: 'Stage 4 of the DTM shows that developed, industrialized nations eventually reach low birth AND low death rates — producing stable or even declining population. Most of Western Europe and Japan are in Stage 4 or Stage 5 (population decline).' },
      { q: 'The Human Development Index (HDI) measures a country\'s development using:', opts: ['GDP per capita alone', 'Military strength, GDP, and population size', 'Life expectancy, education, and income per capita', 'Trade balance, foreign investment, and literacy'], ans: 2, exp: 'The HDI, developed by Mahbub ul Haq and the UNDP, combines three dimensions: health (life expectancy), education (mean and expected years of schooling), and income (GNI per capita). It provides a broader picture of human well-being than GDP alone.' },
      { q: 'Wallerstein\'s world-systems theory divides countries into:', opts: ['Developed and underdeveloped', 'Core, semi-periphery, and periphery based on their role in the global economy', 'First, Second, and Third World based on Cold War alignment', 'Colonial powers and former colonies'], ans: 1, exp: 'Wallerstein argues that the capitalist world economy creates a hierarchy: core states (wealthy, high-tech) exploit periphery states (poor, raw material exporters), with semi-periphery states in between. This structural inequality is self-reinforcing.' },
      { q: 'Supranationalism, as exemplified by the European Union, refers to:', opts: ['One country dominating its neighbors militarily', 'The transfer of some state authority to a multi-country organization', 'Each country acting independently without international cooperation', 'United Nations control over member states\' economies'], ans: 1, exp: 'Supranationalism occurs when states voluntarily cede some sovereignty to a higher authority. The EU has supranational powers over trade, currency (eurozone), and law that override member state law in those domains.' },
      { q: 'A "centrifugal force" in political geography is one that:', opts: ['Brings citizens together around national identity', 'Attracts foreign investment to a country', 'Divides and weakens a state\'s unity, potentially leading to devolution or secession', 'Strengthens a country\'s military capability'], ans: 2, exp: 'Centrifugal forces pull a state apart — ethnic, linguistic, religious, or regional divisions that undermine national unity. Examples: Quebec\'s secessionist movement in Canada, Catalonia in Spain. Centripetal forces do the opposite, binding the state together.' },
    ],
  },
  {
    id: 'pol-uslaw',
    name: 'US Government & Constitutional Law',
    grade: 11, term: 'Fall', credits: 0.5,
    description: 'A deep dive into the structure, principles, and living evolution of American government. Students examine the Constitution\'s design — separation of powers, federalism, checks and balances, and the Bill of Rights — through landmark Supreme Court cases, applying constitutional reasoning to contemporary legal and political controversies.',
    syllabus: {
      objectives: [
        'Explain the constitutional principles of separation of powers and checks and balances with examples',
        'Describe how federalism allocates power between national and state governments',
        'Analyze landmark Supreme Court decisions and their constitutional reasoning',
        'Explain how the Bill of Rights protects individual liberties against government action',
        'Apply constitutional analysis to a contemporary legal controversy in a structured essay',
      ],
      units: [
        { week: '1–2',   topic: 'Constitutional Foundations',    desc: 'Origins of the Constitution: Articles of Confederation\'s failures, Constitutional Convention, Federalist Papers.' },
        { week: '3–4',   topic: 'Separation of Powers & Checks', desc: 'The three branches: powers, limits, and how they check one another. Presidential veto, judicial review, congressional override.' },
        { week: '5–6',   topic: 'Federalism',                   desc: 'Enumerated, implied, and reserved powers. Commerce Clause evolution. Cooperative vs. dual federalism.' },
        { week: '7–8',   topic: 'The Bill of Rights',           desc: 'First Amendment freedoms (speech, religion, press), Fourth Amendment search and seizure, Fifth and Sixth Amendment rights of the accused.' },
        { week: '9–10',  topic: 'The Supreme Court',            desc: 'Judicial review (Marbury v. Madison), constitutional interpretation: originalism vs. living constitutionalism. How cases reach the Court.' },
        { week: '11–12', topic: 'Landmark Cases',               desc: 'Brown v. Board, Roe v. Wade / Dobbs, Citizens United, Obergefell v. Hodges. What changed and why they matter.' },
        { week: '13',    topic: 'Civil Rights & Equal Protection', desc: 'The 14th Amendment, equal protection clause, strict scrutiny. The civil rights movement and constitutional change.' },
        { week: '14–16', topic: 'Constitutional Analysis Project', desc: 'Choose a current legal dispute and write a structured constitutional analysis arguing one side using precedent and constitutional text.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtOfse2ncvffeelTrqvhrz8H', title: 'Crash Course Government & Politics — US Constitution Series', channel: 'Crash Course', note: 'Episodes 1–20 cover the constitutional structure of American government with clarity and depth.' },
      { url: 'https://www.khanacademy.org/humanities/us-government-and-civics', title: 'US Government & Civics — Khan Academy', channel: 'Khan Academy', note: 'Full curriculum on constitutional structure, civil liberties, and the Supreme Court. Use for practice and review.' },
      { url: 'https://www.oyez.org/', title: 'Oyez — Supreme Court Case Summaries', channel: 'Oyez Project', note: 'Freely accessible database of every Supreme Court case with audio arguments and plain-language summaries. Essential for Weeks 9–12.' },
      { url: 'https://constitutioncenter.org/', title: 'National Constitution Center — Interactive Constitution', channel: 'National Constitution Center', note: 'Clause-by-clause analysis of every part of the Constitution, with competing liberal and conservative interpretations side by side.' },
    ],
    quiz: [
      { q: 'The principle of "judicial review" — the power of courts to strike down laws as unconstitutional — was established in:', opts: ['The text of Article III of the Constitution', 'Marbury v. Madison (1803)', 'McCulloch v. Maryland (1819)', 'The Federalist Papers No. 78'], ans: 1, exp: 'Judicial review was not explicitly written in the Constitution. Chief Justice John Marshall claimed this power for the Supreme Court in Marbury v. Madison (1803), arguing that it is the courts\' duty to say what the law is — and that any law conflicting with the Constitution is void.' },
      { q: 'The "necessary and proper" clause of the Constitution (Article I, Section 8) is significant because:', opts: ['It limits Congress to only the powers explicitly listed', 'It grants Congress implied powers beyond those explicitly listed, enabling flexible governance', 'It gives the President authority to issue executive orders', 'It establishes the Supreme Court\'s appellate jurisdiction'], ans: 1, exp: 'The necessary and proper clause (also called the "elastic clause") gives Congress power to make laws needed to carry out its enumerated powers. In McCulloch v. Maryland, Marshall interpreted it broadly, establishing the doctrine of implied powers that has greatly expanded federal authority.' },
      { q: 'Under the First Amendment, "prior restraint" refers to:', opts: ['Government censorship of speech before it is published or broadcast', 'Criminal punishment for speech after it is made', 'Restrictions on political campaign donations', 'The right to remain silent when arrested'], ans: 0, exp: 'Prior restraint is government action that prevents speech or publication before it occurs — as opposed to punishing speech after the fact. Courts apply a very high standard to justify prior restraint, rooted in Near v. Minnesota (1931) and the Pentagon Papers case (1971).' },
      { q: 'The Fourteenth Amendment\'s equal protection clause is most directly relevant to:', opts: ['Presidential term limits', 'The federal government\'s power to levy income taxes', 'Laws that treat different groups differently, which must withstand judicial scrutiny', 'The right of states to nullify federal laws'], ans: 2, exp: 'The Equal Protection Clause prohibits states from denying any person equal protection of the laws. Courts apply different levels of scrutiny depending on the classification: rational basis (most laws), intermediate scrutiny (sex), and strict scrutiny (race, national origin, fundamental rights).' },
    ],
  },
  {
    id: 'pol-apgov',
    name: 'AP Government & Politics: US',
    grade: 11, term: 'Spring', credits: 1.0,
    description: 'College-level American government with full AP exam preparation. Students examine constitutional foundations, the three branches in depth, civil liberties, political participation, and public policy through required Supreme Court cases and Foundational Documents. Aim for a 4 or 5 on the AP exam to earn college credit.',
    syllabus: {
      objectives: [
        'Analyze the constitutional structure of American government and its underlying principles',
        'Explain how Congress, the President, and the Supreme Court interact and compete for power',
        'Describe the role of political parties, interest groups, and media in the policy process',
        'Apply the required Supreme Court cases to analyze civil liberties and civil rights issues',
        'Write AP-style argumentative essays (argument essay and SCOTUS comparison) under timed conditions',
      ],
      units: [
        { week: '1–3',   topic: 'Foundations of American Democracy', desc: 'Enlightenment ideas, Articles of Confederation, Constitutional Convention, Federalist vs. Anti-Federalist debates, constitutional principles.' },
        { week: '4–5',   topic: 'Interactions Among Branches',  desc: 'Congressional powers and structure, lawmaking process, presidential powers and constraints, bureaucracy, judicial review.' },
        { week: '6–7',   topic: 'Civil Liberties & Civil Rights', desc: 'Incorporation doctrine, First Amendment cases, due process, equal protection, required SCOTUS cases (Brown, Engel, Tinker, Gideon, Miranda, Roe/Dobbs, Obergefell).' },
        { week: '8–9',   topic: 'American Political Ideologies & Beliefs', desc: 'Political socialization, political ideology spectrum, polling, public opinion, generational and demographic shifts.' },
        { week: '10–11', topic: 'Political Participation',      desc: 'Voting behavior, voter turnout, elections, Electoral College, campaign finance (Citizens United), political parties and realignment.' },
        { week: '12',    topic: 'Interest Groups & Media',      desc: 'How interest groups lobby, PACs and Super PACs, the role of media (traditional and social) in agenda-setting.' },
        { week: '13',    topic: 'Public Policy',                desc: 'The policy cycle: agenda-setting, formulation, adoption, implementation, evaluation. Domestic vs. foreign policy.' },
        { week: '14–16', topic: 'AP Exam Preparation',          desc: 'Timed multiple choice, free-response writing (SCOTUS comparison, argument essay, concept application, quantitative analysis), full exam simulation.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/c/heimlershistory', title: 'AP Government Full Review — Heimler\'s History', channel: 'Heimler\'s History', note: 'The gold standard for AP Gov exam prep. Watch every episode in the AP Gov playlist and use his unit review sheets.' },
      { url: 'https://www.khanacademy.org/humanities/us-government-and-civics', title: 'AP US Government & Politics — Khan Academy', channel: 'Khan Academy', note: 'Full AP Gov curriculum. Especially strong for the required SCOTUS cases and constitutional foundations.' },
      { url: 'https://apclassroom.collegeboard.org/', title: 'AP Classroom — Official AP Government Resources', channel: 'College Board', note: 'Official progress checks, daily videos, and released FRQs. Use the SCOTUS case library and released argument essays.' },
      { url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtOfse2ncvffeelTrqvhrz8H', title: 'Crash Course Government & Politics — Complete Series', channel: 'Crash Course', note: 'All 50 episodes cover every AP Gov topic. Use as a first watch for each unit before deeper study.' },
    ],
    quiz: [
      { q: 'In Federalist No. 51, James Madison argues that the best guard against tyranny in government is:', opts: ['A powerful executive with authority to override Congress', 'Ambition counteracting ambition through the separation of powers and checks and balances', 'Direct democracy where citizens vote on every law', 'A strong military to deter domestic insurrection'], ans: 1, exp: '"If men were angels, no government would be necessary." Madison\'s insight in Federalist 51 is that you cannot rely on good character alone — the constitutional structure must pit the ambitions of officeholders against each other, so power checks power.' },
      { q: 'The Supreme Court\'s decision in Citizens United v. FEC (2010) held that:', opts: ['Campaign contributions by individuals must be publicly disclosed', 'Corporations and unions cannot donate to political campaigns', 'Limiting independent political expenditures by corporations violates First Amendment free speech protections', 'The Electoral College must reflect the popular vote'], ans: 2, exp: 'In Citizens United, the Court ruled that political spending is a form of free speech protected by the First Amendment. Corporations, associations, and unions may spend unlimited amounts on independent political expenditures — leading to the rise of Super PACs.' },
      { q: 'The "incorporation doctrine" refers to the Supreme Court\'s use of the 14th Amendment to:', opts: ['Allow states to expand rights beyond the federal minimum', 'Apply most Bill of Rights protections to state governments, not just the federal government', 'Incorporate foreign treaty obligations into domestic law', 'Require federal agencies to follow procedural rules'], ans: 1, exp: 'Originally, the Bill of Rights only constrained the federal government. Through the 14th Amendment\'s due process clause, the Supreme Court has selectively incorporated nearly all Bill of Rights protections so they apply to state governments as well.' },
      { q: 'Which best describes the difference between "iron triangles" and "issue networks" in policymaking?', opts: ['Iron triangles are formal constitutional structures; issue networks are informal', 'Iron triangles are stable, closed alliances among an agency, congressional committee, and interest group; issue networks are fluid and involve more actors', 'Issue networks only involve government actors, while iron triangles include private businesses', 'Iron triangles operate at the state level; issue networks operate at the federal level'], ans: 1, exp: 'Iron triangles describe the tight, mutually beneficial relationships among a federal agency, the relevant congressional subcommittee, and an interest group. Issue networks are broader, more fluid policy communities involving academics, journalists, NGOs, and multiple agencies — more common in complex modern policy areas.' },
      { q: 'The primary mechanism by which public opinion influences government policy is through:', opts: ['Direct orders from citizens to their elected officials', 'Electoral accountability — politicians track public opinion to improve their re-election prospects', 'Mandatory polling requirements written into the Constitution', 'Supreme Court rulings that must reflect majority opinion'], ans: 1, exp: 'The main linkage between public opinion and policy is electoral accountability: politicians who consistently ignore public preferences risk losing re-election. Interest groups, media framing, and agenda-setting also shape which opinions translate into policy priorities.' },
    ],
  },
  {
    id: 'pol-trade',
    name: 'Global Economics & Trade Policy',
    grade: 12, term: 'Fall', credits: 0.5,
    description: 'How do trade, investment, and economic interdependence shape political relationships between countries? This course bridges economics and political science, examining trade theory, tariff and non-tariff barriers, the WTO, bilateral and multilateral trade agreements, currency policy, and the politics of US-China economic competition.',
    syllabus: {
      objectives: [
        'Apply comparative advantage theory and its limitations to explain patterns of international trade',
        'Analyze how tariffs, quotas, and subsidies affect trade flows and political relationships',
        'Explain the role of the WTO and regional trade agreements in governing global commerce',
        'Describe how exchange rate policy can be used as a tool of economic statecraft',
        'Write a policy brief analyzing a current trade dispute with a recommended policy position',
      ],
      units: [
        { week: '1–2',   topic: 'Why States Trade — and Fight Over It', desc: 'Comparative advantage, terms of trade, gains and distributional consequences of trade. Why free trade has winners and losers.' },
        { week: '3–4',   topic: 'Trade Barriers & Policy Tools',  desc: 'Tariffs, quotas, subsidies, non-tariff barriers. Who benefits, who pays. The political economy of protection.' },
        { week: '5–6',   topic: 'The WTO & Multilateral Trade',   desc: 'GATT origins, WTO structure and dispute settlement, most-favored-nation status, and the collapse of the Doha Round.' },
        { week: '7–8',   topic: 'Regional Trade Agreements',      desc: 'USMCA, EU single market, RCEP, CPTPP. How regional blocs work and whether they undermine global free trade.' },
        { week: '9–10',  topic: 'Currency & Exchange Rate Policy', desc: 'How exchange rates affect trade competitiveness. Currency manipulation debates, China\'s renminbi policy, and currency wars.' },
        { week: '11–12', topic: 'US-China Economic Competition',  desc: 'Trade war, technology decoupling, supply chain restructuring, sanctions, and the debate over economic interdependence vs. security.' },
        { week: '13',    topic: 'Trade & Development',            desc: 'Import-substitution industrialization vs. export-led growth. How East Asia (Japan, Korea, China) used trade policy to develop.' },
        { week: '14–16', topic: 'Trade Policy Brief',             desc: 'Write a policy brief on a current trade issue (e.g., semiconductor export controls, Chinese EV tariffs, digital trade rules). Argue a specific policy recommendation.' },
      ],
    },
    resources: [
      { url: 'https://www.cfr.org/topics/trade-and-trade-policy', title: 'Trade & Trade Policy — CFR Issue Guide', channel: 'Council on Foreign Relations', note: 'Comprehensive, up-to-date analysis of global trade issues. Essential reference for the policy brief project.' },
      { url: 'https://www.youtube.com/watch?v=rcW9SFGasUE', title: 'Comparative Advantage and Trade — Explained', channel: 'Marginal Revolution University', note: 'Top economists explain comparative advantage clearly — start here for Weeks 1–2 trade theory.' },
      { url: 'https://www.youtube.com/watch?v=JHRnqJJ0rhc', title: 'US-China Trade War Explained', channel: 'CNBC', note: 'Clear explainer on the origins, escalation, and implications of the US-China trade conflict. Use for Weeks 11–12.' },
      { url: 'https://www.youtube.com/watch?v=_FHcnAf_WKE', title: 'How the WTO Works', channel: 'Explained / Vox', note: 'Visual overview of the WTO\'s structure, dispute settlement, and why it is under stress.' },
    ],
    quiz: [
      { q: 'A country imposes a 25% tariff on imported steel. The MOST direct effect is:', opts: ['Foreign steel becomes cheaper for domestic buyers', 'Domestic steel producers face more competition and lower prices', 'The price of imported steel rises, protecting domestic producers but raising costs for steel-using industries', 'Foreign steel companies receive a tax rebate'], ans: 2, exp: 'A tariff is a tax on imports, paid by domestic importers. It raises the price of foreign steel, making domestic steel relatively more competitive. Domestic steel producers gain, but industries that use steel as an input (autos, construction) face higher costs. Consumers bear higher prices.' },
      { q: 'The WTO\'s "most-favored-nation" (MFN) principle requires that:', opts: ['Countries give preferential treatment to their closest allies', 'Any trade advantage granted to one country must be extended to all WTO members', 'Developed countries give developing countries preferential market access', 'Members treat their largest trading partners better than smaller ones'], ans: 1, exp: 'MFN is the foundation of non-discrimination in the WTO. If Country A lowers tariffs for Country B, it must offer the same tariff to all other WTO members. This prevents discriminatory bilateral deals — with exceptions allowed for regional free trade agreements.' },
      { q: 'When economists refer to China\'s export-led growth strategy, they mean:', opts: ['China imports more than it exports', 'China deliberately closed its markets to foreign goods', 'China used trade surpluses and competitive manufacturing exports as the primary engine of economic development', 'China relied on foreign aid for economic development'], ans: 2, exp: 'Export-led growth (practiced by Japan, South Korea, and China) involves keeping currency competitive, investing in manufacturing capacity, and targeting export markets. China\'s entry into global supply chains and its WTO accession in 2001 dramatically accelerated this strategy.' },
      { q: '"Economic statecraft" or "weaponized interdependence" refers to:', opts: ['Countries using military force to protect trade routes', 'States exploiting economic interdependence as a tool of political coercion or leverage', 'The peaceful resolution of trade disputes through WTO arbitration', 'The free flow of capital across borders without government restriction'], ans: 1, exp: 'Weaponized interdependence (Farrell and Newman) describes how powerful states can exploit asymmetric economic linkages — control of financial networks, technology supply chains, or commodity flows — to coerce others. US sanctions and China\'s rare earth export restrictions are examples.' },
    ],
  },
  {
    id: 'pol-capstone',
    name: 'Policy Research Capstone',
    grade: 12, term: 'Spring', credits: 1.0,
    description: 'Your senior capstone is an original policy research paper that serves as the academic centerpiece of your college application. You will choose a real policy problem — domestic or international — develop a research question, review the academic and policy literature, analyze evidence, and produce a structured policy paper with recommendations. Presentations are conducted in a formal policy forum format.',
    syllabus: {
      objectives: [
        'Formulate a clear, researchable policy question grounded in political science or IR concepts',
        'Conduct a structured literature review of academic and policy sources',
        'Analyze qualitative and quantitative evidence to evaluate policy options',
        'Write a complete policy paper with an executive summary, analysis, and recommendations',
        'Present and defend research findings and policy recommendations in a formal Q&A format',
      ],
      units: [
        { week: '1–2',   topic: 'Policy Research Design',        desc: 'Selecting a policy problem, formulating a research question, identifying dependent and independent variables, mapping stakeholders.' },
        { week: '3–4',   topic: 'Literature Review',             desc: 'Finding and evaluating academic journals, think-tank reports, and government documents. Synthesizing sources into a coherent argument.' },
        { week: '5–6',   topic: 'Data Sources & Evidence',       desc: 'Using World Bank, UN, Pew, and government databases. Evaluating source credibility. Quantitative vs. qualitative evidence.' },
        { week: '7–8',   topic: 'Policy Analysis Frameworks',    desc: 'Cost-benefit analysis, stakeholder analysis, feasibility assessment, trade-off evaluation. Comparing policy alternatives.' },
        { week: '9–10',  topic: 'Writing the Policy Paper',      desc: 'Structure of a policy paper: executive summary, problem statement, background, analysis, alternatives, recommendation, conclusion.' },
        { week: '11–12', topic: 'Revision & Peer Review',        desc: 'Structured peer feedback workshops, instructor review, revision for argumentation clarity and evidence quality.' },
        { week: '13–14', topic: 'Preparing the Presentation',    desc: 'Designing policy slides, crafting a clear verbal argument, anticipating counterarguments, Q&A preparation.' },
        { week: '15–16', topic: 'Policy Forum Presentation',     desc: 'Present paper to a faculty and guest panel. Defend your policy recommendation and respond to challenging questions.' },
      ],
    },
    resources: [
      { url: 'https://www.cfr.org/', title: 'Council on Foreign Relations — Research & Reports', channel: 'Council on Foreign Relations', note: 'The primary model for your policy paper. Read CFR Council Special Reports and Independent Task Force Reports to see what professional policy analysis looks like.' },
      { url: 'https://data.worldbank.org/', title: 'World Bank Open Data', channel: 'World Bank', note: 'Comprehensive global development data — GDP, governance indicators, education, health. Essential for research papers on international topics.' },
      { url: 'https://www.youtube.com/watch?v=MCr3NQ5JNDE', title: 'How to Write a Policy Brief — Georgetown University', channel: 'Georgetown University', note: 'Walkthrough of the structure and argumentation of a professional policy brief. Use at the start of Weeks 9–10.' },
      { url: 'https://www.ted.com/topics/global+issues', title: 'TED Talks on Global Issues & Policy', channel: 'TED', note: 'Browse TED talks on your chosen policy topic for inspiration and perspectives. Use during Weeks 1–2 to refine your research question.' },
    ],
    quiz: [
      { q: 'The "executive summary" of a policy paper serves to:', opts: ['List all the academic sources cited in the paper', 'Provide a 1–2 page overview of the problem, analysis, and key recommendations for busy decision-makers who may not read the full paper', 'Summarize opposing viewpoints without taking a position', 'Describe the research methodology in technical detail'], ans: 1, exp: 'Policy papers are written for practitioners who are often pressed for time. The executive summary distills the most important findings and recommendations into a brief, readable form. It is frequently the only section that senior officials read — so it must stand alone.' },
      { q: 'In a policy analysis framework, a "feasibility assessment" evaluates whether a policy option:', opts: ['Is supported by academic literature', 'Can realistically be implemented given political, economic, budgetary, and administrative constraints', 'Has been tried before in another country', 'Maximizes the number of people who benefit'], ans: 1, exp: 'Even the best policy solution on paper may fail if it is politically unpassable, too expensive, administratively impossible, or legally constrained. Feasibility analysis forces analysts to assess whether a recommendation can actually be put into practice — distinguishing ideal from achievable.' },
      { q: 'When evaluating sources for a policy research paper, a peer-reviewed journal article is most valuable because:', opts: ['It is always more recent than news articles', 'It has been evaluated by independent experts in the field for methodological rigor and validity', 'It represents the official government position on an issue', 'It is always freely available online'], ans: 1, exp: 'Peer review is the process by which independent scholars evaluate a paper before publication, checking methodology, evidence, and reasoning. While not perfect, it provides quality control that opinion pieces, news articles, and unrefereed reports lack.' },
      { q: 'A policy paper recommends that the US impose export controls on advanced semiconductor technology to China. A key counterargument a policymaker should address is:', opts: ['The US has no legal authority to restrict exports', 'Export controls may harm US semiconductor companies\' revenues and push China to accelerate its own chip development', 'Semiconductors are not important to national security', 'Congress must approve all export control decisions'], ans: 1, exp: 'Export controls create a genuine trade-off: they may delay China\'s access to advanced technology but also cost US firms billions in lost sales and could accelerate China\'s domestic chip development programs (like SMIC and Huawei\'s HiSilicon). Rigorous policy analysis must grapple with these costs and second-order effects.' },
      { q: 'In the context of policy research, "stakeholder analysis" identifies:', opts: ['Only the government agencies involved in implementing a policy', 'All actors — government, private sector, civil society, and affected populations — who have interests in or are affected by a policy decision', 'The political party that supports a given policy position', 'Academic experts who have published on the topic'], ans: 1, exp: 'Stakeholder analysis maps every group with a stake in the policy outcome: who benefits, who loses, who has political power to block or support implementation. Ignoring key stakeholders is a common reason good policies fail — they face unexpected opposition from groups the analyst overlooked.' },
    ],
  },
];

export default function PoliticalSciencePathway() {
  return <PathwayPage meta={META} schedule={SCHEDULE} courses={COURSES} />;
}
