import React from 'react';
import { PathwayPage } from './PathwayComponents';

const COLOR = '#00695C'; // medical teal

const META = {
  color: COLOR,
  title: 'Pre-Medicine & Biomedical Sciences',
  subtitle: 'Heal people. Advance science. Save lives.',
  emoji: '🩺',
  courseEmoji: '🩺',
  heroDescription: 'A science-intensive 4-year pathway for students targeting medical school, biomedical research, or health sciences. From cell biology to AP Biology and human physiology, you will graduate with the science depth and research experience that programs like Johns Hopkins, UCSF, and UMich Pre-Med tracks look for.',
  targets: ['Pre-Medicine / MD Track', 'Biomedical Engineering', 'Biology / Molecular Biology', 'Neuroscience', 'Public Health', 'Pharmacy / Pharmacology'],
  collegeNote: 'Pre-med applicants must demonstrate exceptional science preparation. AP Biology is the single most important AP for this track. Colleges also look for research experience and community health involvement. This pathway builds both the transcript depth and the conceptual fluency that medical school prerequisites demand.',
  stats: [{ label: 'AP Courses', value: 2 }],
};

const SCHEDULE = [
  { grade: 9, term: 'Fall', courses: [
    { name: 'English I',                  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra I',                  type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology',                    type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World History',              type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Physical Education',         type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Cell Biology & Life Processes', type: 'pathway', credits: 0.5, courseId: 'med-cellbio' },
  ]},
  { grade: 9, term: 'Spring', courses: [
    { name: 'English I — Writing',        type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Geometry',                   type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Environmental Science',      type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Geography',                  type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Health & Wellness',          type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Human Anatomy & Physiology', type: 'pathway',   credits: 0.5, courseId: 'med-anatomy' },
  ]},
  { grade: 10, term: 'Fall', courses: [
    { name: 'English II',                 type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra II',                 type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Chemistry',                  type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'U.S. History',              type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Genetics & Molecular Biology', type: 'pathway', credits: 0.5, courseId: 'med-genetics' },
    { name: 'Introduction to Communication', type: 'supporting', credits: 0.5, dept: 'Communication' },
  ]},
  { grade: 10, term: 'Spring', courses: [
    { name: 'English II — Literature',    type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Pre-Calculus',              type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics Fundamentals',      type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World Politics',            type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Biochemistry Fundamentals', type: 'pathway',   credits: 0.5, courseId: 'med-biochem' },
  ]},
  { grade: 11, term: 'Fall', courses: [
    { name: 'English III',               type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Statistics',                type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology — Advanced',        type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'AP Biology',                type: 'pathway',   credits: 1.0, courseId: 'med-apbio' },
  ]},
  { grade: 11, term: 'Spring', courses: [
    { name: 'English III — Literature',  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Trigonometry',              type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics — Mechanics',       type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Microbiology & Immunology', type: 'pathway',   credits: 0.5, courseId: 'med-micro' },
    { name: 'AP Statistics',             type: 'supporting', credits: 1.0, dept: 'Mathematics' },
  ]},
  { grade: 12, term: 'Fall', courses: [
    { name: 'English IV — Writing & Communication', type: 'core', credits: 1.0, dept: 'English Language Arts' },
    { name: 'Calculus',                  type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Neuroscience & Brain Function', type: 'pathway', credits: 0.5, courseId: 'med-neuro' },
    { name: 'AP Chemistry',              type: 'supporting', credits: 1.0, dept: 'Science', note: 'Strongly recommended for pre-med' },
  ]},
  { grade: 12, term: 'Spring', courses: [
    { name: 'English IV — Advanced Composition', type: 'core', credits: 1.0, dept: 'English Language Arts' },
    { name: 'Biomedical Research Capstone', type: 'pathway', credits: 1.0, courseId: 'med-capstone' },
  ]},
];

const COURSES = [
  {
    id: 'med-cellbio',
    name: 'Cell Biology & Life Processes',
    grade: 9, term: 'Fall', credits: 0.5,
    description: 'Every medical concept — from cancer to antibiotic resistance — begins at the cell. This course establishes the foundational literacy of life science by examining cell structure and function, energy metabolism, and cellular reproduction. Students learn to think in the language of molecules and cells, building the framework that all future biology and chemistry courses depend on.',
    syllabus: {
      objectives: [
        'Identify and describe the functions of major prokaryotic and eukaryotic organelles',
        'Explain how the phospholipid bilayer governs membrane permeability and cell signaling',
        'Trace the flow of energy through cellular respiration and photosynthesis, identifying key inputs and outputs',
        'Distinguish between mitosis and meiosis and explain the significance of each for growth and reproduction',
        'Analyze how disruptions in normal cell cycle regulation can lead to disease, including cancer',
      ],
      units: [
        { week: '1–2',   topic: 'The Chemistry of Life',           desc: 'Water properties, macromolecules (carbohydrates, lipids, proteins, nucleic acids), functional groups, and why molecular structure determines biological function.' },
        { week: '3–4',   topic: 'Cell Structure & Organelles',     desc: 'Prokaryotic vs. eukaryotic cells. Tour of organelles: nucleus, ribosomes, ER (rough and smooth), Golgi apparatus, mitochondria, chloroplasts, lysosomes, and the cytoskeleton.' },
        { week: '5–6',   topic: 'Membrane Biology',                desc: 'Fluid mosaic model, phospholipid bilayer, membrane proteins. Passive transport (diffusion, osmosis, facilitated diffusion) vs. active transport. Endocytosis and exocytosis.' },
        { week: '7–8',   topic: 'Cellular Respiration',            desc: 'ATP as energy currency. Glycolysis, the Krebs cycle, and the electron transport chain. Anaerobic respiration and fermentation. Net ATP yields and efficiency.' },
        { week: '9–10',  topic: 'Photosynthesis',                  desc: 'Light-dependent reactions in the thylakoid (photosystems I and II, chemiosmosis). Calvin cycle in the stroma. C3, C4, and CAM plants. Comparing respiration and photosynthesis.' },
        { week: '11–12', topic: 'Cell Cycle & Mitosis',            desc: 'Interphase (G1, S, G2), mitosis (PMAT), cytokinesis. Cyclins, CDKs, and cell cycle checkpoints. How mutations in checkpoint genes drive cancer.' },
        { week: '13–14', topic: 'Meiosis & Sexual Reproduction',   desc: 'Meiosis I and II. Crossing over and genetic recombination. Comparison of mitosis vs. meiosis. Gametogenesis: spermatogenesis and oogenesis.' },
        { week: '15–16', topic: 'Cell Biology in Medicine',        desc: 'Case studies: cancer cell biology, stem cells and regenerative medicine, apoptosis (programmed cell death), and how viruses hijack cellular machinery.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PL3EED4C1D684D3ADF', title: 'Crash Course Biology — Full Playlist', channel: 'Crash Course', note: 'Episodes 1–10 cover cell structure, photosynthesis, and cellular respiration in an engaging, accurate format. Watch one episode per topic.' },
      { url: 'https://www.khanacademy.org/science/ap-biology', title: 'AP Biology — Cell Biology Units', channel: 'Khan Academy', note: 'Work through Units 1–3 (Chemistry of Life, Cell Structure, Cellular Energetics). Interactive exercises with immediate feedback.' },
      { url: 'https://www.hhmi.org/biointeractive/explore', title: 'HHMI BioInteractive — Cell Biology Resources', channel: 'HHMI BioInteractive', note: 'Research-quality animations and virtual labs on membrane transport, mitosis, and cellular respiration. Free and scientifically rigorous.' },
      { url: 'https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/', title: 'MIT OCW 7.01 — Fundamentals of Biology', channel: 'MIT OpenCourseWare', note: 'MIT introductory biology lecture notes and problem sets. Lectures 1–10 align with this course. Excellent for students who want college-level depth.' },
    ],
    quiz: [
      { q: 'Which organelle is responsible for producing ATP via oxidative phosphorylation in eukaryotic cells?', opts: ['Ribosome', 'Mitochondrion', 'Golgi apparatus', 'Lysosome'], ans: 1, exp: 'The mitochondrion is the site of the Krebs cycle and the electron transport chain, where the majority of ATP is produced. Its inner membrane (cristae) houses the ATP synthase complexes that drive oxidative phosphorylation.' },
      { q: 'A cell is placed in a hypertonic solution. What will happen to it?', opts: ['Water will enter the cell by osmosis, causing it to swell', 'Water will leave the cell by osmosis, causing it to shrink', 'Solutes will enter the cell by diffusion', 'Nothing — the cell membrane prevents any movement'], ans: 1, exp: 'In a hypertonic solution, solute concentration outside the cell is higher than inside. Water moves from low solute concentration (inside) to high solute concentration (outside) by osmosis, causing the cell to lose water and shrink (crenate in animal cells).' },
      { q: 'What is the correct sequence of stages in mitosis?', opts: ['Prophase → Anaphase → Metaphase → Telophase', 'Prophase → Metaphase → Anaphase → Telophase', 'Metaphase → Prophase → Telophase → Anaphase', 'Interphase → Metaphase → Anaphase → Telophase'], ans: 1, exp: 'Mitosis proceeds PMAT: Prophase (chromosomes condense, spindle forms) → Metaphase (chromosomes align at metaphase plate) → Anaphase (sister chromatids separate to poles) → Telophase (nuclear envelopes reform). Remember: Phases Make A Team.' },
      { q: 'During cellular respiration, what is the primary role of the electron transport chain?', opts: ['To produce acetyl-CoA from pyruvate', 'To generate ATP by using electrons from NADH and FADH₂ to pump H⁺ ions across the inner mitochondrial membrane', 'To convert glucose to pyruvate', 'To fix CO₂ into organic molecules'], ans: 1, exp: 'The electron transport chain accepts electrons from NADH and FADH₂ (produced in glycolysis and the Krebs cycle) and passes them through protein complexes, pumping H⁺ ions into the intermembrane space. This electrochemical gradient drives ATP synthase to produce ~32–34 ATP per glucose molecule.' },
      { q: 'How does crossing over during meiosis I contribute to genetic diversity?', opts: ['It doubles the number of chromosomes', 'It allows homologous chromosomes to exchange segments, creating new combinations of alleles', 'It separates sister chromatids before meiosis II', 'It prevents mutations from being passed to offspring'], ans: 1, exp: 'Crossing over (recombination) occurs during prophase I of meiosis when homologous chromosomes synapse at the synaptonemal complex. Chromatids exchange corresponding segments at chiasmata, producing chromosomes with new allele combinations that never existed in either parent — a major source of genetic variation.' },
    ],
  },
  {
    id: 'med-anatomy',
    name: 'Human Anatomy & Physiology',
    grade: 9, term: 'Spring', credits: 0.5,
    description: 'The body is the machine a future physician must understand completely. This course surveys all major organ systems — cardiovascular, respiratory, digestive, musculoskeletal, endocrine, and more — connecting structural anatomy to functional physiology throughout. Students develop the vocabulary and conceptual framework used in every clinical context from patient assessment to pharmacology.',
    syllabus: {
      objectives: [
        'Identify the major bones, muscles, and organs of the human body and describe their structural relationships',
        'Explain how each major organ system maintains homeostasis and how systems interact',
        'Describe the cardiac cycle, including the electrical conduction system and the mechanics of blood pressure',
        'Trace food from ingestion through digestion and absorption, explaining enzymatic and hormonal regulation at each stage',
        'Analyze how disruptions to normal physiology (e.g., hypertension, diabetes, asthma) result from specific system failures',
      ],
      units: [
        { week: '1–2',   topic: 'Anatomical Terminology & Organization', desc: 'Body planes, directional terms, body cavities, levels of organization (chemical → cell → tissue → organ → system). The four tissue types: epithelial, connective, muscle, nervous.' },
        { week: '3–4',   topic: 'Integumentary & Skeletal Systems',    desc: 'Skin layers, thermoregulation, wound healing. Axial vs. appendicular skeleton, bone tissue (compact and spongy), ossification, joint types, and common musculoskeletal injuries.' },
        { week: '5–6',   topic: 'Muscular System',                    desc: 'Skeletal, smooth, and cardiac muscle. Sarcomere structure, sliding filament theory of muscle contraction, neuromuscular junction, and the role of calcium and ATP.' },
        { week: '7–8',   topic: 'Cardiovascular System',              desc: 'Heart chambers, valves, and the cardiac cycle. Electrical conduction (SA node, AV node, bundle of His, Purkinje fibers). Blood pressure regulation and the baroreceptor reflex. Blood composition and ABO blood typing.' },
        { week: '9–10',  topic: 'Respiratory & Lymphatic Systems',    desc: 'Upper and lower respiratory tract anatomy. Mechanics of breathing: pressure gradients, diaphragm, lung compliance. Gas exchange at the alveolar-capillary membrane. Oxygen and CO₂ transport in blood. Lymph nodes, lymph circulation, and its role in immunity.' },
        { week: '11–12', topic: 'Digestive & Urinary Systems',        desc: 'GI tract from mouth to anus. Enzymatic digestion of carbohydrates, proteins, and fats. Liver, pancreas, and gallbladder functions. Kidney anatomy (nephron structure), filtration, reabsorption, secretion, and urine formation.' },
        { week: '13–14', topic: 'Endocrine & Reproductive Systems',   desc: 'Major endocrine glands and hormones (hypothalamus, pituitary, thyroid, adrenal, pancreas). Feedback loops. The male and female reproductive systems; the menstrual cycle and hormonal regulation.' },
        { week: '15–16', topic: 'Nervous System & Clinical Integration', desc: 'CNS vs. PNS, neuron anatomy, action potential, synaptic transmission. Reflex arcs. Case-based review: applying anatomy and physiology to diagnose hypertension, type 2 diabetes, chronic obstructive pulmonary disease (COPD), and kidney disease.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PLbKSbFnKYVY0PCRto9fiSRwgNFRHR_yp8', title: 'Crash Course Anatomy & Physiology — Full Series', channel: 'Crash Course', note: 'Crash Course A&P covers every system in clear, accurate episodes. Watch 2–3 episodes per unit to reinforce lecture content.' },
      { url: 'https://www.khanacademy.org/science/health-and-medicine', title: 'Health & Medicine — Human Body Systems', channel: 'Khan Academy', note: 'Khan Academy\'s health and medicine section covers cardiovascular, respiratory, and other systems with MCAT-level detail. Ideal for self-paced practice.' },
      { url: 'https://www.hhmi.org/biointeractive/cardiology-cardiac-physiology', title: 'HHMI BioInteractive — Cardiac Physiology', channel: 'HHMI BioInteractive', note: 'Animations and case studies on heart function and cardiovascular disease. Use during the cardiovascular unit.' },
      { url: 'https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/', title: 'MIT OCW 7.01 — Fundamentals of Biology', channel: 'MIT OpenCourseWare', note: 'MIT\'s biology course provides rigorous coverage of physiology at an introductory college level. The lecture notes and exams are excellent review material.' },
    ],
    quiz: [
      { q: 'Which structure initiates the electrical impulse that triggers each heartbeat?', opts: ['Atrioventricular (AV) node', 'Bundle of His', 'Sinoatrial (SA) node', 'Purkinje fibers'], ans: 2, exp: 'The sinoatrial (SA) node, located in the right atrium, is the heart\'s natural pacemaker. It spontaneously depolarizes ~60–100 times per minute, generating an electrical impulse that spreads through the atria, to the AV node, and down through the bundle of His and Purkinje fibers to trigger ventricular contraction.' },
      { q: 'At the alveolar-capillary membrane, oxygen moves from the alveoli into the blood because:', opts: ['Active transport pumps move it against its gradient', 'Its partial pressure is higher in the alveolus than in the deoxygenated blood arriving from the pulmonary artery', 'Hemoglobin actively grabs oxygen molecules', 'Blood pressure forces oxygen through the membrane'], ans: 1, exp: 'Gas exchange occurs by passive diffusion down partial pressure gradients. Deoxygenated venous blood arriving at the lungs has a low PO₂ (~40 mmHg), while alveolar air has a higher PO₂ (~104 mmHg). Oxygen diffuses from high to low partial pressure across the thin alveolar-capillary membrane.' },
      { q: 'The sliding filament theory of muscle contraction states that:', opts: ['Muscle fibers shorten by chemically degrading actin and myosin', 'Sarcomeres shorten because actin thin filaments slide over stationary myosin thick filaments, powered by ATP hydrolysis', 'Myosin filaments lengthen to pull the Z-lines apart', 'Calcium causes the sarcomere membrane to contract'], ans: 1, exp: 'During muscle contraction, myosin heads bind actin, perform a power stroke (moving actin toward the M-line), then detach and reset using ATP. Because thin (actin) filaments slide inward, the H-zone and I-band shorten while the A-band length stays constant. The Z-lines are pulled together, shortening the sarcomere.' },
      { q: 'Which part of the nephron is primarily responsible for reabsorbing glucose and amino acids from the filtrate?', opts: ['Collecting duct', 'Loop of Henle', 'Proximal convoluted tubule', 'Distal convoluted tubule'], ans: 2, exp: 'The proximal convoluted tubule (PCT) reabsorbs approximately 65–70% of filtered water, virtually all glucose, amino acids, and a large portion of Na⁺ and Cl⁻. This occurs via sodium-coupled cotransporters on the luminal membrane. Under normal blood glucose levels, no glucose appears in urine; in diabetes, when blood glucose exceeds the renal threshold, glucose spills into the urine.' },
    ],
  },
  {
    id: 'med-genetics',
    name: 'Genetics & Molecular Biology',
    grade: 10, term: 'Fall', credits: 0.5,
    description: 'Modern medicine is increasingly molecular. This course covers the principles of heredity — from Mendelian genetics through the molecular mechanics of DNA replication, transcription, and translation — and connects them directly to human disease, pharmacogenomics, and the biotechnology that underlies diagnostic testing and gene therapy. Understanding genetics is now a prerequisite for understanding virtually every area of clinical medicine.',
    syllabus: {
      objectives: [
        'Solve Mendelian genetics problems including dihybrid crosses, incomplete dominance, codominance, and sex-linked traits',
        'Explain the molecular structure of DNA and RNA and describe how each nucleotide base pairs',
        'Describe the steps of DNA replication, identifying key enzymes including helicase, primase, DNA polymerase, and ligase',
        'Trace the central dogma from gene to protein: transcription (including RNA processing) and translation (initiation, elongation, termination)',
        'Connect mutations, epigenetics, and gene regulation to human genetic diseases and cancer biology',
      ],
      units: [
        { week: '1–2',   topic: 'Mendelian Genetics',              desc: 'Gregor Mendel\'s experiments. Dominant and recessive alleles. Monohybrid and dihybrid crosses, Punnett squares, probability rules. Incomplete dominance, codominance, multiple alleles (ABO blood type), and polygenic traits.' },
        { week: '3–4',   topic: 'Chromosomal Inheritance',         desc: 'Sex chromosomes and sex-linked traits. X-inactivation (Lyon hypothesis). Autosomal vs. X-linked patterns of inheritance. Chromosomal abnormalities: Down syndrome (trisomy 21), Turner syndrome, Klinefelter syndrome. Karyotyping.' },
        { week: '5–6',   topic: 'DNA Structure & Replication',     desc: 'Watson-Crick double helix: nucleotide structure, antiparallel strands, base pairing (A-T, G-C). Replication: helicase unwinds, primase lays RNA primer, DNA polymerase III extends (5\'→3\'), leading vs. lagging strand synthesis, Okazaki fragments, DNA ligase. Proofreading and repair.' },
        { week: '7–8',   topic: 'Transcription & RNA Processing',  desc: 'RNA polymerase, promoters, and transcription factors. Pre-mRNA synthesis, 5\' cap and 3\' poly-A tail addition. RNA splicing: introns removed, exons joined by spliceosomes. Alternative splicing and its role in protein diversity.' },
        { week: '9–10',  topic: 'Translation & the Genetic Code',  desc: 'Codons and anticodons. tRNA charging (aminoacyl-tRNA synthetases). Ribosome structure (small and large subunits, A, P, E sites). Initiation, elongation (peptidyl transferase activity), termination. Post-translational modifications.' },
        { week: '11–12', topic: 'Gene Regulation',                 desc: 'Prokaryotic regulation: the lac operon (inducible) and trp operon (repressible). Eukaryotic regulation: transcription factors, enhancers, silencers, histone modification, DNA methylation (epigenetics). microRNA and post-transcriptional regulation.' },
        { week: '13–14', topic: 'Mutations & Genetic Disease',     desc: 'Point mutations (missense, nonsense, silent), frameshift mutations (insertions/deletions). Mutagens and DNA repair mechanisms. Single-gene diseases: sickle cell anemia (molecular basis), cystic fibrosis, Huntington\'s disease. Oncogenes and tumor suppressor genes.' },
        { week: '15–16', topic: 'Biotechnology & Genomics',        desc: 'Restriction enzymes, gel electrophoresis, PCR, Southern blotting, DNA sequencing (Sanger and next-generation). CRISPR-Cas9 gene editing. The Human Genome Project and genomic medicine. Ethical issues in genetic testing and gene therapy.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PL3EED4C1D684D3ADF', title: 'Crash Course Biology — Genetics Episodes', channel: 'Crash Course', note: 'Episodes 9–17 cover Mendelian genetics, DNA, transcription, translation, and genetic engineering. Watch alongside each weekly unit.' },
      { url: 'https://www.khanacademy.org/science/ap-biology/heredity', title: 'AP Biology — Heredity Unit', channel: 'Khan Academy', note: 'Khan Academy\'s genetics content is MCAT-quality. Work through all the heredity and molecular genetics exercises.' },
      { url: 'https://www.hhmi.org/biointeractive/dna-structure-3d-animation', title: 'HHMI BioInteractive — DNA Replication & Protein Synthesis Animations', channel: 'HHMI BioInteractive', note: 'Studio-quality 3D animations of DNA replication and transcription/translation. Watch before the Week 5–10 units.' },
      { url: 'https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/', title: 'MIT OCW 7.01 — Genetics & Molecular Biology Lectures', channel: 'MIT OpenCourseWare', note: 'MIT\'s introductory biology genetics lectures and problem sets provide genuine college-level rigor. Particularly valuable for the mutation and gene regulation units.' },
    ],
    quiz: [
      { q: 'In a cross between two individuals who are heterozygous for a recessive disorder (Aa × Aa), what is the probability of producing an affected offspring?', opts: ['25%', '50%', '75%', '0%'], ans: 0, exp: 'A Punnett square of Aa × Aa gives genotype ratios: 1 AA : 2 Aa : 1 aa. The homozygous recessive (aa) genotype, which causes the disorder, appears in 1 out of 4 offspring — a 25% probability.' },
      { q: 'During DNA replication, why is synthesis on the lagging strand discontinuous?', opts: ['DNA polymerase runs out of nucleotides on that strand', 'DNA polymerase can only synthesize in the 5\'→3\' direction, which is away from the replication fork on the lagging strand, requiring repeated re-priming', 'Helicase only unwinds one strand at a time', 'The lagging strand is made of RNA, not DNA'], ans: 1, exp: 'DNA polymerase adds nucleotides only in the 5\'→3\' direction. On the lagging strand, this direction runs away from the replication fork. As the fork opens new template, primase must repeatedly lay short RNA primers, and DNA polymerase synthesizes short Okazaki fragments (~100–200 nucleotides in eukaryotes) between each primer. Ligase then joins the fragments after primer removal.' },
      { q: 'A nonsense mutation in a protein-coding gene most likely causes:', opts: ['A single amino acid substitution with no effect on protein length', 'The introduction of a premature stop codon, producing a truncated (shorter) protein', 'An addition of an extra amino acid to the protein', 'A shift in the reading frame affecting all downstream codons'], ans: 1, exp: 'A nonsense mutation changes a sense codon (one that specifies an amino acid) to a stop codon (UAA, UAG, or UGA). Translation terminates prematurely, producing a truncated protein that usually lacks function. This is the molecular basis of diseases like some forms of Duchenne muscular dystrophy and beta-thalassemia.' },
      { q: 'What is the function of RNA splicing after transcription in eukaryotes?', opts: ['To add the 5\' cap and poly-A tail to the mRNA', 'To remove intron sequences and join exons together to form a continuous coding sequence', 'To translate the mRNA into a protein', 'To wind the mRNA around histones for storage'], ans: 1, exp: 'Eukaryotic genes contain non-coding introns interspersed with coding exons. After the primary transcript (pre-mRNA) is made, the spliceosome (a complex of snRNAs and proteins) recognizes splice sites at intron-exon boundaries, excises the introns, and ligates the exons. The mature mRNA carries only the coding sequence.' },
    ],
  },
  {
    id: 'med-biochem',
    name: 'Biochemistry Fundamentals',
    grade: 10, term: 'Spring', credits: 0.5,
    description: 'Biochemistry is the chemical language of life — and of the MCAT. This course covers the structure and function of biological macromolecules, enzyme kinetics, metabolic pathways, and the thermodynamic principles that govern every chemical reaction inside a cell. Students leave with the molecular-level understanding that is essential for pharmacology, physiology, and clinical medicine.',
    syllabus: {
      objectives: [
        'Describe the four levels of protein structure and explain how each level is stabilized by specific types of chemical bonds and interactions',
        'Explain enzyme kinetics: Michaelis-Menten kinetics, Km, Vmax, and the effects of competitive vs. non-competitive inhibition',
        'Trace the major metabolic pathways of glucose — glycolysis, gluconeogenesis, the citric acid cycle — and identify their key regulatory enzymes',
        'Explain how lipid structure determines membrane properties and how lipoproteins transport fat in the bloodstream',
        'Apply thermodynamic concepts (ΔG, activation energy, Le Chatelier\'s principle) to predict the direction and favorability of biological reactions',
      ],
      units: [
        { week: '1–2',   topic: 'Water, pH, and Buffers',           desc: 'Hydrogen bonds and water\'s unique properties. Acid-base chemistry: pH, pKa, Henderson-Hasselbalch equation. Physiological buffers (bicarbonate system, phosphate buffer). Why blood pH is maintained at 7.35–7.45.' },
        { week: '3–4',   topic: 'Amino Acids & Protein Structure',  desc: 'The 20 standard amino acids: side chain properties (polar, nonpolar, charged). Peptide bond formation. Primary, secondary (α-helix, β-sheet), tertiary (folding driven by hydrophobic effect, disulfide bonds), and quaternary structure. Protein denaturation.' },
        { week: '5–6',   topic: 'Enzyme Kinetics & Regulation',     desc: 'Enzymes as biological catalysts: active sites, induced fit model. Michaelis-Menten equation and its graphical interpretation. Competitive and non-competitive inhibition. Allosteric regulation. Feedback inhibition in metabolic pathways.' },
        { week: '7–8',   topic: 'Carbohydrate Metabolism',          desc: 'Glucose structure and anomers. Glycolysis: 10 steps, key enzymes (hexokinase, PFK-1, pyruvate kinase), ATP and NADH yield, regulation. Gluconeogenesis: substrates, key enzymes that bypass irreversible glycolytic steps. Glycogen synthesis and breakdown.' },
        { week: '9–10',  topic: 'Citric Acid Cycle & Oxidative Phosphorylation', desc: 'Pyruvate dehydrogenase complex. Eight steps of the TCA cycle: substrates, products, enzymes, regulatory points. NADH and FADH₂ as electron donors to the ETC. Proton gradient, chemiosmosis, and ATP synthase structure. P/O ratio.' },
        { week: '11–12', topic: 'Lipid Biochemistry',               desc: 'Fatty acid structure (saturated vs. unsaturated) and nomenclature. Fatty acid oxidation (β-oxidation): cycle of steps, ATP yield calculation. Fatty acid synthesis: acetyl-CoA carboxylase, fatty acid synthase complex. Phospholipids, glycolipids, and cholesterol.' },
        { week: '13–14', topic: 'Nucleotide Metabolism & Vitamins', desc: 'Purine and pyrimidine biosynthesis pathways (de novo vs. salvage). Why methotrexate (used in cancer and autoimmune disease) inhibits dihydrofolate reductase. Coenzymes derived from vitamins: NAD⁺/NADH (niacin), FAD/FADH₂ (riboflavin), coenzyme A (pantothenate).' },
        { week: '15–16', topic: 'Biochemistry of Disease',          desc: 'Enzyme deficiency diseases: PKU (phenylalanine hydroxylase), Gaucher disease (glucocerebrosidase), Lesch-Nyhan syndrome (HGPRT). How drug mechanisms are rooted in biochemistry: statins (HMG-CoA reductase inhibitors), penicillin (cell wall synthesis inhibition), aspirin (COX inhibitor).' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PLbKSbFnKYVY3D2KsMILCJBTOj-nkqEXL-', title: 'Crash Course Chemistry — Organic & Biochemistry Episodes', channel: 'Crash Course', note: 'Episodes on organic chemistry and carbon compounds build the foundation for biochemistry. Supplement with the Biology episodes on metabolism.' },
      { url: 'https://www.khanacademy.org/test-prep/mcat/biomolecules', title: 'MCAT — Biomolecules & Metabolism', channel: 'Khan Academy MCAT Prep', note: 'Khan Academy\'s MCAT biochemistry section covers amino acids, enzymes, and metabolic pathways at exactly the right level. Complete all exercises.' },
      { url: 'https://www.hhmi.org/biointeractive/exploring-enzyme-kinetics', title: 'HHMI BioInteractive — Enzyme Kinetics', channel: 'HHMI BioInteractive', note: 'Interactive enzyme kinetics simulations allow you to manipulate substrate concentration and inhibitor type to see Michaelis-Menten curves respond in real time.' },
      { url: 'https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/', title: 'MIT OCW 7.01 — Biochemistry & Metabolism Modules', channel: 'MIT OpenCourseWare', note: 'MIT\'s problem sets on metabolic pathways and enzyme kinetics are excellent practice. The exam problems are especially useful for building analytical skills.' },
    ],
    quiz: [
      { q: 'An enzyme has a Km of 2 mM and a Vmax of 100 μmol/min. When substrate concentration equals 2 mM, the reaction rate is:', opts: ['100 μmol/min (Vmax)', '25 μmol/min (Vmax/4)', '50 μmol/min (Vmax/2)', '75 μmol/min (3Vmax/4)'], ans: 2, exp: 'By definition, Km is the substrate concentration at which reaction rate equals exactly half of Vmax. This is derived from the Michaelis-Menten equation: v = (Vmax × [S]) / (Km + [S]). When [S] = Km: v = (Vmax × Km) / (Km + Km) = Vmax/2 = 50 μmol/min.' },
      { q: 'A competitive inhibitor of an enzyme:', opts: ['Binds irreversibly to the enzyme\'s active site and permanently reduces Vmax', 'Binds the active site and competes with substrate; high substrate concentrations can overcome the inhibition', 'Binds an allosteric site and changes the enzyme\'s shape, reducing both Vmax and Km', 'Covalently modifies the substrate so it cannot be processed'], ans: 1, exp: 'A competitive inhibitor is structurally similar to the substrate and competes for the same active site. It increases the apparent Km (lower affinity) but does not change Vmax — adding enough substrate eventually overwhelms the inhibitor. Non-competitive inhibitors bind a different (allosteric) site and reduce Vmax without affecting Km.' },
      { q: 'Which of the following is the net equation for glycolysis (one glucose → two pyruvate)?', opts: ['Glucose + 2 ATP → 2 pyruvate + 4 ADP + 2 NADH', 'Glucose + 2 NAD⁺ + 2 ADP + 2 Pᵢ → 2 pyruvate + 2 NADH + 2 ATP + 2 H₂O', 'Glucose + 6 O₂ → 6 CO₂ + 6 H₂O + 32 ATP', 'Glucose + 2 ADP → 2 lactate + 2 ATP'], ans: 1, exp: 'Glycolysis has an investment phase (uses 2 ATP) and a payoff phase (produces 4 ATP and 2 NADH). Net yield: 2 ATP and 2 NADH per glucose. The equation: Glucose + 2 NAD⁺ + 2 ADP + 2 Pᵢ → 2 pyruvate + 2 NADH + 2 H⁺ + 2 ATP + 2 H₂O.' },
      { q: 'What is the primary structural difference between saturated and unsaturated fatty acids, and how does this affect membrane fluidity?', opts: ['Saturated fatty acids have double bonds; unsaturated do not — making saturated membranes more fluid', 'Unsaturated fatty acids contain one or more C=C double bonds (cis configuration) that create kinks, preventing tight packing and increasing membrane fluidity compared to saturated fatty acids', 'The difference is in chain length, not double bonds — longer chains are less fluid', 'Saturated fatty acids have hydroxyl groups that attract water, making them more fluid'], ans: 1, exp: 'Saturated fatty acids have all C–C single bonds, allowing carbon chains to pack tightly via van der Waals interactions — increasing rigidity. Unsaturated fatty acids have one or more cis double bonds, which introduce rigid kinks in the chain, preventing tight packing. Membranes rich in unsaturated fatty acids are more fluid at a given temperature. This is why organisms that live in cold environments (e.g., fish) have higher proportions of unsaturated fatty acids in their membranes.' },
    ],
  },
  {
    id: 'med-apbio',
    name: 'AP Biology',
    grade: 11, term: 'Fall', credits: 1.0,
    description: 'AP Biology is the academic centerpiece of this pathway — the single most important course for a pre-med student\'s high school transcript. It covers all of biology at introductory college depth: evolution, ecology, cellular energetics, genetics, gene expression, and the diversity of life. The AP exam in May can earn college credit and demonstrates to admissions committees that you are ready for university-level science.',
    syllabus: {
      objectives: [
        'Demonstrate mastery of all eight AP Biology units at the level required for a score of 4 or 5 on the AP exam',
        'Apply evidence-based reasoning to analyze experimental data, graphs, and biological scenarios in AP free-response format',
        'Construct mechanistic explanations for evolutionary change using natural selection, genetic drift, gene flow, and mutation',
        'Explain how cell communication pathways (signal transduction) regulate cell responses to environmental stimuli',
        'Synthesize concepts across units — connecting ecology, evolution, genetics, and physiology into an integrated understanding of biology',
      ],
      units: [
        { week: '1–2',   topic: 'Unit 1: Chemistry of Life',        desc: 'Water properties, macromolecules (structure-function relationships for carbohydrates, lipids, proteins, nucleic acids), and the relationship between molecular structure and biological function. Free energy and thermodynamics.' },
        { week: '3–4',   topic: 'Unit 2: Cell Structure & Function', desc: 'Eukaryotic and prokaryotic cell structure. Cell membrane and transport (osmosis, facilitated diffusion, active transport, endocytosis/exocytosis). Cell communication: ligands, receptors, and the three stages of signal transduction (reception, transduction, response).' },
        { week: '5–6',   topic: 'Unit 3: Cellular Energetics',      desc: 'Enzyme structure and catalysis, activation energy, and the effect of temperature and pH. Photosynthesis: light reactions and the Calvin cycle, cyclic vs. non-cyclic photophosphorylation. Cellular respiration: glycolysis, pyruvate oxidation, TCA cycle, oxidative phosphorylation. Fermentation.' },
        { week: '7–8',   topic: 'Units 4–5: Genetics & Gene Expression', desc: 'Mendelian and non-Mendelian inheritance. DNA replication, transcription, translation. Gene regulation in prokaryotes (operon model) and eukaryotes (chromatin remodeling, transcription factors). The role of non-coding RNA. Mutations and their consequences.' },
        { week: '9–10',  topic: 'Unit 6: Gene Expression & Biotechnology', desc: 'Development: cell differentiation and the role of transcription factors. Stem cell biology. Biotechnology applications: gel electrophoresis, PCR, CRISPR, DNA profiling, and recombinant DNA technology. Ethical considerations in genetic technology.' },
        { week: '11–12', topic: 'Unit 7: Natural Selection & Evolution', desc: 'Darwin\'s theory of natural selection. Hardy-Weinberg equilibrium: conditions, equations, and using deviations to detect evolutionary forces (selection, genetic drift, gene flow, mutation, non-random mating). Speciation: allopatric and sympatric. Phylogenetics and cladistics.' },
        { week: '13',    topic: 'Unit 8: Ecology',                  desc: 'Population ecology: exponential and logistic growth, carrying capacity, density-dependent and density-independent factors. Community ecology: species interactions (competition, predation, mutualism, parasitism), succession, and keystone species. Ecosystem ecology: nutrient cycles, energy flow, and the impact of human activity.' },
        { week: '14–16', topic: 'AP Exam Review & Free Response',   desc: 'Full-length practice exams under timed conditions. Targeted review of weak areas. Intensive free-response writing practice: constructing claims, using evidence, and providing reasoning. All eight units revisited through a problem-solving lens.' },
      ],
    },
    resources: [
      { url: 'https://apclassroom.collegeboard.org/', title: 'AP Classroom — Official AP Biology Resources', channel: 'College Board', note: 'The single most important resource. Contains AP Daily videos for every learning objective, progress checks, and official past FRQs. Use throughout the year.' },
      { url: 'https://www.khanacademy.org/science/ap-biology', title: 'AP Biology — Full Course', channel: 'Khan Academy', note: 'Khan Academy\'s AP Biology is structured around the official AP curriculum. Complete all eight units with exercises. Use alongside AP Classroom.' },
      { url: 'https://www.youtube.com/c/AmoebaSisters', title: 'Amoeba Sisters — AP Biology Videos', channel: 'Amoeba Sisters', note: 'High-quality, visually clear videos on every major AP Biology topic. Especially good for genetics, evolution, and cell communication. Watch before each unit.' },
      { url: 'https://www.hhmi.org/biointeractive/explore', title: 'HHMI BioInteractive — AP Biology Labs & Animations', channel: 'HHMI BioInteractive', note: 'HHMI provides research-quality interactive labs aligned with AP Biology — including evolution simulations, gel electrophoresis virtual labs, and more.' },
    ],
    quiz: [
      { q: 'Under Hardy-Weinberg equilibrium, a population has an allele frequency of q = 0.4 for a recessive allele. What is the expected frequency of heterozygotes (Aa)?', opts: ['0.16', '0.36', '0.48', '0.24'], ans: 2, exp: 'If q = 0.4, then p = 1 − q = 0.6. The Hardy-Weinberg equation predicts genotype frequencies: p² (AA) + 2pq (Aa) + q² (aa) = 1. Heterozygote frequency = 2pq = 2 × 0.6 × 0.4 = 0.48. This means 48% of the population would be expected to be heterozygous carriers.' },
      { q: 'In a signal transduction pathway, a G-protein coupled receptor (GPCR) activates adenylyl cyclase. What is the immediate downstream effect?', opts: ['Calcium ions are released from the endoplasmic reticulum', 'ATP is converted to cAMP, which activates protein kinase A', 'The receptor dimerizes and autophosphorylates', 'Phospholipase C cleaves PIP₂ into IP₃ and DAG'], ans: 1, exp: 'When a ligand activates a GPCR, the associated G-protein (Gα subunit) dissociates and activates adenylyl cyclase. Adenylyl cyclase converts ATP to cyclic AMP (cAMP). cAMP is a second messenger that activates Protein Kinase A (PKA), which phosphorylates target proteins and triggers a cellular response.' },
      { q: 'A population of beetles is isolated on an island and experiences a dramatic reduction in population size due to a hurricane. The survivors have different allele frequencies than the original mainland population. This is an example of:', opts: ['Natural selection', 'Gene flow', 'The bottleneck effect (genetic drift)', 'Sympatric speciation'], ans: 2, exp: 'The bottleneck effect is a form of genetic drift occurring when a large population is suddenly reduced to a small number of survivors (e.g., by a disaster). The surviving gene pool may not represent the original population\'s allele frequencies — some alleles may be lost entirely and others overrepresented purely by chance, not because of selective advantage.' },
      { q: 'During the light-dependent reactions of photosynthesis, water is split in a process called photolysis. Which of the following correctly describes what happens to the products of water splitting?', opts: ['Electrons reduce NADP⁺ to NADPH; O₂ is used in the Calvin cycle; H⁺ ions are released outside the thylakoid', 'Electrons replace those lost by oxidized P680 in Photosystem II; O₂ is released as a byproduct; H⁺ ions accumulate in the thylakoid lumen, contributing to the proton gradient that drives ATP synthesis', 'Electrons flow directly to the Calvin cycle; O₂ becomes water again in the stroma; H⁺ is used by rubisco', 'Electrons flow to Photosystem I; H⁺ reduces NADP⁺; O₂ is stored in the vacuole'], ans: 1, exp: 'Photolysis: 2H₂O → 4H⁺ + 4e⁻ + O₂. The electrons replace those energized and lost from the P680 reaction center of Photosystem II. O₂ is released as a byproduct (the source of all atmospheric oxygen). H⁺ ions accumulate in the thylakoid lumen, building the proton gradient that powers ATP synthase (chemiosmosis) to produce ATP.' },
      { q: 'A researcher finds that a mutation in a tumor suppressor gene causes uncontrolled cell division. Why does a loss-of-function mutation in a tumor suppressor cause cancer, while a gain-of-function mutation in a proto-oncogene causes a similar effect?', opts: ['Both types of mutations activate the same signaling pathway', 'Tumor suppressors normally inhibit cell division — losing their function removes the "brakes." Proto-oncogenes normally promote division — gaining function removes the "speed limit." Both outcomes accelerate cell cycling past checkpoints.', 'Only proto-oncogene mutations cause cancer; tumor suppressor mutations cause cell death', 'The mutations affect different tissues and produce different types of cancer that are not related'], ans: 1, exp: 'The cell cycle is controlled by both accelerators and brakes. Proto-oncogenes (e.g., RAS) encode growth-promoting proteins — a gain-of-function mutation (becoming an oncogene) constitutively activates growth signals. Tumor suppressors (e.g., p53, RB) encode proteins that arrest the cell cycle or trigger apoptosis — loss of function removes this control. Cancer typically requires mutations in both types, explaining the "two-hit hypothesis" for tumor suppressors.' },
    ],
  },
  {
    id: 'med-micro',
    name: 'Microbiology & Immunology',
    grade: 11, term: 'Spring', credits: 0.5,
    description: 'Infectious disease and immune dysfunction are at the center of clinical medicine. This course covers the biology of bacteria, viruses, fungi, and parasites — how they cause disease and how the immune system combats them. Students learn the molecular basis of innate and adaptive immunity, the logic of vaccines, and the principles of antibiotic and antiviral drug development. This knowledge is directly applicable to understanding current infectious diseases, autoimmune conditions, and immunosuppression.',
    syllabus: {
      objectives: [
        'Compare and contrast the structure and reproduction strategies of bacteria, viruses, fungi, and parasites',
        'Explain the mechanisms by which pathogens evade host defenses, using specific examples such as influenza antigenic drift and bacterial capsule formation',
        'Describe the components and sequence of events in both the innate and adaptive immune responses',
        'Explain the molecular basis of antibody specificity and how clonal selection generates an adaptive immune response',
        'Analyze how vaccines, antibiotics, and antivirals work at the molecular level, and explain the mechanisms behind antibiotic resistance',
      ],
      units: [
        { week: '1–2',   topic: 'Microbial World & Bacterial Biology', desc: 'Survey of microorganisms: bacteria, archaea, viruses, fungi, protozoa, helminths, prions. Bacterial cell structure: cell wall (gram-positive vs. gram-negative), capsule, flagella, pili, plasmids. Binary fission, bacterial growth curves, and endospore formation.' },
        { week: '3–4',   topic: 'Bacterial Pathogenesis',             desc: 'Koch\'s postulates. Virulence factors: toxins (exotoxins vs. endotoxins), adhesins, invasins, and immune evasion strategies. Case studies: Staphylococcus aureus (toxin-mediated disease), Mycobacterium tuberculosis (intracellular survival), Vibrio cholerae (enterotoxin mechanism).' },
        { week: '5–6',   topic: 'Virology',                          desc: 'Virus structure: capsid, envelope, genome types (DNA/RNA, ss/ds, +/−). Lytic vs. lysogenic cycles. Replication strategies of DNA viruses (e.g., herpesvirus) and RNA viruses (e.g., influenza, HIV). Reverse transcriptase and retroviruses. Antigenic drift vs. antigenic shift in influenza.' },
        { week: '7–8',   topic: 'Innate Immunity',                   desc: 'Physical and chemical barriers: skin, mucus, stomach acid. Pattern recognition receptors (PRRs) and pathogen-associated molecular patterns (PAMPs). Toll-like receptors and downstream signaling. Inflammation: vasodilation, neutrophil recruitment, phagocytosis. Complement system pathways. Natural killer cells and interferons.' },
        { week: '9–10',  topic: 'Adaptive Immunity — Humoral',       desc: 'B lymphocyte development and activation. Antibody structure: variable and constant regions, antigen-binding sites, isotypes (IgM, IgG, IgA, IgE, IgD). Clonal selection and expansion. Plasma cells and memory B cells. Functions of antibodies: neutralization, opsonization, complement activation, ADCC.' },
        { week: '11–12', topic: 'Adaptive Immunity — Cellular',      desc: 'T lymphocyte development in the thymus (positive and negative selection). MHC class I (endogenous antigens → CD8⁺ cytotoxic T cells) vs. MHC class II (exogenous antigens → CD4⁺ helper T cells). Helper T cell subsets: Th1, Th2, Th17, Treg. Cytotoxic T cell mechanism: perforin and granzymes.' },
        { week: '13–14', topic: 'Vaccines & Antimicrobials',         desc: 'Vaccine types: live attenuated, inactivated, subunit, toxoid, mRNA (COVID-19 mechanism). Herd immunity thresholds. Antibiotic mechanisms: cell wall synthesis inhibitors (β-lactams), protein synthesis inhibitors (aminoglycosides, macrolides), DNA replication inhibitors (fluoroquinolones). Mechanisms of antibiotic resistance: β-lactamase, efflux pumps, target modification. Antiviral strategies: nucleoside analogues, protease inhibitors, neuraminidase inhibitors.' },
        { week: '15–16', topic: 'Immune Dysregulation & Clinical Cases', desc: 'Hypersensitivity reactions: Type I (IgE-mediated allergy/anaphylaxis), Type II (cytotoxic), Type III (immune complex), Type IV (delayed/T cell-mediated). Autoimmune disease: molecular mimicry, breakdown of tolerance. HIV pathogenesis: CD4⁺ T cell depletion, AIDS-defining illnesses. Immunosuppression in transplantation.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PLbKSbFnKYVY1GKnBtEkFcMijfEsRVq1gR', title: 'Crash Course Biology — Immune System & Microbes', channel: 'Crash Course', note: 'Crash Course episodes on bacteria, viruses, and the immune system are accurate and engaging. Watch episodes covering microbial biology and immunity.' },
      { url: 'https://www.khanacademy.org/test-prep/mcat/organ-systems/the-immune-system', title: 'MCAT — Immune System Unit', channel: 'Khan Academy MCAT Prep', note: 'Khan Academy\'s MCAT immunology content covers innate and adaptive immunity at the depth required for both this course and future MCAT preparation.' },
      { url: 'https://www.hhmi.org/biointeractive/viral-evolution', title: 'HHMI BioInteractive — Viral Evolution & Immunity Animations', channel: 'HHMI BioInteractive', note: 'HHMI offers animations on HIV replication, flu evolution, and immune response. Scientifically authoritative and visually excellent.' },
      { url: 'https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/', title: 'MIT OCW 7.01 — Immunology & Infectious Disease Modules', channel: 'MIT OpenCourseWare', note: 'MIT biology lectures on microbiology and immunology provide genuine college depth. The problem sets on immune system regulation are particularly challenging and valuable.' },
    ],
    quiz: [
      { q: 'Gram-positive bacteria stain purple in the Gram stain procedure because:', opts: ['They lack an outer membrane, so the crystal violet-iodine complex is retained in the thick peptidoglycan cell wall after decolorization', 'They have an outer membrane that absorbs the safranin counterstain', 'They produce purple pigments as a virulence factor', 'Their lipopolysaccharide (LPS) layer binds crystal violet strongly'], ans: 0, exp: 'Gram-positive bacteria have a thick peptidoglycan layer (20–80 nm) outside the cytoplasmic membrane but no outer membrane. During Gram staining, the crystal violet-iodine complex is trapped in this thick wall after alcohol decolorization. Gram-negative bacteria have a thin peptidoglycan layer plus an outer membrane — the alcohol dissolves the outer membrane, releasing the crystal violet, and the cells take up the safranin counterstain (pink/red).' },
      { q: 'Why must the influenza vaccine be reformulated each year?', opts: ['The vaccine wears off after 12 months', 'Influenza viruses undergo antigenic drift — gradual mutations in the hemagglutinin (HA) and neuraminidase (NA) surface proteins — causing the circulating strains to no longer match the previous vaccine', 'Manufacturing regulations require new vaccines annually', 'The immune system forgets the previous vaccine\'s antigens within a year'], ans: 1, exp: 'Influenza RNA polymerase lacks proofreading activity, so errors accumulate during replication. Mutations in the hemagglutinin and neuraminidase genes gradually change the surface antigens (antigenic drift). As the circulating virus diverges from the vaccine strain, pre-existing antibodies no longer neutralize it effectively. Each year, WHO surveillance tracks circulating strains to predict the best vaccine composition for the coming season.' },
      { q: 'A CD8⁺ cytotoxic T cell recognizes its target because:', opts: ['The target cell displays antigen fragments on MHC class I molecules, which are present on virtually all nucleated cells', 'The target cell secretes chemokines that attract the T cell', 'The T cell receptor binds free antigen in the blood', 'The target cell displays antigen on MHC class II molecules'], ans: 0, exp: 'MHC class I molecules present peptides derived from proteins synthesized within the cell (endogenous antigens) — including viral proteins if the cell is infected. CD8⁺ T cells (cytotoxic T lymphocytes, CTLs) bear T cell receptors that recognize the antigen-MHC I complex. MHC class II presents exogenous antigens and is recognized by CD4⁺ helper T cells. The rule: "CD8 = class I; CD4 = class II."' },
      { q: 'β-lactam antibiotics (like penicillin) kill bacteria by:', opts: ['Disrupting the bacterial cell membrane by inserting into the lipid bilayer', 'Inhibiting transpeptidase enzymes (penicillin-binding proteins) that cross-link peptidoglycan strands, weakening the cell wall and causing lysis in hypotonic environments', 'Blocking the 30S ribosomal subunit to prevent translation', 'Inhibiting DNA gyrase to prevent DNA replication'], ans: 1, exp: 'Bacteria maintain cell wall integrity by cross-linking glycan chains with short peptide bridges — a reaction catalyzed by transpeptidases (also called penicillin-binding proteins, PBPs). β-lactams mimic the D-Ala–D-Ala terminus of the peptide bridge and covalently inactivate PBPs. Without cross-linking, the peptidoglycan weakens. In hypotonic conditions (like body fluids), osmotic pressure causes the bacterium to lyse. Staphylococcal resistance via β-lactamase (which cleaves the β-lactam ring) or MRSA (altered PBP) are clinically critical.' },
    ],
  },
  {
    id: 'med-neuro',
    name: 'Neuroscience & Brain Function',
    grade: 12, term: 'Fall', credits: 0.5,
    description: 'The brain is the most complex object in the known universe — and the least understood organ in clinical medicine. This course explores the cellular and systems-level neuroscience that underlies behavior, sensation, emotion, and cognition, from the ion channels that fire a single neuron to the neural circuits that control movement, vision, memory, and sleep. Students also examine neurological and psychiatric diseases through a mechanistic lens, connecting molecular pathology to clinical symptoms.',
    syllabus: {
      objectives: [
        'Explain the ionic basis of the resting membrane potential and the action potential, including the roles of Na⁺/K⁺ ATPase, voltage-gated Na⁺ channels, and K⁺ channels',
        'Describe how chemical synapses work, including neurotransmitter synthesis, vesicle release, receptor binding, and reuptake or enzymatic degradation',
        'Map the major brain regions to their primary functions and explain how damage to each region produces characteristic clinical signs',
        'Explain the cellular mechanisms of long-term potentiation (LTP) as a synaptic model for learning and memory',
        'Analyze the neurobiology of major neurological and psychiatric conditions, including Parkinson\'s disease, Alzheimer\'s disease, depression, and addiction',
      ],
      units: [
        { week: '1–2',   topic: 'Neuron Structure & Resting Potential', desc: 'Neuron anatomy: soma, dendrites, axon, axon terminals, myelin sheath, nodes of Ranvier. Glial cells: astrocytes, oligodendrocytes, microglia, Schwann cells. Resting membrane potential (−70 mV): Na⁺/K⁺-ATPase, K⁺ leak channels, and the Nernst equation for each ion.' },
        { week: '3–4',   topic: 'Action Potential & Signal Propagation', desc: 'Threshold potential. Opening of voltage-gated Na⁺ channels (depolarization), inactivation, and K⁺ channel opening (repolarization, hyperpolarization). Refractory periods (absolute and relative). Saltatory conduction in myelinated axons. Axon diameter and conduction velocity.' },
        { week: '5–6',   topic: 'Synaptic Transmission',               desc: 'Electrical vs. chemical synapses. Calcium-triggered neurotransmitter release (SNARE complex). Ionotropic receptors (ligand-gated ion channels: fast) vs. metabotropic receptors (GPCRs: slow). Major neurotransmitters: glutamate (excitatory), GABA (inhibitory), dopamine, serotonin, acetylcholine, norepinephrine — synthesis, function, and clinical relevance.' },
        { week: '7–8',   topic: 'Brain Structure & Organization',       desc: 'Embryonic brain development: hindbrain (medulla, pons, cerebellum), midbrain (superior and inferior colliculi, substantia nigra), forebrain (diencephalon: thalamus and hypothalamus; telencephalon: cerebral cortex, basal ganglia, limbic system). Cortical lobes and their functions. Brodmann areas. Blood-brain barrier.' },
        { week: '9–10',  topic: 'Sensory & Motor Systems',              desc: 'Sensory transduction: how photons, sound waves, odorants, and mechanical forces become action potentials. Visual pathway: retina → optic chiasm → lateral geniculate nucleus → primary visual cortex. Somatosensory cortex and homunculus. Motor cortex, descending tracts (corticospinal/pyramidal), basal ganglia circuits, and cerebellar coordination.' },
        { week: '11–12', topic: 'Learning, Memory & Consciousness',     desc: 'Hebbian plasticity and long-term potentiation (LTP): NMDA receptor as a coincidence detector, AMPA receptor trafficking. Hippocampus and spatial/episodic memory. H.M. and the role of the hippocampus in consolidating declarative memory. Sleep stages (NREM and REM) and memory consolidation. Theories of consciousness.' },
        { week: '13–14', topic: 'Neurological & Psychiatric Disease',   desc: 'Parkinson\'s disease: substantia nigra degeneration, dopamine deficiency, Lewy bodies. L-DOPA pharmacology. Alzheimer\'s disease: amyloid-beta plaques, tau tangles, cholinergic hypothesis. Depression: monoamine hypothesis, mechanism of SSRIs and SNRIs. Schizophrenia: dopamine hypothesis. Addiction: mesolimbic reward pathway, ΔFosB.' },
        { week: '15–16', topic: 'Clinical Neuroscience & Neuroethics',  desc: 'Neuroimaging: fMRI, PET, EEG, CT, MRI — what each measures. Reading a basic neurological exam. Case-based learning: stroke (ischemic vs. hemorrhagic, time-critical tPA window), traumatic brain injury (diffuse axonal injury), epilepsy (mechanisms and treatment). Neuroethics: cognitive enhancement, brain-computer interfaces, consciousness in vegetative state patients.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtOAKed_MxxWBNaPno5h3Zs8', title: 'Crash Course Psychology & Neuroscience', channel: 'Crash Course', note: 'Crash Course Psychology episodes on the nervous system, the brain, sensation, and consciousness are accurate and engaging. Watch as an introduction to each unit.' },
      { url: 'https://www.khanacademy.org/test-prep/mcat/organ-systems/neurology', title: 'MCAT — Neurology Unit', channel: 'Khan Academy MCAT Prep', note: 'Khan Academy\'s MCAT neuroscience unit covers action potentials, synaptic transmission, and brain regions at the level tested in college biology and on the MCAT.' },
      { url: 'https://www.hhmi.org/biointeractive/neuroscience', title: 'HHMI BioInteractive — Neuroscience & the Brain', channel: 'HHMI BioInteractive', note: 'HHMI\'s neuroscience resources include animations of action potentials, synaptic transmission, and case studies in neurological disease. Scientifically rigorous.' },
      { url: 'https://ocw.mit.edu/courses/9-01-introduction-to-neuroscience-fall-2007/', title: 'MIT OCW 9.01 — Introduction to Neuroscience', channel: 'MIT OpenCourseWare', note: 'MIT\'s introductory neuroscience course — lecture notes, problem sets, and exams are all freely available. This is genuine college-level material aligned with this course.' },
    ],
    quiz: [
      { q: 'During an action potential, what causes the rapid depolarization of the membrane from −70 mV toward +40 mV?', opts: ['K⁺ ions rushing out of the cell through voltage-gated K⁺ channels', 'Na⁺ ions rushing into the cell through voltage-gated Na⁺ channels that open when threshold (approximately −55 mV) is reached', 'The Na⁺/K⁺-ATPase pump actively pushing Na⁺ into the cell', 'Cl⁻ ions exiting the cell through GABA-gated channels'], ans: 1, exp: 'When the membrane is depolarized to threshold (~−55 mV), voltage-gated Na⁺ channels open. Na⁺ has a high electrochemical gradient driving it into the cell (higher outside concentration + inside negative charge), so it rushes in, rapidly depolarizing the membrane to approximately +40 mV. The Na⁺ channels then inactivate (absolute refractory period), and voltage-gated K⁺ channels open to repolarize the membrane.' },
      { q: 'Long-term potentiation (LTP) at glutamatergic synapses is initiated when:', opts: ['Presynaptic dopamine is released at the same time as postsynaptic serotonin', 'The AMPA receptor is blocked by magnesium at normal resting potential', 'Simultaneous presynaptic glutamate release and postsynaptic depolarization relieve the Mg²⁺ block from NMDA receptors, allowing Ca²⁺ to enter the postsynaptic cell and trigger signaling cascades that strengthen the synapse', 'GABA inhibits the postsynaptic cell long enough for NMDA receptors to reset'], ans: 2, exp: 'NMDA receptors are "coincidence detectors": they require both glutamate binding (from presynaptic activity) and sufficient postsynaptic depolarization (to expel the Mg²⁺ ion that blocks the channel at rest). When both conditions are met, Ca²⁺ enters through NMDA receptors, activating CaMKII and other kinases that phosphorylate existing AMPA receptors, increase AMPA receptor trafficking to the membrane, and initiate gene expression changes for long-lasting synaptic strengthening.' },
      { q: 'In Parkinson\'s disease, the primary neurological lesion is:', opts: ['Loss of acetylcholine neurons in the nucleus basalis of Meynert', 'Degeneration of dopaminergic neurons in the substantia nigra pars compacta, reducing dopamine input to the striatum and disrupting basal ganglia motor circuits', 'Demyelination of corticospinal tract neurons', 'Excessive serotonin activity in the raphe nuclei'], ans: 1, exp: 'Parkinson\'s disease is characterized by progressive loss of dopamine-producing neurons in the substantia nigra pars compacta. These neurons project to the striatum (caudate and putamen) via the nigrostriatal pathway, which is part of basal ganglia circuits regulating movement initiation and suppression. Dopamine deficiency disrupts the balance between direct (movement-promoting) and indirect (movement-suppressing) pathways, producing the hallmark symptoms: bradykinesia, resting tremor, rigidity, and postural instability. L-DOPA, the dopamine precursor, partially restores dopamine levels.' },
      { q: 'A patient suffers a stroke affecting Broca\'s area (left inferior frontal gyrus). The most likely consequence is:', opts: ['Loss of ability to understand language (receptive/fluent aphasia)', 'Hemiplegia (paralysis of one side of the body)', 'Non-fluent (expressive) aphasia — difficulty producing speech while language comprehension remains relatively intact', 'Loss of visual field on the right side'], ans: 2, exp: 'Broca\'s area is the speech production center. Damage produces Broca\'s aphasia (expressive aphasia) — patients know what they want to say but produce halting, non-fluent speech with preserved comprehension. Wernicke\'s area (posterior superior temporal gyrus) handles language comprehension; its damage produces fluent but meaningless speech with poor comprehension (Wernicke\'s aphasia). These two areas are connected by the arcuate fasciculus.' },
    ],
  },
  {
    id: 'med-capstone',
    name: 'Biomedical Research Capstone',
    grade: 12, term: 'Spring', credits: 1.0,
    description: 'The Biomedical Research Capstone is the culminating experience of the Pre-Medicine pathway. Students identify a biomedical question, conduct a structured literature review, design and execute an original research project (laboratory or computational), analyze data with appropriate statistical methods, and present findings in a format modeled on scientific publication and medical conference presentation. This capstone mirrors the research experience that top pre-med programs value — and produces the centerpiece of a college application.',
    syllabus: {
      objectives: [
        'Formulate a testable hypothesis grounded in a critical review of peer-reviewed scientific literature',
        'Design an experimental or computational study with appropriate controls, variables, and sample size considerations',
        'Collect, organize, and analyze data using descriptive and inferential statistics, including t-tests, chi-square tests, and graphical representation',
        'Write a scientific paper in IMRaD format (Introduction, Methods, Results, and Discussion) meeting the standards of a student research journal',
        'Present and defend research findings in a professional oral presentation, responding to questions from a faculty panel',
      ],
      units: [
        { week: '1–2',   topic: 'Scientific Literature & Research Ethics', desc: 'How to read a scientific paper. PubMed and Google Scholar search strategies. Evaluating source quality: peer review, impact factor, replication. Research ethics: informed consent, IRB principles, data integrity, responsible authorship, and avoiding plagiarism.' },
        { week: '3–4',   topic: 'Research Question & Hypothesis',    desc: 'Identifying a researchable gap. Moving from broad interest (e.g., "cancer") to a specific, testable hypothesis. PICO framework (Population, Intervention, Comparison, Outcome) for clinical questions. Writing a specific, measurable, achievable, relevant, and time-bound (SMART) hypothesis.' },
        { week: '5–6',   topic: 'Experimental Design',              desc: 'Independent, dependent, and controlled variables. Control groups and experimental groups. Sources of bias: selection bias, measurement bias, confounding variables. Sample size and statistical power. Randomization and blinding in clinical trials. Designing an experiment feasible in a high school setting.' },
        { week: '7–8',   topic: 'Data Collection & Lab Methods',    desc: 'Laboratory safety and documentation. Proper use of pipettes, microscopes, spectrophotometers, and centrifuges. Electronic laboratory notebook maintenance. Basic molecular techniques: PCR setup, gel electrophoresis, enzyme assays, cell culture (as available). For computational projects: accessing public databases (NCBI, UniProt, PDB).' },
        { week: '9–10',  topic: 'Data Analysis & Statistics',       desc: 'Descriptive statistics: mean, median, standard deviation, standard error of the mean. Data visualization: scatter plots, bar graphs with error bars, box plots. Inferential statistics: t-test (two-sample, paired), chi-square test, p-value interpretation, and confidence intervals. Introduction to R or Excel for statistical analysis.' },
        { week: '11–12', topic: 'Scientific Writing — IMRaD',       desc: 'Introduction: background, significance, hypothesis, and aims. Methods: reproducibility standard — write so another scientist can replicate exactly. Results: present data without interpretation; figure and table design. Discussion: interpret results, compare to literature, address limitations, and propose future directions. Abstract: the hardest 250 words.' },
        { week: '13–14', topic: 'Peer Review & Revision',           desc: 'Exchange manuscripts with a peer for structured review using a rubric modeled on journal peer review. Provide constructive written critique. Revise manuscript in response to reviewer comments. Second revision for final submission. Understanding the publication process.' },
        { week: '15–16', topic: 'Research Presentation & Defense',  desc: 'Prepare a 15-minute oral presentation with slides in the format of a scientific conference talk. Design a research poster as an alternative or supplement. Practice with peers and receive feedback. Final public presentation and Q&A with faculty panel. Celebrate your scientific contribution.' },
      ],
    },
    resources: [
      { url: 'https://www.youtube.com/playlist?list=PLbKSbFnKYVY3pNGzsqKbXOAB6UJjN2ZPO', title: 'Crash Course — Statistics & Study Design', channel: 'Crash Course', note: 'Crash Course Statistics covers study design, statistical inference, and data visualization in accessible videos. Watch the relevant episodes alongside the data analysis unit.' },
      { url: 'https://www.khanacademy.org/math/statistics-probability', title: 'Statistics & Probability — Full Course', channel: 'Khan Academy', note: 'Review or learn hypothesis testing, confidence intervals, and statistical significance. Complete the inferential statistics unit before Week 9.' },
      { url: 'https://www.hhmi.org/biointeractive/biointeractive-data-analysis', title: 'HHMI BioInteractive — Data Analysis & Scientific Process', channel: 'HHMI BioInteractive', note: 'HHMI provides real datasets from published research and guides students through analysis — excellent preparation for independent research. Includes activities on graphing, statistics, and interpreting results.' },
      { url: 'https://ocw.mit.edu/courses/res-7-001-pre-7.01-getting-up-to-speed-in-biology-summer-2019/', title: 'MIT OCW — Scientific Methods in Biology', channel: 'MIT OpenCourseWare', note: 'MIT research methodology resources help students understand how professional scientists approach experimental design and data analysis. Particularly useful for the hypothesis and design units.' },
    ],
    quiz: [
      { q: 'A researcher tests whether a new drug lowers blood pressure. She measures systolic blood pressure in 30 patients before and after treatment. Which statistical test is most appropriate?', opts: ['Two-sample independent t-test comparing two different groups', 'Paired t-test comparing the same subjects before and after treatment', 'Chi-square test of independence', 'One-sample z-test comparing to a population mean'], ans: 1, exp: 'A paired t-test is appropriate when the same subjects are measured twice (before and after an intervention). It accounts for individual variability by analyzing the difference in each subject\'s measurements, increasing statistical power compared to an independent t-test. A two-sample t-test would be used if the study compared two separate groups (e.g., drug group vs. placebo group from different individuals).' },
      { q: 'In an experiment, a researcher finds p = 0.03. What does this mean?', opts: ['There is a 3% chance the drug works', 'The effect size is 3%', 'If the null hypothesis were true, there is a 3% chance of obtaining results at least as extreme as those observed — below the conventional α = 0.05 threshold, so the null hypothesis is rejected', 'The study has a 97% power to detect the effect'], ans: 2, exp: 'A p-value is the probability of obtaining a result as extreme as or more extreme than what was observed, assuming the null hypothesis is true. A p-value of 0.03 means there is a 3% chance of seeing results this extreme by random chance if the null hypothesis (no effect) were correct. Since 0.03 < 0.05 (the conventional alpha level), we reject the null hypothesis and call the result statistically significant. This does NOT mean there is a 97% chance the drug works.' },
      { q: 'Which section of a scientific paper (IMRaD format) should present data without interpretation?', opts: ['Introduction', 'Methods', 'Results', 'Discussion'], ans: 2, exp: 'The Results section presents data objectively — tables, figures, and statistical outcomes — without drawing conclusions or comparing to other studies. Interpretation belongs in the Discussion, where you explain what the results mean, why they are significant, how they compare to prior work, and what limitations apply. Separating Results from Discussion is a fundamental principle of scientific writing.' },
      { q: 'A study finds that ice cream sales are strongly correlated (r = 0.91) with drowning deaths. The most accurate interpretation is:', opts: ['Eating ice cream increases the risk of drowning', 'Drowning causes people to crave ice cream', 'Ice cream and drowning are correlated because both are associated with a confounding variable — hot weather increases both ice cream sales and swimming activity', 'This is a statistically significant causal relationship'], ans: 2, exp: 'This is a classic confounding variable example. Hot weather (the confounder) increases both ice cream consumption and outdoor swimming — the two variables are correlated because they share a common cause, not because one causes the other. Correlation does not imply causation. Establishing causality requires controlled experimental design that eliminates confounders, or rigorous observational study designs such as cohort studies with multivariate adjustment.' },
      { q: 'What is the purpose of a control group in an experiment?', opts: ['To ensure all participants receive the treatment', 'To provide a baseline comparison that allows the researcher to attribute any observed difference to the experimental treatment rather than to other factors', 'To double the sample size and increase statistical power', 'To blind the researcher to which group participants are in'], ans: 1, exp: 'A control group receives no treatment (or a placebo) and is otherwise treated identically to the experimental group. Any difference between the groups can then be attributed to the treatment variable. Without a control, there is no way to determine whether observed changes would have occurred naturally, due to the placebo effect, or for other uncontrolled reasons. Well-designed controls are the foundation of valid experimental inference.' },
    ],
  },
];

export default function PreMedPathway() {
  return <PathwayPage meta={META} schedule={SCHEDULE} courses={COURSES} />;
}
