import React from 'react';
import { PathwayPage } from './PathwayComponents';

const COLOR = '#5b2c6f';

const META = {
  color: COLOR,
  title: 'Psychology & Behavioral Science',
  subtitle: 'Understand the human mind. Change the world.',
  emoji: '🧠',
  courseEmoji: '🧠',
  heroDescription: 'A structured 4-year pathway for students interested in psychology, counseling, social work, neuroscience, or behavioral economics. Each course builds directly on the last — by graduation, you will have a college-level foundation and an original research paper.',
  targets: ['Psychology / Clinical Psychology', 'Counseling & Social Work', 'Neuroscience & Cognitive Science', 'Behavioral Economics', 'Education & Child Development'],
  collegeNote: 'Completing this pathway demonstrates sustained academic commitment to your intended field. Your AP Psychology credit, Capstone research paper, Research Methods foundation, and the breadth of your 4-year course sequence tell a clear, compelling story to admissions committees.',
};

const SCHEDULE = [
  { grade: 9, term: 'Fall', courses: [
    { name: 'English I',                    type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra I',                    type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Biology',                      type: 'core',      credits: 1.0, dept: 'Science', note: 'Biopsychology foundation' },
    { name: 'World History',                type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Physical Education',           type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Introduction to Psychology',   type: 'pathway',   credits: 0.5, courseId: 'intro-psych' },
  ]},
  { grade: 9, term: 'Spring', courses: [
    { name: 'English I — Writing',          type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Geometry',                     type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Environmental Science',        type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Geography',                    type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Health & Wellness',            type: 'core',      credits: 0.5, dept: 'Health & PE' },
    { name: 'Human Development',            type: 'pathway',   credits: 0.5, courseId: 'human-development' },
  ]},
  { grade: 10, term: 'Fall', courses: [
    { name: 'English II',                   type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Algebra II',                   type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Chemistry',                    type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'U.S. History',                 type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Psychology Foundations',       type: 'pathway',   credits: 0.5, courseId: 'psych-foundations' },
    { name: 'Introduction to Communication',type: 'supporting', credits: 0.5, dept: 'Communication' },
  ]},
  { grade: 10, term: 'Spring', courses: [
    { name: 'English II — Literature',      type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Pre-Calculus',                 type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Physics Fundamentals',         type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'World Politics',               type: 'core',      credits: 0.5, dept: 'Social Studies' },
    { name: 'Social Psychology',            type: 'pathway',   credits: 0.5, courseId: 'social-psych' },
    { name: 'Public Speaking',              type: 'supporting', credits: 0.5, dept: 'Communication' },
  ]},
  { grade: 11, term: 'Fall', courses: [
    { name: 'English III',                  type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Statistics',                   type: 'supporting', credits: 1.0, dept: 'Mathematics', note: 'Essential for research methods' },
    { name: 'Biology — Advanced',           type: 'core',      credits: 1.0, dept: 'Science' },
    { name: 'Economics',                    type: 'core',      credits: 1.0, dept: 'Social Studies' },
    { name: 'AP Psychology',                type: 'pathway',   credits: 1.0, courseId: 'ap-psychology' },
  ]},
  { grade: 11, term: 'Spring', courses: [
    { name: 'English III — Literature',     type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Trigonometry',                 type: 'core',      credits: 1.0, dept: 'Mathematics' },
    { name: 'Government',                   type: 'core',      credits: 1.0, dept: 'Social Studies' },
    { name: 'Cognitive Psychology',         type: 'pathway',   credits: 0.5, courseId: 'cognitive-psych' },
    { name: 'Research Methods in Social Science', type: 'pathway', credits: 1.0, courseId: 'research-methods' },
  ]},
  { grade: 12, term: 'Fall', courses: [
    { name: 'English IV — Writing & Comm.', type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'AP Statistics',                type: 'supporting', credits: 1.0, dept: 'Mathematics', note: 'Recommended for psych majors' },
    { name: 'Psychology Seminar / Capstone',type: 'pathway',   credits: 1.0, courseId: 'psych-capstone' },
    { name: 'Behavioral Science',           type: 'pathway',   credits: 0.5, courseId: 'behavioral-science' },
    { name: 'Ethics & Critical Thinking',   type: 'supporting', credits: 0.5, dept: 'Elective' },
  ]},
  { grade: 12, term: 'Spring', courses: [
    { name: 'English IV — Adv. Composition',type: 'core',      credits: 1.0, dept: 'English Language Arts' },
    { name: 'Personal Finance',             type: 'core',      credits: 0.5, dept: 'Elective' },
    { name: 'Economics Seminar',            type: 'core',      credits: 1.0, dept: 'Social Studies' },
    { name: 'Abnormal Psychology',          type: 'pathway',   credits: 1.0, courseId: 'abnormal-psych' },
    { name: 'Counseling & Mental Health',   type: 'pathway',   credits: 1.0, courseId: 'counseling' },
  ]},
];

const COURSES = [
  {
    id: 'intro-psych', grade: 9, term: 'Fall', credits: 0.5,
    name: 'Introduction to Psychology',
    description: 'Explore the foundations of psychological science — the history, major schools of thought, research methods, and core topics of the field.',
    syllabus: {
      objectives: ['Understand the major schools of psychological thought', 'Apply the scientific method to psychological questions', 'Build a working vocabulary of core psychological concepts', 'Identify landmark studies in psychology history'],
      units: [
        { week: 1, topic: 'What is Psychology?', desc: 'History and major schools (Behaviorism, Psychoanalysis, Humanistic, Cognitive, Biological).' },
        { week: 2, topic: 'Research Methods', desc: 'Experiments, surveys, naturalistic observation; variables, hypotheses, ethical guidelines.' },
        { week: 3, topic: 'The Brain & Nervous System', desc: 'Neurons, neurotransmitters, brain structures and their behavioral roles.' },
        { week: 4, topic: 'Sensation & Perception', desc: 'Sensory thresholds, signal detection, perceptual illusions.' },
        { week: 5, topic: 'States of Consciousness', desc: 'Sleep stages, REM, dreams, hypnosis, psychoactive drugs.' },
        { week: 6, topic: 'Learning', desc: 'Classical conditioning (Pavlov), operant conditioning (Skinner), observational learning (Bandura).' },
        { week: 7, topic: 'Memory', desc: 'Encoding, storage, retrieval; short-term vs. long-term memory; forgetting.' },
        { week: 8, topic: 'Thinking, Language & Intelligence', desc: 'Concepts, problem solving, heuristics, intelligence theories.' },
        { week: 9, topic: 'Motivation & Emotion', desc: "Maslow's hierarchy, emotion theories. Review & Assessment." },
      ],
    },
    resources: [
      { title: 'Crash Course Psychology — Episodes 1–9', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+psychology+playlist', note: 'Best intro series on YouTube.' },
      { title: 'Introduction to Psychology', channel: 'Khan Academy', url: 'https://www.khanacademy.org/science/ap-psychology', note: 'Free full course with exercises.' },
      { title: 'How Memories Form and How We Lose Them', channel: 'TED-Ed', url: 'https://www.youtube.com/results?search_query=TED-Ed+how+memories+form+and+how+we+lose+them', note: 'Clear animated memory explainer.' },
      { title: 'The Science of Thinking', channel: 'Veritasium', url: 'https://www.youtube.com/results?search_query=veritasium+science+of+thinking', note: 'Engaging intro to cognitive biases.' },
    ],
    quiz: [
      { q: 'Wilhelm Wundt founded psychology\'s first laboratory in 1879 because he:', opts: ['Published "The Interpretation of Dreams"', 'Wanted to study mental processes scientifically using controlled experiments', 'Developed classical conditioning theory', 'Proposed stages of cognitive development'], ans: 1, exp: 'Wundt opened the first formal psychology lab in Leipzig — marking psychology\'s birth as a scientific discipline.' },
      { q: 'Which research method observes behavior in natural settings without intervention?', opts: ['Case study', 'Naturalistic observation', 'Survey', 'Laboratory experiment'], ans: 1, exp: 'Naturalistic observation records behavior as it occurs without manipulation.' },
      { q: 'Pavlov\'s dog experiments demonstrated:', opts: ['Operant conditioning', 'Cognitive dissonance', 'Classical conditioning', 'Observational learning'], ans: 2, exp: 'A neutral stimulus (bell) came to elicit salivation after repeated pairing with food — classical conditioning.' },
      { q: 'Which brain structure primarily governs emotion and memory?', opts: ['Cerebellum', 'Frontal lobe', 'Limbic system', 'Brain stem'], ans: 2, exp: 'The limbic system (amygdala + hippocampus) governs emotion and memory formation.' },
      { q: 'The correct order of memory stages is:', opts: ['Storage → Encoding → Retrieval', 'Encoding → Storage → Retrieval', 'Retrieval → Encoding → Storage', 'Encoding → Retrieval → Storage'], ans: 1, exp: 'Memory: encode (take in) → store → retrieve when needed.' },
      { q: "Maslow's highest need is:", opts: ['Safety', 'Social belonging', 'Esteem', 'Self-actualization'], ans: 3, exp: "Self-actualization — realizing one's full potential — tops Maslow's hierarchy." },
      { q: 'A double-blind study eliminates:', opts: ['Sample size problems', 'Experimenter and participant bias', 'Data errors', 'Sampling issues'], ans: 1, exp: 'Neither participants nor researchers know group assignment — removing expectation bias on both sides.' },
      { q: 'Absolute threshold is:', opts: ['The difference between two detectable stimuli', 'The minimum stimulus detectable 50% of the time', 'The maximum before pain', 'Sensory adaptation'], ans: 1, exp: 'Absolute threshold = minimum stimulation level detectable at least half the time.' },
      { q: 'REM sleep is characterized by:', opts: ['Deepest, hardest to wake', 'Most brain inactivity', 'Vivid dreaming and high brain activity', 'Very slow heart rate'], ans: 2, exp: 'REM features brain activity resembling wakefulness, vivid dreams, and memory consolidation.' },
      { q: "Watson's behaviorism held that psychology should study only:", opts: ['Unconscious drives', 'Observable behavior — not internal mental states', 'Cognitive processes', 'Neurological structures'], ans: 1, exp: 'Watson believed psychology should be purely objective — only studying measurable behavior.' },
    ],
  },
  {
    id: 'human-development', grade: 9, term: 'Spring', credits: 0.5,
    name: 'Human Development',
    description: 'A lifespan course examining physical, cognitive, and social-emotional development from conception through late adulthood — essential background for clinical and educational psychology.',
    syllabus: {
      objectives: ["Apply Piaget's cognitive stages to real scenarios", "Understand Erikson's psychosocial theory across the lifespan", 'Evaluate attachment theory and its long-term effects', "Describe Kohlberg's moral reasoning stages"],
      units: [
        { week: 1, topic: 'Prenatal Development & Infancy', desc: 'Conception, fetal stages, teratogens, newborn reflexes.' },
        { week: 2, topic: "Piaget's Cognitive Stages", desc: 'Sensorimotor, preoperational, concrete operational, formal operational. Object permanence, conservation.' },
        { week: 3, topic: 'Vygotsky & Social Learning', desc: 'Zone of Proximal Development, scaffolding, cultural influences.' },
        { week: 4, topic: 'Attachment Theory', desc: "Bowlby's theory, Ainsworth's Strange Situation, four attachment styles." },
        { week: 5, topic: "Erikson's Psychosocial Stages", desc: 'Eight stages from Trust vs. Mistrust through Ego Integrity vs. Despair.' },
        { week: 6, topic: 'Adolescence', desc: 'Puberty, identity formation (Marcia), peer influence, adolescent brain.' },
        { week: 7, topic: "Kohlberg's Moral Development", desc: 'Preconventional, conventional, postconventional. Gilligan\'s care ethics critique.' },
        { week: 8, topic: 'Adulthood & Aging', desc: 'Early, middle, late adulthood; cognitive aging; life review.' },
        { week: 9, topic: 'Death, Dying & Grief', desc: "Kübler-Ross's DABDA model. Review & Assessment." },
      ],
    },
    resources: [
      { title: 'Development — Crash Course Psychology #18–19', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+psychology+development+adolescence', note: 'Covers Piaget, Erikson, and adolescence.' },
      { title: 'Attachment Theory Explained', channel: 'The School of Life', url: 'https://www.youtube.com/results?search_query=school+of+life+attachment+theory', note: 'Clear explanation of Bowlby and Ainsworth.' },
      { title: "Kohlberg's Moral Reasoning", channel: 'TED-Ed', url: 'https://www.youtube.com/results?search_query=TED-Ed+kohlberg+moral+development', note: 'Animated explainer of moral development stages.' },
      { title: 'Developmental Psychology Unit', channel: 'Khan Academy', url: 'https://www.khanacademy.org/science/ap-psychology', note: 'Navigate to the Development section.' },
    ],
    quiz: [
      { q: "A child in Piaget's preoperational stage lacks:", opts: ['Object permanence', 'Conservation', 'Abstract reasoning', 'Motor coordination'], ans: 1, exp: 'Conservation develops in concrete operations (7–11). Preoperational children think appearance equals quantity.' },
      { q: "Ainsworth's Strange Situation assessed:", opts: ['Cognitive stages', 'Infant attachment styles', 'Language acquisition', 'Moral reasoning'], ans: 1, exp: 'Ainsworth observed infant responses to caregiver departure and return, identifying secure, anxious-avoidant, and anxious-ambivalent styles.' },
      { q: "Erikson's adolescence stage is:", opts: ['Trust vs. Mistrust', 'Industry vs. Inferiority', 'Identity vs. Role Confusion', 'Intimacy vs. Isolation'], ans: 2, exp: 'The central adolescent challenge (12–18) is forming a stable identity.' },
      { q: "Vygotsky's ZPD refers to:", opts: ['Language area of the brain', 'Tasks done independently', 'The gap between independent and guided performance', 'Moral reasoning stages'], ans: 2, exp: 'ZPD = difference between what a learner can do alone vs. with expert guidance (scaffolding).' },
      { q: "Kübler-Ross's grief stages in order:", opts: ['Anger, Denial, Bargaining, Acceptance, Depression', 'Denial, Anger, Bargaining, Depression, Acceptance', 'Denial, Depression, Anger, Bargaining, Acceptance', 'Bargaining, Denial, Anger, Depression, Acceptance'], ans: 1, exp: 'DABDA: Denial → Anger → Bargaining → Depression → Acceptance. Not everyone follows this order.' },
      { q: 'Secure attachment is characterized by:', opts: ['Indifference to caregiver', 'Extreme distress, hard to comfort on reunion', 'Mild distress at separation, quickly comforted on reunion', 'Fear of caregiver'], ans: 2, exp: 'Securely attached infants use the caregiver as a safe base and are easily comforted when reunited.' },
      { q: "Kohlberg's postconventional morality is guided by:", opts: ['Avoiding punishment', 'Maintaining social order', 'Universal ethical principles transcending specific laws', 'Seeking peer approval'], ans: 2, exp: 'Postconventional morality: abstract principles like justice and human rights — beyond any specific rules.' },
      { q: 'Object permanence is the understanding that:', opts: ['Same-looking objects share properties', 'Objects exist even when out of sight', 'Moral judgments depend on intentions', 'Language follows universal grammar'], ans: 1, exp: "Babies develop object permanence around 8–12 months. Before this, 'out of sight' = gone." },
      { q: "Piaget's formal operational stage (12+) enables:", opts: ['Conservation', 'Using symbols', 'Abstract and hypothetical reasoning', 'Make-believe play'], ans: 2, exp: 'Abstract reasoning and systematic logic are hallmarks of formal operations.' },
      { q: '"Empty nest syndrome" describes:', opts: ['Childhood depression', 'School anxiety', "Parents' feelings of loss when adult children leave home", "An Erikson stage"], ans: 2, exp: 'When adult children leave the family home, some parents experience significant emotional adjustment.' },
    ],
  },
  {
    id: 'psych-foundations', grade: 10, term: 'Fall', credits: 0.5,
    name: 'Psychology Foundations',
    description: 'Deepens understanding of personality theory, psychological assessment, stress, and mental health — with a focus on reading and evaluating research evidence.',
    syllabus: {
      objectives: ['Compare major personality theories (psychodynamic, trait, humanistic)', 'Understand DSM-5 classification of psychological disorders', 'Evaluate biological and cognitive treatment approaches', 'Apply stress and coping frameworks to case studies'],
      units: [
        { week: 1, topic: 'Personality — Psychodynamic', desc: "Freud's id/ego/superego, defense mechanisms." },
        { week: 2, topic: 'Personality — Trait & Humanistic', desc: 'Big Five (OCEAN), Rogers, Maslow, self-concept.' },
        { week: 3, topic: 'Measuring Personality', desc: 'Projective tests (Rorschach), self-report inventories, reliability vs. validity.' },
        { week: 4, topic: 'Stress, Health & Coping', desc: "Selye's GAS, eustress vs. distress, coping strategies." },
        { week: 5, topic: 'Classifying Disorders — DSM-5', desc: 'Medical vs. psychological model, cultural considerations, stigma.' },
        { week: 6, topic: 'Anxiety Disorders', desc: 'GAD, Panic Disorder, Social Anxiety, Specific Phobias.' },
        { week: 7, topic: 'Mood Disorders', desc: 'MDD, Persistent Depressive Disorder, Bipolar I & II.' },
        { week: 8, topic: 'Treatment — Psychotherapy', desc: 'CBT, psychoanalytic, humanistic, exposure therapy, DBT.' },
        { week: 9, topic: 'Biological Treatments', desc: 'SSRIs, antipsychotics, mood stabilizers; combined approaches. Review & Assessment.' },
      ],
    },
    resources: [
      { title: 'Crash Course Psychology — Personality & Disorders', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+psychology+personality', note: 'Episodes 35–37 cover personality and disorders.' },
      { title: 'What is Depression?', channel: 'TED-Ed', url: 'https://www.youtube.com/results?search_query=TED-Ed+what+is+depression', note: 'Animated explainer on the biology and experience of depression.' },
      { title: 'The Big Five Personality Traits', channel: 'Psych2Go', url: 'https://www.youtube.com/results?search_query=psych2go+big+five+personality+traits', note: 'Accessible intro to OCEAN.' },
      { title: 'Personality & Disorders Unit', channel: 'Khan Academy', url: 'https://www.khanacademy.org/science/ap-psychology', note: 'Navigate to Personality unit.' },
    ],
    quiz: [
      { q: "Freud's 'id' operates on the:", opts: ['Reality principle', 'Moral principle', 'Pleasure principle', 'Social principle'], ans: 2, exp: 'The id seeks immediate gratification. The ego (reality) and superego (moral) develop to regulate it.' },
      { q: 'The Big Five (OCEAN) traits are:', opts: ['Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism', 'Optimism, Creativity, Energy, Adaptation, Nervousness', 'Openness, Control, Empathy, Awareness, Neuroticism', 'Outcomes, Consistency, Experience, Affect, Neuroticism'], ans: 0, exp: 'OCEAN is the widely accepted five-factor model, supported by cross-cultural research.' },
      { q: 'The DSM-5 is used to:', opts: ['Determine legal responsibility', 'Identify learning disabilities', 'Classify and diagnose mental disorders', 'Price health insurance'], ans: 2, exp: 'DSM-5 provides standardized diagnostic criteria used by clinicians, researchers, and insurance systems.' },
      { q: 'GAD is characterized by:', opts: ['Fear of one specific stimulus', 'Persistent, excessive worry about multiple life domains', 'Recurring intrusive thoughts and rituals', 'Intense fear of social situations'], ans: 1, exp: 'GAD = chronic, difficult-to-control worry about many things lasting at least 6 months.' },
      { q: 'MDD requires symptoms lasting at least:', opts: ['3 days', '1 week', '2 weeks', '1 month'], ans: 2, exp: 'DSM-5: at least 5 symptoms present most of the day, nearly every day, for 2 consecutive weeks.' },
      { q: 'CBT focuses on:', opts: ['Exploring unconscious conflicts', 'Changing maladaptive thought patterns and behaviors', 'Prescribing medication', 'Hypnosis'], ans: 1, exp: 'CBT: thoughts, feelings, and behaviors are interconnected — changing distorted thinking improves outcomes.' },
      { q: 'A projective test assumes people:', opts: ['Can objectively rate their personality', 'Project unconscious feelings onto ambiguous stimuli', 'Follow universal cognitive patterns', 'Are best predicted by genetics'], ans: 1, exp: 'Projective tests use ambiguous stimuli as "screens" for unconscious thoughts and conflicts.' },
      { q: 'Serotonin is most associated with:', opts: ['Fight-or-flight response', 'Motor coordination', 'Mood regulation — low levels linked to depression', 'Memory consolidation'], ans: 2, exp: 'Low serotonin is associated with depression — why SSRIs are the most prescribed antidepressants.' },
      { q: 'Eustress refers to:', opts: ['Chronic unmanageable stress', 'Stress from illness', 'Positive motivating stress', 'Trauma-related stress'], ans: 2, exp: "Eustress is 'good stress' — from exciting challenges that can improve performance." },
      { q: "Self-actualization (Maslow) means:", opts: ['Need to belong to a group', "Achieving one's full potential", 'Drive for food and shelter', 'A defense mechanism'], ans: 1, exp: "Self-actualization is the motivation to realize one's full potential." },
    ],
  },
  {
    id: 'social-psych', grade: 10, term: 'Spring', credits: 0.5,
    name: 'Social Psychology',
    description: "Examines how individuals' thoughts, feelings, and behaviors are shaped by social context — from Milgram's obedience studies to the bystander effect, conformity, prejudice, and relationships.",
    syllabus: {
      objectives: ['Explain how social situations shape individual behavior', 'Analyze landmark studies (Milgram, Asch, Zimbardo) and their ethical implications', 'Apply social psychology to media, politics, and everyday life', 'Evaluate research on prejudice and discrimination'],
      units: [
        { week: 1, topic: 'Situation vs. Disposition', desc: 'How social context powerfully shapes behavior beyond personality.' },
        { week: 2, topic: 'Social Perception & Attribution', desc: 'Fundamental Attribution Error, actor-observer bias, self-serving bias.' },
        { week: 3, topic: 'Attitudes & Persuasion', desc: 'Cognitive dissonance (Festinger), Elaboration Likelihood Model.' },
        { week: 4, topic: 'Conformity', desc: "Asch's line studies, normative vs. informational influence." },
        { week: 5, topic: 'Obedience', desc: "Milgram's shock experiments, Stanford Prison Experiment." },
        { week: 6, topic: 'Prejudice & Discrimination', desc: 'Social identity theory (Tajfel), implicit bias, stereotype threat, contact hypothesis.' },
        { week: 7, topic: 'Group Dynamics', desc: 'Groupthink, social loafing, deindividuation, social facilitation (Zajonc).' },
        { week: 8, topic: 'Prosocial Behavior', desc: "Bystander effect (Darley & Latané), diffusion of responsibility." },
        { week: 9, topic: 'Interpersonal Attraction', desc: "Proximity, mere exposure effect, Sternberg's love theory. Review & Assessment." },
      ],
    },
    resources: [
      { title: 'Social Thinking & Influence — CrashCourse #37–38', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+psychology+social+thinking+influence', note: 'Two essential social psychology episodes.' },
      { title: 'The Milgram Experiment — Deep Dive', channel: 'Vsauce', url: 'https://www.youtube.com/results?search_query=vsauce+milgram+experiment', note: 'Must-watch for understanding obedience and situational power.' },
      { title: 'Why Do We Make Bad Decisions?', channel: 'TED-Ed', url: 'https://www.youtube.com/results?search_query=TED-Ed+why+do+we+make+bad+decisions', note: 'Connects social psychology to everyday judgment.' },
      { title: 'Social Psychology Unit', channel: 'Khan Academy', url: 'https://www.khanacademy.org/science/ap-psychology', note: 'Navigate to Social Psychology for lessons and quizzes.' },
    ],
    quiz: [
      { q: 'The Fundamental Attribution Error is the tendency to:', opts: ['Attribute our own failures externally', "Overestimate personality and underestimate situation in others' behavior", 'Assume others share our beliefs', 'Over-weight first impressions'], ans: 1, exp: "We see our own behavior as situationally driven but others' as reflecting stable traits." },
      { q: "In Asch's experiments, participants gave wrong answers primarily because:", opts: ['They doubted their own perception', 'They feared punishment', 'Social pressure overrode their own judgment', 'They were paid to agree'], ans: 2, exp: 'Most knew the answer was wrong but went along — normative social influence.' },
      { q: "~What % of Milgram's participants administered the maximum shock?", opts: ['25%', '45%', '65%', '90%'], ans: 2, exp: 'About 65% went to 450V — far higher than predicted. The situation overrode personal conscience.' },
      { q: 'Groupthink occurs when:', opts: ['Groups vote secretly', 'Harmony suppresses critical thinking', 'Individuals take more risk in groups', 'Two groups compromise'], ans: 1, exp: 'Groupthink leads to poor decisions — maintaining harmony trumps evaluating alternatives.' },
      { q: 'The Bystander Effect: as bystanders increase, each person is:', opts: ['More likely to help', 'Less likely to help', 'Equally likely to help', 'Faster to respond'], ans: 1, exp: 'Diffusion of responsibility: more bystanders → everyone assumes someone else will act.' },
      { q: 'Cognitive dissonance is discomfort felt when:', opts: ['You have too many choices', 'Your behavior conflicts with your beliefs', "You're excluded from a group", "You fail others' expectations"], ans: 1, exp: "People resolve dissonance by changing attitude, behavior, or rationalizing the conflict." },
      { q: 'The mere exposure effect means:', opts: ['Violence desensitizes over time', 'We like things more just from repeated exposure', 'Attraction requires similarity', 'Public commitment increases conformity'], ans: 1, exp: 'Zajonc (1968): repeated exposure to a stimulus increases liking — even without conscious awareness.' },
      { q: 'In-group bias is the tendency to:', opts: ['Distrust your own group', 'Favor your own group over out-groups', "Blame your group for others' failures", 'Conform to out-group norms'], ans: 1, exp: "Even random group membership leads to in-group favoritism — the core of Tajfel's Social Identity Theory." },
      { q: 'Deindividuation in groups involves:', opts: ['Loss of identity leading to impulsive behavior', 'Forming strong individual opinions', 'Taking personal responsibility', 'Maintaining cultural identity'], ans: 0, exp: 'Reduced self-awareness in crowds increases likelihood of impulsive or antisocial behavior.' },
      { q: 'Social facilitation (Zajonc): audiences impair performance when:', opts: ['Task is simple and well-learned', 'Task is novel or complex', 'Audience is supportive', 'Audience is familiar'], ans: 1, exp: 'Audience arousal enhances dominant responses. For new tasks, the dominant response is wrong → worse performance.' },
    ],
  },
  {
    id: 'ap-psychology', grade: 11, term: 'Fall', credits: 1.0,
    name: 'AP Psychology',
    description: 'College-level psychology covering all major domains — biological bases, learning, memory, cognition, development, personality, abnormal behavior, treatment, and social psychology. Prepares students for the AP exam.',
    syllabus: {
      objectives: ['Master all AP Psychology content areas (College Board)', 'Analyze and evaluate psychological research', 'Apply concepts in AP free-response format', 'Demonstrate understanding of research ethics'],
      units: [
        { week: '1–2', topic: 'History, Approaches & Research Methods', desc: 'Schools of thought, research designs, statistical concepts, APA ethics.' },
        { week: '3–4', topic: 'Biological Bases of Behavior', desc: 'Neurons, neurotransmitters, endocrine system, brain structures, genetics.' },
        { week: '5–6', topic: 'Sensation, Perception & Consciousness', desc: 'Sensory systems, Gestalt, sleep stages, psychoactive drugs.' },
        { week: '7–8', topic: 'Learning & Conditioning', desc: 'Classical (Pavlov), operant (Skinner), observational (Bandura), biological constraints.' },
        { week: '9–10', topic: 'Memory & Cognition', desc: 'Encoding/storage/retrieval, misinformation effect (Loftus), intelligence models.' },
        { week: '11–12', topic: 'Motivation, Emotion & Stress', desc: 'Maslow, drive theories, emotion theories, stress-health connection.' },
        { week: '13–14', topic: 'Developmental Psychology', desc: 'Piaget, Vygotsky, Kohlberg, Erikson, Ainsworth — full review.' },
        { week: '15–16', topic: 'Personality, Testing & Individual Differences', desc: 'Freud, Big Five, Bandura; assessment; intelligence testing; cultural bias.' },
        { week: 17, topic: 'Abnormal Behavior & Treatment', desc: 'DSM-5 categories, major disorders, psychological and biomedical treatments.' },
        { week: 18, topic: 'Social Psychology + AP Exam Prep', desc: 'Conformity, obedience, prejudice. Full practice exams and FRQ strategy.' },
      ],
    },
    resources: [
      { title: 'Crash Course Psychology — Full 40-Episode Playlist', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+psychology+complete+playlist', note: 'Cover the full playlist — maps almost perfectly to AP content.' },
      { title: 'AP Psychology — Full Course', channel: 'Khan Academy', url: 'https://www.khanacademy.org/science/ap-psychology', note: 'Free AP prep with progress tracking.' },
      { title: 'AP FRQ Strategy', channel: 'Marco Learning', url: 'https://www.youtube.com/results?search_query=AP+psychology+free+response+tips+marco+learning', note: 'Critical for exam day — how to answer FRQs correctly.' },
      { title: 'AP Classroom', channel: 'College Board', url: 'https://apclassroom.collegeboard.org', note: 'Official practice questions and progress checks. Required.' },
    ],
    quiz: [
      { q: 'Studying the hippocampus in memory formation reflects which perspective?', opts: ['Psychodynamic', 'Humanistic', 'Behavioral', 'Biological'], ans: 3, exp: 'The biological perspective examines how brain structures, genes, and neurochemistry influence behavior.' },
      { q: 'The JND (difference threshold) is governed by:', opts: ['Signal detection theory', "Weber's Law", 'Law of Effect', 'Yerkes-Dodson Law'], ans: 1, exp: "Weber's Law: JND is a constant proportion of the stimulus." },
      { q: "Garcia & Koelling's taste-aversion showed conditioning is:", opts: ['Unlimited — any stimulus can pair with any response', 'Constrained by biological predispositions', 'Only effective with immediate reinforcement', 'Impossible in a single trial'], ans: 1, exp: 'Animals learn associations more readily aligned with evolutionary survival — challenges the equipotentiality assumption.' },
      { q: 'The misinformation effect (Loftus) shows memory is:', opts: ['Permanently stored accurately', 'Reconstructive and susceptible to post-event information', 'More accurate under stress', 'Stored primarily in the cerebellum'], ans: 1, exp: 'Misleading post-event questions can alter memories — memory is reconstructed, not replayed.' },
      { q: 'Growth mindset (Dweck) means:', opts: ['Intelligence is fixed', 'Effort and learning can develop ability', 'Success requires natural talent', 'Failure signals low intelligence'], ans: 1, exp: 'Growth mindset → embrace challenges, learn from failure, see effort as path to mastery.' },
      { q: 'MDD criteria require symptoms lasting:', opts: ['1 week', '2 weeks', '1 month', '6 months'], ans: 1, exp: 'At least 5 symptoms for 2 consecutive weeks (DSM-5).' },
      { q: 'CBT is based on:', opts: ['Psychoanalytic theory', 'Humanistic principles', "Beck's cognitive model + behavioral learning", 'Biological psychiatry'], ans: 2, exp: "Beck: distorted thinking drives emotional disorders — changing thoughts changes feelings." },
      { q: 'REM sleep features:', opts: ['Deepest sleep', 'Most brain inactivity', 'Vivid dreaming and high brain activity', 'Very slow heart rate'], ans: 2, exp: 'REM brain activity resembles wakefulness; vivid dreams; muscle atonia.' },
      { q: 'In double-blind studies, neither participants nor researchers know:', opts: ['The hypothesis', 'Who is in experimental vs. control group', 'The statistical method', 'The sample size'], ans: 1, exp: 'Eliminates both participant and experimenter expectation bias.' },
      { q: 'Social facilitation: audiences impair performance when:', opts: ['Task is simple and well-learned', 'Task is novel or complex', 'Audience is supportive', 'Audience is familiar'], ans: 1, exp: 'Arousal enhances dominant response. For unfamiliar tasks, dominant response is wrong → worse performance.' },
    ],
  },
  {
    id: 'cognitive-psych', grade: 11, term: 'Spring', credits: 0.5,
    name: 'Cognitive Psychology',
    description: 'Explores how the mind processes information — attention, memory systems, language, problem-solving, decision-making, and cognitive biases, with applications to learning and technology.',
    syllabus: {
      objectives: ["Describe Baddeley's Working Memory Model", 'Distinguish System 1 vs. System 2 thinking (Kahneman)', 'Analyze cognitive biases and real-world consequences', 'Apply cognitive science to effective learning strategies'],
      units: [
        { week: 1, topic: 'The Mind as Information Processor', desc: 'History of cognitive revolution, information processing model, cognitive neuroscience.' },
        { week: 2, topic: 'Attention', desc: 'Selective attention (cocktail party effect), divided attention, inattentional blindness.' },
        { week: 3, topic: "Working Memory — Baddeley's Model", desc: "Central executive, phonological loop, visuospatial sketchpad, episodic buffer. Miller's 7±2." },
        { week: 4, topic: 'Long-Term Memory Systems', desc: 'Explicit (episodic, semantic) vs. implicit (procedural, priming); HM case study.' },
        { week: 5, topic: 'Language & Thought', desc: 'Sapir-Whorf hypothesis, language acquisition (Chomsky vs. Skinner).' },
        { week: 6, topic: 'Problem Solving & Creativity', desc: 'Algorithms vs. heuristics, mental set, functional fixedness, insight.' },
        { week: 7, topic: "Decision Making — Kahneman's Two Systems", desc: 'System 1 vs. System 2; availability, representativeness, anchoring, framing.' },
        { week: 8, topic: 'Cognitive Biases', desc: 'Confirmation bias, hindsight bias, overconfidence, sunk cost fallacy.' },
        { week: 9, topic: 'Applied Cognitive Science', desc: 'Spaced repetition, retrieval practice, interleaving; cognitive load in UX. Review & Assessment.' },
      ],
    },
    resources: [
      { title: 'The Riddle of Experience vs. Memory (Kahneman)', channel: 'TED', url: 'https://www.youtube.com/results?search_query=kahneman+TED+experience+memory', note: "Nobel laureate's talk — required viewing for System 1/2." },
      { title: 'The Invisible Gorilla — Inattentional Blindness', channel: 'YouTube', url: 'https://www.youtube.com/results?search_query=invisible+gorilla+selective+attention+test', note: 'Watch BEFORE reading about it.' },
      { title: 'How to Practice Effectively', channel: 'TED-Ed', url: 'https://www.youtube.com/results?search_query=TED-Ed+how+to+practice+effectively', note: 'Applies cognitive science to skill acquisition.' },
      { title: 'Memory and Cognition Unit', channel: 'Khan Academy', url: 'https://www.khanacademy.org/science/ap-psychology', note: 'Navigate to Cognition unit.' },
    ],
    quiz: [
      { q: "Baddeley's Working Memory Model consists of:", opts: ['Sensory memory, short-term, long-term', 'Central executive, phonological loop, visuospatial sketchpad, episodic buffer', 'Encoding, storage, retrieval', 'Declarative and procedural memory'], ans: 1, exp: 'Baddeley replaced simple short-term memory with a multi-component system that actively manipulates information.' },
      { q: 'The cocktail party effect demonstrates:', opts: ['Divided attention', 'Selective attention — filtering relevant speech from noise', 'Attentional blindness', 'Working memory overload'], ans: 1, exp: 'In a noisy party you can follow one conversation — and your brain alerts you to your own name. Selective attention.' },
      { q: "Kahneman's System 1 is:", opts: ['Slow, deliberate, analytical', 'Fast, automatic, intuitive', 'Working memory-intensive', 'Based on logical deduction'], ans: 1, exp: 'System 1 handles most moment-to-moment decisions automatically. System 2 is effortful conscious reasoning.' },
      { q: 'Confirmation bias is:', opts: ['Overestimating memory accuracy', 'Seeking information confirming existing beliefs', 'Underestimating task difficulty', 'Attributing success to luck'], ans: 1, exp: 'We naturally seek, interpret, and recall info confirming what we already believe.' },
      { q: 'Semantic memory stores:', opts: ['Personal episodic memories', 'General world knowledge and facts', 'Unconscious motor skills', 'Brief sensory impressions'], ans: 1, exp: "Semantic memory = your 'encyclopedia': facts without memory of when you learned them." },
      { q: 'The Sapir-Whorf hypothesis proposes:', opts: ['Language is innate (universal grammar)', 'Language shapes and constrains thought', 'Thought precedes language universally', 'Memory and language are stored separately'], ans: 1, exp: 'Linguistic relativity: the language you speak influences how you perceive and categorize the world.' },
      { q: 'An algorithm vs. a heuristic:', opts: ['Algorithm is faster but less accurate', 'Algorithm guarantees a correct solution; heuristic is a fast shortcut', 'Heuristic guarantees correctness', 'Only heuristics work for complex problems'], ans: 1, exp: 'Algorithms guarantee the answer; heuristics are faster shortcuts that may fail.' },
      { q: 'The availability heuristic judges likelihood by:', opts: ['Statistical base rates', 'How easily examples come to mind', 'Expert consensus', 'Logical analysis'], ans: 1, exp: 'Ease of mental recall ≠ actual probability — Tversky & Kahneman\'s key insight.' },
      { q: 'Neuroplasticity means:', opts: ["Brain can't change after childhood", 'Brain can reorganize and form new connections throughout life', 'Neurons firing action potentials', 'Stress hormone regulation'], ans: 1, exp: 'The brain remains changeable throughout life — learning strengthens synaptic connections.' },
      { q: 'The spacing effect means:', opts: ['Cramming is best for retention', 'Distributed practice outperforms massed practice for long-term retention', 'Same-session repetition is most effective', 'Rest reduces learning'], ans: 1, exp: 'Distributed practice consistently outperforms cramming — one of the most replicable findings in cognitive psychology.' },
    ],
  },
  {
    id: 'research-methods', grade: 11, term: 'Spring', credits: 1.0,
    name: 'Research Methods in Social Science',
    description: 'Teaches the scientific methodology behind psychological research — from hypothesis formation and study design to data collection, statistical analysis, and ethical review. Essential for university psychology.',
    syllabus: {
      objectives: ['Design a complete research study with a testable hypothesis', 'Distinguish experimental, correlational, and qualitative designs', 'Apply basic statistics (correlation, t-test, p-value) to data', 'Apply IRB ethics and informed consent standards'],
      units: [
        { week: '1–2', topic: 'Philosophy of Science & Scientific Method', desc: 'Empiricism, falsifiability (Popper), paradigm shifts (Kuhn), science vs. pseudoscience.' },
        { week: '3–4', topic: 'Research Designs', desc: 'Experimental, correlational, quasi-experimental, qualitative; internal vs. external validity.' },
        { week: '5–6', topic: 'Sampling Methods', desc: 'Random, stratified, convenience, snowball; sampling bias and generalizability.' },
        { week: '7–8', topic: 'Survey & Measurement Design', desc: 'Likert scales, avoiding bias in wording, reliability vs. validity, operational definitions.' },
        { week: '9–10', topic: 'Observational & Qualitative Methods', desc: 'Naturalistic observation, structured interviews, case studies, triangulation.' },
        { week: '11–12', topic: 'Basic Statistics', desc: 'Descriptive stats (mean, SD), correlation, null hypothesis, p-value, Type I & II errors.' },
        { week: '13–14', topic: 'Data Analysis & Interpretation', desc: 'Reading graphs, interpreting output, effect size, practical vs. statistical significance.' },
        { week: '15–16', topic: 'Research Ethics', desc: 'IRB, informed consent, deception, debriefing, historical abuses (Tuskegee, Milgram).' },
        { week: '17–18', topic: 'Presentations & Peer Review', desc: 'Communicating findings, critiquing published research, the replication crisis.' },
      ],
    },
    resources: [
      { title: 'Crash Course Statistics — Episodes 1–12', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+statistics+playlist', note: 'Best free statistics intro.' },
      { title: 'Research Methods in Psychology', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+psychology+research+methods', note: 'Crash Course Psychology #2 covers methods clearly.' },
      { title: 'Google Scholar', channel: 'Google', url: 'https://scholar.google.com', note: 'Find and read actual peer-reviewed articles.' },
      { title: 'APA Ethics Code', channel: 'APA', url: 'https://www.apa.org/ethics/code', note: "The actual ethical standards — required reading for the ethics unit." },
    ],
    quiz: [
      { q: 'The independent variable in an experiment is:', opts: ['What is measured as the outcome', 'What the researcher manipulates', 'An uncontrolled confound', 'The variable held constant'], ans: 1, exp: 'IV = what the researcher controls/manipulates. DV = what is measured.' },
      { q: 'A convenience sample:', opts: ['Is always larger', 'Selects participants based on easy availability, not random selection', 'Is more representative', 'Eliminates sampling bias'], ans: 1, exp: 'Convenience sampling is fast but less representative, limiting generalizability.' },
      { q: 'The null hypothesis states:', opts: ['The predicted effect will occur', 'There is no difference/effect between conditions', 'The alternative hypothesis is false', 'Results are significant'], ans: 1, exp: 'Null hypothesis always assumes no effect. Statistical tests evaluate the probability of your results if this were true.' },
      { q: 'A Type I error (false positive) occurs when:', opts: ['You fail to find a real effect', 'You conclude an effect exists when it does not', 'Your sample is too small', 'Your measurement is unreliable'], ans: 1, exp: 'Type I = false alarm — rejecting a true null hypothesis. Controlled by the alpha level (p < 0.05).' },
      { q: 'Triangulation in qualitative research means:', opts: ['Using exactly three participants', 'Using multiple methods/sources to corroborate findings', 'Drawing a data visualization', 'Applying a three-step statistical test'], ans: 1, exp: 'Triangulation increases credibility by converging evidence from multiple methods.' },
      { q: 'Content validity means a test:', opts: ['Predicts future performance', 'Covers all relevant aspects of the construct', 'Is consistent across administrations', 'Correlates with similar tests'], ans: 1, exp: 'Content validity: does the measure sample the full domain of the construct?' },
      { q: 'An operational definition specifies:', opts: ['How research is funded', 'How an abstract concept is measured in observable, concrete terms', 'Ethical parameters', 'The theoretical framework'], ans: 1, exp: "Operationalization makes abstract concepts measurable. 'Stress' = cortisol level or PSS scale score." },
      { q: 'Stratified random sampling:', opts: ['Selects randomly from the entire population', 'Divides population into subgroups and randomly samples from each', 'Selects all members of naturally occurring groups', 'Chooses the easiest participants'], ans: 1, exp: 'Stratified sampling ensures proportional representation of key subgroups.' },
      { q: 'r = −0.75 indicates:', opts: ['No significant relationship', 'Strong negative relationship', 'Weak positive relationship', 'Perfect inverse relationship'], ans: 1, exp: 'Sign = direction (negative = inverse). Magnitude (0.75) = strong.' },
      { q: 'The p-value represents:', opts: ['Probability the null is true', 'Probability of results this extreme assuming the null is true', 'Effect size', 'Variance explained'], ans: 1, exp: 'p < 0.05: if the null were true, you\'d see results this extreme less than 5% of the time.' },
    ],
  },
  {
    id: 'psych-capstone', grade: 12, term: 'Fall', credits: 1.0,
    name: 'Psychology Seminar / Capstone',
    description: 'Students design and conduct an original research project from start to finish — hypothesis, data collection, analysis, full APA paper, and public presentation. The centerpiece of college applications.',
    syllabus: {
      objectives: ['Design a complete study with ethical approval', 'Write a full APA-format paper (Abstract, Introduction, Method, Results, Discussion)', 'Collect and analyze data using appropriate statistics', 'Present findings in a professional poster session'],
      units: [
        { week: '1–2', topic: 'Research Design Review', desc: 'Choosing the right design for your research question.' },
        { week: '3–4', topic: 'APA Format & Finding Sources', desc: 'APA 7th edition, in-text citations, reference lists, Google Scholar.' },
        { week: '5–6', topic: 'Developing Your Research Question', desc: 'From broad interest to specific testable hypothesis. Literature review workshop.' },
        { week: '7–8', topic: 'Research Ethics', desc: 'IRB process, informed consent, confidentiality, deception, debriefing.' },
        { week: '9–10', topic: 'Data Collection', desc: 'Survey design, interviews, observation coding, self-report limitations.' },
        { week: '11–12', topic: 'Statistical Analysis', desc: 'Applying descriptive stats, correlation, t-test to your own data.' },
        { week: '13–14', topic: 'Writing Results & Discussion', desc: 'Reporting findings, interpreting results, acknowledging limitations.' },
        { week: '15–16', topic: 'Full Paper Drafting', desc: 'Peer review workshop, integrating feedback, revision.' },
        { week: 17, topic: 'Poster Presentations', desc: 'Visual design, presenting findings concisely, responding to questions.' },
        { week: 18, topic: 'Final Submission', desc: 'Final paper due. Reflection on the research process.' },
      ],
    },
    resources: [
      { title: 'APA Format Tutorial (7th Edition)', channel: 'YouTube', url: 'https://www.youtube.com/results?search_query=APA+format+7th+edition+tutorial', note: 'Learn citations, references, and paper structure.' },
      { title: 'Crash Course Statistics', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+statistics+playlist', note: 'Episodes 1–10 cover everything needed.' },
      { title: 'Google Scholar', channel: 'Google', url: 'https://scholar.google.com', note: 'Find peer-reviewed articles for your literature review.' },
      { title: 'APA Ethics Code', channel: 'APA', url: 'https://www.apa.org/ethics/code', note: 'Required for the ethics and IRB unit.' },
    ],
    quiz: [
      { q: 'IRB review ensures:', opts: ['Research gets published', "Participants' rights are protected", 'The study is experimental', 'Funding is available'], ans: 1, exp: "IRBs are ethics committees reviewing human-participant research — required by US federal law." },
      { q: 'The APA Introduction section:', opts: ['Summarizes the findings', 'Reviews existing literature and justifies the study', 'Describes the participants and procedure', 'Interprets the results'], ans: 1, exp: 'The Introduction presents existing research, identifies a gap, and presents the research question.' },
      { q: 'r = −0.85 indicates:', opts: ['Weak positive relationship', 'No relationship', 'Strong negative relationship', 'Perfect positive relationship'], ans: 2, exp: 'Sign = direction (negative = inverse relationship). Magnitude (0.85) = strong.' },
      { q: 'Random assignment controls confounds by:', opts: ['Ensuring a representative population sample', 'Distributing participant differences equally across conditions', 'Increasing external validity', 'Reducing cost'], ans: 1, exp: 'Random assignment is what allows causal conclusions — distinguishing experiments from correlational studies.' },
      { q: 'High reliability + low validity means:', opts: ['Measures its construct consistently', 'Measures consistently but misses the intended construct', 'Varies across administrations', 'Cannot be published'], ans: 1, exp: 'Reliability is necessary but not sufficient. A scale could reliably measure shoe size with zero IQ validity.' },
      { q: 'Informed consent requires:', opts: ['Agreement with the hypothesis', 'Receiving study info and freely choosing to participate', 'Signing a payment contract', 'Staying until completion'], ans: 1, exp: 'Informed consent: disclosure, comprehension, voluntary participation. Participants can withdraw any time.' },
      { q: 'To compare means of two independent groups, use a:', opts: ['Chi-square test', 'Pearson correlation', 'Independent samples t-test', 'ANOVA'], ans: 2, exp: 'The independent samples t-test: tests whether two group means differ more than expected by chance.' },
      { q: 'External validity refers to:', opts: ['Consistency across measurements', 'Generalizability to other populations and settings', 'Whether the study measures what it claims', 'Variable control within the experiment'], ans: 1, exp: 'High internal validity (control) vs. high external validity (generalizability) often trade off.' },
      { q: 'Publication bias means:', opts: ['Only government-funded studies are published', 'Positive/significant results get published; null results do not', 'Qualitative is favored over quantitative', 'Prestigious universities get cited more'], ans: 1, exp: 'If only p < 0.05 results get published, the literature overestimates effect sizes.' },
      { q: 'APA in-text citation for 3+ authors uses:', opts: ['All last names', 'First author + "et al."', 'Only the journal name', 'Only the year'], ans: 1, exp: 'APA 7th edition: (Smith et al., 2020).' },
    ],
  },
  {
    id: 'behavioral-science', grade: 12, term: 'Fall', credits: 0.5,
    name: 'Behavioral Science',
    description: 'Examines human behavior from an interdisciplinary lens — integrating psychology, economics, and sociology to understand decision-making, habit formation, and evidence-based behavior change.',
    syllabus: {
      objectives: ['Apply behavioral economics concepts (loss aversion, nudge theory) to real problems', 'Analyze how defaults and social norms shape population-level behavior', 'Evaluate evidence-based behavior change interventions', 'Design a simple behavior change intervention'],
      units: [
        { week: '1–2', topic: 'What is Behavioral Science?', desc: 'Interdisciplinary origins: psychology + economics + sociology. Rational actor model and its failures.' },
        { week: '3–4', topic: 'Behavioral Economics', desc: 'Loss aversion, status quo bias, anchoring, mental accounting (Kahneman & Tversky, Thaler).' },
        { week: '5–6', topic: 'Nudge Theory & Choice Architecture', desc: "Defaults, salience, social norms, simplification, commitment devices. Thaler & Sunstein's framework." },
        { week: '7–8', topic: 'Habit Formation & Behavior Change', desc: "Duhigg's habit loop, Fogg Behavior Model, implementation intentions." },
        { week: 9, topic: 'Applied Behavioral Science', desc: 'Applications in public health, policy, UX design, marketing. Review & Final Project.' },
      ],
    },
    resources: [
      { title: 'Nudge Theory Explained', channel: 'The Economist', url: 'https://www.youtube.com/results?search_query=nudge+theory+behavioral+economics+explained', note: 'Clear intro to choice architecture.' },
      { title: 'Thinking, Fast and Slow — Summary', channel: 'YouTube', url: 'https://www.youtube.com/results?search_query=thinking+fast+and+slow+kahneman+summary', note: "Kahneman's book is the foundation — multiple good summaries available." },
      { title: 'The Power of Habit — Core Ideas', channel: 'YouTube', url: 'https://www.youtube.com/results?search_query=power+of+habit+charles+duhigg+summary', note: "Duhigg's habit loop is required content." },
      { title: 'Behavioral Economics', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+economics+behavioral', note: 'Good intro connecting economics and psychology.' },
    ],
    quiz: [
      { q: 'Nudge theory (Thaler & Sunstein) means:', opts: ['Financial incentives to change behavior', 'Designing choice architectures that steer toward better decisions without removing options', 'Punishing undesirable behavior', 'Enforcing rules through law'], ans: 1, exp: 'Nudges preserve freedom of choice while making better options easier — e.g., making healthy food the default.' },
      { q: 'Loss aversion means people:', opts: ['Are more motivated by gains than losses', 'Feel the pain of a loss ~2× as strongly as an equivalent gain', 'Always avoid all risk', 'Underestimate negative events'], ans: 1, exp: 'Kahneman & Tversky: losing $100 hurts roughly twice as much as gaining $100 feels good.' },
      { q: 'The default effect shows people tend to:', opts: ['Rationally evaluate all options', 'Stick with preset options rather than actively choosing alternatives', 'Always choose the best option', 'Prefer the newest option'], ans: 1, exp: 'People are sticky — they tend not to opt out of defaults. Organ donation rates differ dramatically between opt-in vs. opt-out countries.' },
      { q: "Fogg's Behavior Model says behavior occurs when:", opts: ['External incentives are large enough', 'Motivation, ability, and a prompt occur simultaneously', 'Social norms support the behavior', 'Conscious deliberation precedes action'], ans: 1, exp: 'B = MAP: all three (Motivation, Ability, Prompt) must converge at the same moment.' },
      { q: 'Sludge in behavioral science is:', opts: ['Positive nudges improving outcomes', 'Unnecessary friction making good behaviors harder', 'Government behavioral regulations', "Resistance to habit change"], ans: 1, exp: "Sludge is the opposite of nudge: friction that makes beneficial actions difficult (e.g., long opt-out forms)." },
      { q: "Duhigg's habit loop consists of:", opts: ['Stimulus, Response, Reinforcement', 'Cue, Routine, Reward', 'Motivation, Action, Outcome', 'Trigger, Behavior, Consequence'], ans: 1, exp: 'Cue triggers a routine, which delivers a reward that reinforces the loop.' },
      { q: 'Social proof as a behavioral driver means:', opts: ['People follow authority figures', "People look to others' behavior to guide their own", 'Behavior is determined by legal consequences', 'People prioritize social approval over interest'], ans: 1, exp: "In uncertainty, we look to what others are doing — hotels use 'Most guests reuse towels' signs because it outperforms environmental messaging." },
      { q: 'Which is a behavioral intervention?', opts: ['A law mandating vaccine use', 'Placing fruit at eye level to increase healthy eating', 'A fine for littering', 'A public awareness campaign only'], ans: 1, exp: "Changing the choice environment (placement, defaults, framing) to make the desired choice easier — that's behavioral science." },
    ],
  },
  {
    id: 'abnormal-psych', grade: 12, term: 'Spring', credits: 1.0,
    name: 'Abnormal Psychology',
    description: 'Examines classification, causes, and treatment of psychological disorders through a biopsychosocial lens — evaluating biological, psychological, and sociocultural factors, and how culture and stigma shape mental health.',
    syllabus: {
      objectives: ['Apply the biopsychosocial model to psychological disorders', 'Differentiate major DSM-5 categories and diagnostic criteria', 'Critically evaluate multiple treatment approaches', 'Analyze how culture and stigma shape definitions of abnormality'],
      units: [
        { week: '1–2', topic: 'Defining Abnormality', desc: 'Historical perspectives, 4 Ds framework, cultural relativity.' },
        { week: '3–4', topic: 'Anxiety Disorders', desc: 'GAD, Panic Disorder, Specific Phobias, Social Anxiety — symptoms and CBT treatment.' },
        { week: '5–6', topic: 'OCD & Related Disorders', desc: 'OCD, Body Dysmorphic Disorder; basal ganglia circuits; ERP treatment.' },
        { week: '7–8', topic: 'Depressive & Bipolar Disorders', desc: 'MDD, PDD, Bipolar I & II; neurobiological models; mood stabilizers.' },
        { week: '9–10', topic: 'Schizophrenia Spectrum', desc: 'Positive vs. negative symptoms, dopamine hypothesis, antipsychotics.' },
        { week: '11–12', topic: 'Personality Disorders', desc: 'Cluster A/B/C; BPD and NPD in depth; DBT for BPD.' },
        { week: '13–14', topic: 'Trauma & Dissociative Disorders', desc: 'PTSD, DID; neurobiological trauma impact; trauma-informed care.' },
        { week: '15–16', topic: 'Neurodevelopmental Disorders', desc: 'ADHD, Autism Spectrum Disorder, specific learning disorders.' },
        { week: 17, topic: 'Psychotherapy in Depth', desc: 'CBT (Beck), DBT (Linehan), psychodynamic, EMDR; evidence base.' },
        { week: 18, topic: 'Mental Health Systems & Stigma', desc: 'Deinstitutionalization, community mental health, reducing stigma. Final assessment.' },
      ],
    },
    resources: [
      { title: 'Crash Course Psychology — Disorders #28–40', channel: 'CrashCourse', url: 'https://www.youtube.com/results?search_query=crash+course+psychology+psychological+disorders', note: 'Episodes 28–40 cover abnormal psychology comprehensively.' },
      { title: 'What is Schizophrenia?', channel: 'TED-Ed', url: 'https://www.youtube.com/results?search_query=TED-Ed+what+is+schizophrenia', note: 'Animated explainer of symptoms and neuroscience.' },
      { title: 'National Institute of Mental Health', channel: 'NIMH', url: 'https://www.nimh.nih.gov', note: 'Most authoritative source on US mental health statistics and research.' },
      { title: 'Psychological Disorders Unit', channel: 'Khan Academy', url: 'https://www.khanacademy.org/science/ap-psychology', note: 'Navigate to Psychological Disorders.' },
    ],
    quiz: [
      { q: 'The biopsychosocial model holds that disorders arise from:', opts: ['Purely genetic factors', 'Interaction of biological, psychological, and social factors', 'Primarily childhood trauma', 'Societal labeling alone'], ans: 1, exp: 'Biology, psychology, and social context all contribute — no single factor explains mental illness.' },
      { q: 'PTSD is classified in DSM-5 under:', opts: ['Anxiety Disorders', 'Depressive Disorders', 'Trauma- and Stressor-Related Disorders', 'Dissociative Disorders'], ans: 2, exp: 'DSM-5 (2013) moved PTSD to a new category reflecting its distinct etiology.' },
      { q: '"Positive symptoms" of schizophrenia include:', opts: ['Flat affect and reduced speech', 'Social withdrawal and anhedonia', 'Hallucinations and delusions', 'Poor motivation'], ans: 2, exp: 'Positive = additions to behavior (hallucinations, delusions). Negative = reductions (flat affect, poverty of speech).' },
      { q: 'BPD is characterized by:', opts: ['Grandiosity and lack of empathy', 'Instability in mood, identity, and relationships + fear of abandonment', 'Paranoid thinking', 'Intrusive thoughts and rituals'], ans: 1, exp: "BPD's core: emotional dysregulation, unstable relationships, impulsivity, intense fear of abandonment." },
      { q: 'DBT was developed to treat:', opts: ['Schizophrenia', 'Borderline Personality Disorder', 'MDD', 'ADHD'], ans: 1, exp: "Linehan developed DBT for BPD — combining CBT with mindfulness and acceptance." },
      { q: 'The dopamine hypothesis of schizophrenia:', opts: ['Too little dopamine everywhere', 'Too much serotonin', 'Excess dopamine in mesolimbic pathways causes positive symptoms', 'Insufficient acetylcholine'], ans: 2, exp: 'Excess mesolimbic dopamine → positive symptoms; deficient prefrontal dopamine → negative symptoms.' },
      { q: 'A phobia differs from GAD in that it involves:', opts: ['Worry about many areas', 'Intense fear of a specific object or situation', 'Recurring intrusive thoughts and rituals', 'Sudden fear episodes without a trigger'], ans: 1, exp: 'Specific phobia = disproportionate, circumscribed fear of one stimulus leading to active avoidance.' },
      { q: 'Deinstitutionalization in the 1960s–70s resulted in:', opts: ['Building more psychiatric hospitals', 'Release of patients into communities, often without adequate support', 'Increased ECT use', 'Mandatory treatment laws'], ans: 1, exp: 'Patients were moved out of institutions, but community mental health infrastructure was often inadequate.' },
      { q: 'ADHD is most effectively treated with:', opts: ['Psychoanalysis alone', 'Stimulant medication + behavioral therapy combined', 'Hospitalization', 'SSRIs as first-line'], ans: 1, exp: 'Combined treatment consistently outperforms either approach alone.' },
      { q: 'Labeling theory of mental illness suggests:', opts: ['Illness is caused by genetic mutations', 'Psychiatric labels create stigma that can reinforce abnormal behavior', 'Disorders are fully curable with medication', 'Psychologists should not diagnose'], ans: 1, exp: "Once labeled 'mentally ill,' people are treated differently and may internalize that identity — stigma as self-fulfilling prophecy." },
    ],
  },
  {
    id: 'counseling', grade: 12, term: 'Spring', credits: 1.0,
    name: 'Counseling & Mental Health Studies',
    description: 'Introduction to counseling theory and practice — therapeutic relationships, assessment, crisis intervention, trauma, cultural competency, and professional ethics. Essential for clinical, social work, and counseling careers.',
    syllabus: {
      objectives: ['Compare major counseling theories (psychodynamic, humanistic, CBT, existential)', 'Demonstrate core counseling skills: empathy, active listening, open-ended questioning', 'Understand crisis intervention and suicide risk assessment protocols', 'Apply cultural competency to diverse client populations'],
      units: [
        { week: '1–2', topic: 'Introduction to Counseling Theories', desc: 'Psychodynamic, humanistic (Rogers), CBT, existential, and solution-focused approaches.' },
        { week: '3–4', topic: 'The Therapeutic Relationship', desc: "Empathy, unconditional positive regard, congruence (Rogers' core conditions), therapeutic alliance." },
        { week: '5–6', topic: 'Assessment & Case Formulation', desc: 'Intake interviews, mental status exam, biopsychosocial assessment, treatment planning.' },
        { week: '7–8', topic: 'Crisis Intervention & Suicide Prevention', desc: 'Crisis response models, SLAP risk assessment, safety planning, mandatory reporting.' },
        { week: '9–10', topic: 'Grief, Loss & Trauma-Informed Care', desc: 'Complicated grief, trauma-informed approaches, EMDR basics, vicarious trauma.' },
        { week: '11–12', topic: 'Substance Use & Addiction Counseling', desc: 'Addiction models, Motivational Interviewing (MI), harm reduction.' },
        { week: '13–14', topic: 'Group Therapy & Family Systems', desc: "Yalom's curative factors, Bowen's family systems, structural family therapy." },
        { week: '15–16', topic: 'Cultural Competency', desc: 'Multicultural competencies, implicit bias in therapy, culturally adapted interventions.' },
        { week: 17, topic: 'Professional Ethics', desc: 'APA ethics code, confidentiality limits (Tarasoff), dual relationships, supervision.' },
        { week: 18, topic: 'Careers in Mental Health', desc: 'Psychologist vs. counselor vs. social worker vs. psychiatrist; graduate pathways; licensure.' },
      ],
    },
    resources: [
      { title: 'The Power of Vulnerability', channel: 'TED (Brené Brown)', url: 'https://www.youtube.com/results?search_query=Brene+Brown+power+of+vulnerability+TED', note: "One of the most-watched TED talks — directly relevant to the therapeutic relationship." },
      { title: 'Motivational Interviewing — Introduction', channel: 'YouTube', url: 'https://www.youtube.com/results?search_query=motivational+interviewing+introduction+counseling', note: 'MI is a core evidence-based counseling technique.' },
      { title: "Carl Rogers' Person-Centered Therapy", channel: 'YouTube', url: 'https://www.youtube.com/results?search_query=carl+rogers+person+centered+therapy+explained', note: 'Core theory for Units 1–2.' },
      { title: 'APA Ethics Code', channel: 'APA', url: 'https://www.apa.org/ethics/code', note: 'Required for the professional ethics unit.' },
    ],
    quiz: [
      { q: "Rogers' person-centered therapy core conditions are:", opts: ['Interpretation, confrontation, catharsis', 'Empathy, unconditional positive regard, congruence', 'Behavioral activation, cognitive restructuring, homework', 'Dream analysis, free association, transference'], ans: 1, exp: "Rogers' three core conditions: empathy, UPR (non-judgmental acceptance), and congruence (therapist genuineness)." },
      { q: 'Active listening in counseling includes:', opts: ['Giving advice and solutions', 'Reflective listening, paraphrasing, and open-ended questions', 'Maintaining silence throughout', 'Interpreting unconscious motivations'], ans: 1, exp: 'Active listening is non-directive — reflect back, paraphrase, ask questions that open rather than close.' },
      { q: 'Crisis intervention focuses on:', opts: ['Long-term comprehensive treatment', 'Immediate stabilization and safety', 'Always involving medication', 'Formal diagnosis before beginning'], ans: 1, exp: 'Crisis intervention: assess safety, stabilize, connect to resources. Not the same as ongoing therapy.' },
      { q: 'Cultural competency in counseling requires:', opts: ['Treating all clients identically', 'Self-awareness of biases + cultural knowledge + culturally appropriate skills', "Learning clients' native languages", 'Avoiding discussion of cultural differences'], ans: 1, exp: "Sue & Sue's model: awareness (your own biases), knowledge (client's culture), skills (adapted interventions)." },
      { q: 'Family systems theory views problems as:', opts: ['Individual pathology', 'Symptoms of dysfunction within the family system', 'Primarily genetic', 'Products of childhood trauma only'], ans: 1, exp: "The identified 'patient' often reflects a dysfunctional family system. Treat the system." },
      { q: 'Confidentiality limits include:', opts: ['Sharing with all supervisors', 'Imminent danger and mandatory abuse reporting', 'Any situation needing help', 'Client request to share with family'], ans: 1, exp: "Tarasoff (1976): therapists must breach confidentiality when clients pose credible threats to identifiable third parties." },
      { q: 'Motivational Interviewing (MI) was developed for:', opts: ['Severe psychiatric disorders', 'Ambivalence about behavior change, especially addiction', 'Childhood trauma', 'Cognitive distortions in anxiety'], ans: 1, exp: "MI is collaborative and goal-oriented — helping clients explore and resolve ambivalence." },
      { q: 'Dual relationships in counseling ethics describes:', opts: ['Treating two clients simultaneously', 'Having both professional and personal relationship with the same client', 'A client seeing two therapists', 'Using two theoretical orientations'], ans: 1, exp: 'Dual relationships create conflicts of interest and power imbalances — banned by APA ethics.' },
      { q: 'The therapeutic alliance research consistently shows:', opts: ['Technique is the most important outcome predictor', 'Relationship quality is the strongest predictor of therapy outcomes', 'CBT always outperforms other modalities', 'Credentials predict outcomes better than relationship quality'], ans: 1, exp: "The alliance (trust, goal agreement, bond) explains more outcome variance than specific techniques — the 'Dodo Bird verdict.'" },
      { q: 'A psychiatrist differs from a psychologist in that a psychiatrist:', opts: ['Can only do psychotherapy', 'Has an MD and can prescribe medication', 'Has a PhD and focuses on research', 'Is federally licensed but not state licensed'], ans: 1, exp: 'Psychiatrists = MD + prescribing rights. Psychologists = PhD/PsyD + psychological assessment + therapy.' },
    ],
  },
];

export default function PsychologyPathway() {
  return <PathwayPage meta={META} schedule={SCHEDULE} courses={COURSES} />;
}
